### ISSUE TITLE
Voice 5.0.1playback issue

### ISSUE THREAD

**Issue by ddt000** [PaulWoitaschek/Voice#1000]
Just started recently on a Pixel 2.  Playback is just a repeating notification sound (ding, ding, ding).  Progress bar/time doesn't change.  Occasionally there is short bits of book sound between the dings.  No other phone issues to report.

**Comment by hackbot1337** [comment]
i too have this issue. the voice notification does not go away after i close voice. im using a pixel 2 xl and havent had an issue before a few days ago.

**Comment by ddt000** [comment]
Solution for me: reinstall Voice.  Very strange issue but the solution was fairly painless.
