### ISSUE TITLE
Voice auto-merged series of book

### ISSUE THREAD

**Issue by soulowar** [PaulWoitaschek/Voice#1001]
Voice auto-merge series of book from the same author, the issue is that some are in the wrong order, some are different trilogy from different world and I don't want to read them in writing order but by interest. Having a 71hours listening time is daunting but the worse is that voice forgot where I was in the book I had started when it merged with the new files that I added. so now I have to listen to 71hours before I can remove a book from my phone because I guess that if i remove a book it will not remember my progress again?

Thanks

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
