### ISSUE TITLE
[Feature request]: audiobook name based on folder name and not name on the title tag of the first file/track

### ISSUE THREAD

**Issue by MagTun** [PaulWoitaschek/Voice#1010]
**Problem description**
The name of my audiobooks on the main voice screen [where there are the Current, Not yet started and completed] are based on the title tag of the first file/track of the audiobook. So if I have an audiobook in a folder named `Anatomy` whose first track is named `01 Introduction.mp3` with the title `Introduction`, then the whole audiobook is called `Introduction` instead of `Anatomy`. 

**Describe the solution you'd like**
On the main screen, the audiobook should be called `Anatomy` (which is the folder name) and not `Introduction`. 

**Additional context**
It's related to this [issue](https://github.com/PaulWoitaschek/Voice/issues/781) but it's not the same feature request. 
I tried to remove the title tag of the tracks to prevent this, but they are added automatically when I transfert the file to my phone. 

 Version 5.0.1

**Comment by PaulWoitaschek** [comment]
This is no longer relevant with the V7 UI
