### ISSUE TITLE
[BUG] App not updating the list of files upon adding new files in the audio folder

### ISSUE THREAD

**Issue by Mek101** [PaulWoitaschek/Voice#1011]
Adding a new file in the audio folder doesn't make it appear in the application. Restarting the application doesn't work either.
Adding perhaps a scan triggered with a file system watcher, or just a button to trigger a manual scan?

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
