### ISSUE TITLE
Dark Theme Toggle

### ISSUE THREAD

**Issue by z4lpha** [PaulWoitaschek/Voice#1012]
On Android 9 there was a dark theme toggle in settings. Once I upgraded to Android 10 it's now gone and dark theme follows the system theme. Can we please keep the toggle as I like to have the system in light mode but certain apps in dark mode. Perhaps a Enable / Disable / Auto switch?

OnePlus 5T with OxygenOS 10

**Comment by D-aan** [comment]
I second this. A feature to choose dark, light or system theme would be nice. :-)

**Comment by PaulWoitaschek** [comment]
On Android 10 that toggle is part of your system settings. Voice will follow the system dark / light theme.

**Comment by Flavelius** [comment]
+1 for adding the control as suggested, many apps do this, light, dark & system where system does what voice currently does by unfortunately unconfigurable default
