### ISSUE TITLE
5.0.2 release missing from Play Store

### ISSUE THREAD

**Issue by Emilv2** [PaulWoitaschek/Voice#1015]
The latest release, 5.0.2, is missing from the Google Play Store.

**Comment by innesst** [comment]
https://play.google.com/store/apps/details?id=de.ph1b.audiobook

**Comment by ZKjellberg** [comment]
There do not seem to be any logic changes yet for 5.0.2. It appears that was just an increment for the current code, so when changes occur it will be handled. (Though normally people use a `develop` branch for staging new changes)

**Comment by Emilv2** [comment]
5.0.2 fixes #977

**Comment by wberrier** [comment]
I was about to file #977, glad to see it's been fixed already.

But, 5.0.2 is available on one phone I have (One Plus A5000 running Android 9), but on another phone (Samsung Galaxy S9 running Android 10) only 5.0.1 is available.  I've uninstalled and reinstalled on both phones, and still end up with the different versions.

**Comment by Emilv2** [comment]
Weird, it's no available for my One Plus running Android 9. You can download and install 5.0.2 from https://github.com/PaulWoitaschek/Voice/releases until this is fixed.

**Comment by Emilv2** [comment]
@PaulWoitaschek Care to take a look at this? I suppose it must be some setting in the Play Store that prevents it from being released to some phones? I have a new phone with Android 10 and on that phone too 5.0.1 is the latest available version.

**Comment by wommel** [comment]
This issue still persists :(

**Comment by PaulWoitaschek** [comment]
A new version is in the making that will fix it. If you can't wait you can join the public beta:
https://play.google.com/apps/testing/de.ph1b.audiobook

**Comment by ZKjellberg** [comment]
![image](https://user-images.githubusercontent.com/143709/153907493-102249b7-ea29-4758-8fa5-8c4677c200b7.png)

Can you make the group public to opt-in for the beta?

**Comment by PaulWoitaschek** [comment]
It shows as public. 

But apparently it's in an extended review. Can you check if you can join from your phone?
https://play.google.com/store/apps/details?id=de.ph1b.audiobook

**Comment by ZKjellberg** [comment]
Successfully opted in and updated.

I noticed a strange message on the Audiobooks Folder page. The dialog can be dismissed but returned each time I visit the page.
![image](https://user-images.githubusercontent.com/143709/153965894-a76351f0-36ac-4037-af10-d3707d78969d.png)

**Comment by PaulWoitaschek** [comment]
Yeah, it's a placeholder and heavy under development. 
Please open tickets if you find bugs. 
This one is fixed by #1127
