### ISSUE TITLE
M4B file does not play

### ISSUE THREAD

**Issue by StarPicard** [PaulWoitaschek/Voice#1017]
Hi, when I start an M4B file the book immediately stops playing and I never hear any sound. Here some information to the file:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file.m4b':
  Metadata:
    major_brand     : M4A 
    minor_version   : 512
    compatible_brands: M4A isomiso2
    title           : Title
    artist          : Artist
    album_artist    : Artist
    album           : Title
    date            : 2018
    encoder         : Lavf58.45.100
    genre           : Audiobook
    copyright       : Text
    track           : 1/1
  Duration: 32:17:01.26, start: 0.000000, bitrate: 82 kb/s
    Chapter #0:0: start 0.000000, end 19.180000
    Metadata:
      title           : 
    Chapter #0:1: start 19.180000, end 52.918000
...
    Chapter #0:120: start 116201.709000, end 116221.214000
    Metadata:
      title           : 
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 81 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(eng): Data: bin_data (text / 0x74786574)
    Metadata:
      handler_name    : SubtitleHandler
Unsupported codec with id 100359 for input stream 1
```
The file was generated with the following command:
`ffmpeg -i in.m4a -c:v copy -c:a libfdk_aac -vbr 3 out.m4b`

After doing this to the file everything works:
`ffmpeg -i in.m4b -c copy -dn -map_metadata:c -1 out.m4b`

The point is, that VLC plays the file anyway and as i understand [this post](https://trac.ffmpeg.org/ticket/6016#comment:3) this is a normal chapters track. Is this an issue for you or should i report this to another place?

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
