### ISSUE TITLE
MKA audiobook restarts to beginning upon any seek.

### ISSUE THREAD

**Issue by eode** [PaulWoitaschek/Voice#1018]
I have an audiobook that works in (at least some) players -- an MKA (matroska audio) file.  It is recognized and correctly handled in Gnome's default video, and in VLC, and on android, in Sirin (another audiobook reader).

In Voice, chapters are recognized, and I can play the book -- however, *any* seek results in a return to the beginning of the file.  This includes chapter selection, fast forward, rewind, and bookmark selection.

Happy to help however I can.

**Comment by stravaig** [comment]
Having exactly to same issue. Otherwise the app works perfectly. Any idea why this might be happening?

Cheers.

**Comment by eode** [comment]
I imagine it's incorrect seek.  Something about MKA is handled differently by the system -- at least, I assume so, since most audiobook players on Android have this issue.

The only exception I've found is Sirin.  I'd rather be using Voice, but it's Sirin is a really nice player, and you probably won't go back once you've bought it.

**Comment by LiftedStarfish** [comment]
This is still happening. I built an MKA manually using MKVToolNix, and it worked fine _before_ I added the chapters. After adding chapters to the file, it broke. Even if I _remove_ the edition entry that the chapters are stored in, the seek problem persists.

**Comment by LiftedStarfish** [comment]
Update: For some reason, if you create an appropriately formatted XML chapter file with the apprapriate timestamps, and then merge it with a bare MKV file using mkvmerge, it works. I do not know why, but it does. Bellow is an example of a file with such formatting from [mkvtoolnix.download](https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.chapters). It's slightly modified from the original (encoding was changed from "ISO-8859-1" to "UTF8", which is what I did for my test):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Chapters SYSTEM "matroskachapters.dtd">
<Chapters>
  <EditionEntry>
    <ChapterAtom>
      <ChapterTimeStart>00:00:30.000</ChapterTimeStart>
      <ChapterTimeEnd>00:01:20.000</ChapterTimeEnd>
      <ChapterDisplay>
        <ChapterString>A short chapter</ChapterString>
        <ChapterLanguage>eng</ChapterLanguage>
      </ChapterDisplay>
      <ChapterAtom>
        <ChapterTimeStart>00:00:46.000</ChapterTimeStart>
        <ChapterTimeEnd>00:01:10.000</ChapterTimeEnd>
        <ChapterDisplay>
          <ChapterString>A part of that short chapter</ChapterString>
          <ChapterLanguage>eng</ChapterLanguage>
        </ChapterDisplay>
      </ChapterAtom>
    </ChapterAtom>
  </EditionEntry>
</Chapters>
```
Please note that the app _does not_ detect nested chapters. It will only work with top level chapters. In the example above Voice would not detect (or at least not display or make use of) the chapter labeled "A part of that short chapter".

**Comment by PaulWoitaschek** [comment]
In the recent version (7.0.11+) I added an improvement to fix these chapters who overlap.
That should solve this issue (hopefully)

**Comment by eode** [comment]
I can confirm that this issue has been resolved.  Thank you!
