### ISSUE TITLE
After rewinding, Voice jumps back

### ISSUE THREAD

**Issue by cwap71** [PaulWoitaschek/Voice#1019]
Hi, 
voice is great. However, I regularly face the following problem: As I like to continue my audio books a chapter or two earlier than where I stopped before (just to recall), I have to rewind. After roughly 20 sec playing the chapter I chose, the app always jumps back to where I stopped before (probably a bookmark?). This issue arises regularly - however, only the first time after starting the app.
I wonder whether this might be an issue.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
