### ISSUE TITLE
Add "all files access" permission with Android 11

### ISSUE THREAD

**Issue by LexiconCode** [PaulWoitaschek/Voice#1021]
I have to thank you for such a wonderful app! You've made a nice clean design and kept it simple.

Over the years I've become accustomed to using Voice as a hub for all of my audio from many different app sources. Unfortunate for sizable portion of those apps the audio stored what is now protected by scoped storage on Android 11. I'm not sure how Google might interpret adding such a permission even if it could be made optional through the settings. 

An alternative would be to add the permission to the F-droid version.

**Comment by PaulWoitaschek** [comment]
I managed to add support for SAF in the latest betas 🎉

**Comment by LexiconCode** [comment]
> I managed to add support for SAF in the latest betas 🎉

If I could send you or the project a donation it would be great. Just a small way to say thank you.

In the future I would love to familiarize myself with android development to contribute to projects like this.

**Comment by joshunger** [comment]
I just upgraded to Android 14 ... does this work in the latest production build? When I go to Permissions I see No permissions requested.

**Comment by PaulWoitaschek** [comment]
Yes. It uses the aforementioned storage Access Framework
