### ISSUE TITLE
Android Auto UI disappears when pausing playback

### ISSUE THREAD

**Issue by ghost** [PaulWoitaschek/Voice#1023]
When playing a book while  my phone (Galaxy S10) is connected to Android Auto (Kenwood 7706S) there's a playback UI, and there's the standard options for play/pause at the bottom of the screen.

If the audio book being played is paused, the controls vanish.  The only option I've found to restart the playback is by accessing the application on the phone.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
