### ISSUE TITLE
Voice crashs MIB2 (VW, Skode, etc)

### ISSUE THREAD

**Issue by Toschko** [PaulWoitaschek/Voice#1024]
Since last updatet Voice (V5.0.1) crashs my Android Auto MIB2 Device. When i usd other Programs like Spotify, GoneMAD oder Simple Radio everthingis fine. Sometime it crashes after 5 min, sometimes after 20.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
