### ISSUE TITLE
Slider value crash across tracks

### ISSUE THREAD

**Issue by natebragg** [PaulWoitaschek/Voice#1030]
When listening to a book at 2.3x speed, I reached the end of a file, and while transitioning to the next file, Voice crashed.  When I try to open that book again, Voice crashes again.  Other books work fine.

Here is the output of `adb logcat`:

09-30 21:31:14.579 14960 14960 D MediaBrowserCompat: Connecting to a MediaBrowserService.                                                                                
09-30 21:31:14.585 14960 14960 D MediaBrowserCompat: Connecting to a MediaBrowserService.                                                                                      
09-30 21:31:14.645 14960 14960 D AndroidRuntime: Shutting down VM                                                                            
09-30 21:31:14.656 14960 14960 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                                                    
09-30 21:31:14.656 14960 14960 E AndroidRuntime: Process: de.ph1b.audiobook, PID: 14960                                                      
09-30 21:31:14.656 14960 14960 E AndroidRuntime: java.lang.IllegalStateException: Slider value must be greater or equal to valueFrom, and lower or equal to valueTo
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at com.google.android.material.slider.Slider.validateValues(Slider.java:517)                                       
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at com.google.android.material.slider.Slider.validateConfigurationIfDirty(Slider.java:530)    
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at com.google.android.material.slider.Slider.onDraw(Slider.java:1366)                                                                                                                      
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21436)                                                                  
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20313)                                
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21168)                
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20304)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21168)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20304)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21168)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20304)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21168)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20304)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21168)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20304)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21168)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20304)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21168)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.draw(View.java:21439)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at com.android.internal.policy.DecorView.draw(DecorView.java:806)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:20313)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3610)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3418)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:725)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-30 21:31:14.656 14960 14960 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
09-30 21:31:14.658  1279  2020 W ActivityTaskManager:   Force finishing activity de.ph1b.audiobook/.features.MainActivity

**Comment by thomas725** [comment]
Had the same issue a few times and had to delete as torage of the app each time to be able to continue with the current audiobook...

Crash log example:
https://del.dog/crimenelic.txt

**Comment by serverok** [comment]
I have this problem. i am halfway through an audio book, whenever i click on it, the app crash. I had this happend to some other audio book, that happened after i finish listening to audio book, then one i have issue in midway. Please fix.

**Comment by mehdisadeghi** [comment]
As a workaround switch to the main page of the app and press the play button. This worked for me.

**Comment by serverok** [comment]
@mehdisadeghi  Thanks, fixed my problem.

**Comment by micressor** [comment]
Confirm this problem with voice v5.0.2.
Happended with 1.0x book speed.
@mehdisadeghi Thanks for the workaround.

```
01-06 13:09:37.285 17765 17765 E AndroidRuntime: FATAL EXCEPTION: main
01-06 13:09:37.285 17765 17765 E AndroidRuntime: Process: de.ph1b.audiobook, PID: 17765
01-06 13:09:37.285 17765 17765 E AndroidRuntime: java.lang.IllegalStateException: Slider value must be greater or equal to valueFrom, and lower or equal to valueTo
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at com.google.android.material.slider.Slider.validateValues(Slider.java:517)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at com.google.android.material.slider.Slider.validateConfigurationIfDirty(Slider.java:530)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at com.google.android.material.slider.Slider.onDraw(Slider.java:1366)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21975)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20852)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21707)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20843)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21707)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20843)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21707)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20843)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21707)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20843)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21707)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20843)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21707)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20843)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21707)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4432)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.draw(View.java:21978)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:808)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20852)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3767)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3495)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2779)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:726)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-06 13:09:37.285 17765 17765 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
01-06 13:09:37.286  1138  4841 I am_crash: [17765,0,de.ph1b.audiobook,549994052,java.lang.IllegalStateException,Slider value must be greater or equal to valueFrom, and lower or equal to valueTo,Slider.java,517]
```

**Comment by thomas725** [comment]
thanks for that workaround @mehdisadeghi !!

I was afraid after encountering that bug again that I would have to reset the app's storage (and loose the stored progress) to continue listening to my current audio book..

**Comment by PaulWoitaschek** [comment]
Thanks for the report. This is fixed in the latest version.
