### ISSUE TITLE
Please make shourcut icons adaptive

### ISSUE THREAD

**Issue by 532910** [PaulWoitaschek/Voice#1031]
![image](https://user-images.githubusercontent.com/14617699/96517811-4b126300-1272-11eb-9a76-e5e51b8180ae.png)

Known apps with adaptive shortcut icons:
[Element](https://github.com/vector-im/element-android), [Orgzly](https://github.com/orgzly/orgzly-android), [Calendar](https://github.com/LineageOS/android_packages_apps_Etar), [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger), SoundCloud
![image](https://user-images.githubusercontent.com/14617699/96517260-4ef1b580-1271-11eb-8723-448ca6413dc2.png)

All of these shortcuts are created the same way, via long press from the main icon and dragging it to the desktop.

**Comment by PaulWoitaschek** [comment]
Thanks for your suggestion! Shortcuts are already adaptive: https://github.com/PaulWoitaschek/Voice/blob/main/app/src/main/res/mipmap-anydpi-v26/ic_shortcut_play.xml

**Comment by 532910** [comment]
They doesn't look adaptive: see the screenshot.
