### ISSUE TITLE
Supercompact Widget

### ISSUE THREAD

**Issue by ex-ego** [PaulWoitaschek/Voice#1034]
Is it possible to create a Compact Widget? 
I think, the cover and play button is enough.
Am I alone with that wish?

Thanks

**Comment by gwarser** [comment]
I can resize to one tile.

**Comment by ex-ego** [comment]
I know, but then its ugly.
The Problem is, when i have 1 tile, I cannot open the app.
Tapping on the cover (or title) opens the app.
Solution... 2 tile widget with cover and only the play button
By resizing the widget the coverpic disapears very fast (unfortunately not the skipping buttons)

**Comment by MagTun** [comment]
In version 5, I could resize the widget down to 2x1. But I have just installed the beta version (6.0.9) and now I can't resize the widget anymore. It takes 4 tiles. That's too much! I like the widget when was possible to resize it down to 2x1. I don't need the title nor the rewind and fast forward buttons : just a way to open the app and play/pause.

**Comment by PaulWoitaschek** [comment]
Im on Android 13 and I can freely resize it down to 1x1 with 6.0.9.
In 1x1 I can also click on the title to open the app. 
![Uploading Screenshot_20220819-124705.png…]()

**Comment by PaulWoitaschek** [comment]
![Screenshot_20220819-124705](https://user-images.githubusercontent.com/743462/185602916-6e2777be-72bf-4227-a0d5-5124026c5f7c.png)

**Comment by MagTun** [comment]
@PaulWoitaschek, thanks for your quick reply! Sorry, you are right, it's working great! It's just that I didn't know that to get the resize blue I had to not only long-touch it (to kind of "select" it) but then to move to another spot on my screen. It's only after I move it around that the blue square appears and I am then able to resize it. 
Again, I am sorry about this.

**Comment by MagTun** [comment]
Sorry you are right, it's working great! It's just that I didn't know that to get the resize blue I had to not only long-touch it (to kind of "select" it) but then to move to another spot on my screen. It's only after I move it around that the blue square appears and I am then able to resize it. 
Again, I am sorry about this.

**Comment by PaulWoitaschek** [comment]
Absolutely nothing to be sorry about!
It's kind of the beauty of Android: there are many hidden gems. The basic usage is simple and there are features for power users without complicating the basic usage.
