### ISSUE TITLE
[Bug] Duplicate chapters in in chapter picker even though there isn't within the book folder

### ISSUE THREAD

**Issue by jbciardi** [PaulWoitaschek/Voice#1035]
I have the harry potter series in a folder. Within the folder containing all the mp3s, there is the 37 files for the 37 chapters in the deathly hallows. However when I am in the voice app and go to the chapter picker, there are several duplicates of the chapters. 107 of them. Do not know what's wrong, only happens with the harry potter books and not my others.

**Comment by Juul** [comment]
Seeing the same issue in version 6.0.9 with a different book.

Filenames in the audiobook's directory are:

```
Chapter 001.mp3
Chapter 002.mp3
Chapter 003.mp3
Chapter 004.mp3
etc.
```

Chapter list in Voice shows:

```
1 - Chapter 1
2 - Chapter 2
3 - Chapter 1
4 - Chapter 2
5 - Chapter 3
6 - Chapter 2
7 - Chapter 3
8 - Chapter 4
9 - Chapter 3
etc.
```

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is old and a lot changed in the meantime. If not please open a new issue.
