### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [PaulWoitaschek/Voice#1038]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
App version is 5.0.2, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="473" alt="bug-audiobook" src="https://user-images.githubusercontent.com/18572115/103165565-88880380-4854-11eb-89af-ad6ed9f97005.png">

**Comment by PaulWoitaschek** [comment]
Thanks for the report! That UI element no longer exists in Voice and this should be therefore fixed : )
