### ISSUE TITLE
[FEATURE REQUEST] Manually move books from "listening now" to "finished" and back

### ISSUE THREAD

**Issue by LoginByCall** [PaulWoitaschek/Voice#1043]
**Is your feature request related to a problem? Please describe.**
In some cases, manual adjustment of the folder composition is required. For example, when changing the address of the original folder with files, reloading files.

**Describe the solution you'd like**
Add the ability to manually move books from "listening now" to "finished" and back, please.  For example, through an item with a long press.

**Describe alternatives you've considered**

**Additional context**

**Comment by PaulWoitaschek** [comment]
Thanks for the suggestion! Implemented as of https://github.com/PaulWoitaschek/Voice/commit/265d28e90c0dfd68f5c1295b58875986c42567b1

**Comment by PaulWoitaschek** [comment]
Thanks again @shirish87, great work!
