### ISSUE TITLE
[bug] mp3 is not working

### ISSUE THREAD

**Issue by MagTun** [PaulWoitaschek/Voice#1053]
I tried to listen to a mp3 on Voice but somehow it's not working (even though I can listen to in on VLC on the same phone). 

The file is [here](https://backtracks.fm/80000hours/pr/008e5728-203b-11ea-a4f3-0e09fb6f5fad/67---david-chalmers-on-progress-in-philosophy-virtual-reality-and-the-problem-of-consciousness2.mp3?s=1) which is the direct download link from the [80000hours ](https://80000hours.org/podcast/episodes/david-chalmers-nature-ethics-consciousness) podcast. The file is detected by Voice, the time is also correct but when I press the read button, it doesn't do anything.

I am able to listen to the podcast on Voice after having converted it with a simple ffmpeg command:
`ffmpeg -i "input.mp3" "ouput.mp3"`

Any idea why this is happening and if it could be fixed?

Redmi 7A, Voice version : 5.0.1

**Comment by SirMossi** [comment]
Same problem here with some audiobooks ripped from CD.
I've ripped all my audiobooks the same way with audiograbber and nearly all files work fine. But some CDs will not play before I convert them again with ffmpeg.

**Comment by PaulWoitaschek** [comment]
I assume this is fixed with the latest version. If not please open a new issue
