### ISSUE TITLE
4x1 Widget

### ISSUE THREAD

**Issue by trymeouteh** [PaulWoitaschek/Voice#1054]
Please make a 4x1 widget which can be stretched in a launcher to 5x1 if needed.

**Comment by PaulWoitaschek** [comment]
You should be able to resize the widget freely and it should adapt to the specified size.

**Comment by trymeouteh** [comment]
I am unable to resize the 4x2 widget into a 4x1 on my Android 10 device using the default launcher. I can make the 4x2 widget bigger but not smaller.

**Comment by innesst** [comment]
Unclear. I have a 4x1 widget only. Ver 5.02

**Comment by trymeouteh** [comment]
I have 5.0.2 from F-Droid and I am on LineageOS 17.1 which uses Android 10. And I cannot make the widget shorter. I can make it skinnier such as 2x3, 2x2, 2x1 but not 4x1. I can also make it taller such as 4x3

**Comment by MagTun** [comment]
Same problem as @trymeouteh but on Android 13 (Lineage 20), Voice 8.1.3. 
When I try to have a 4x1 widget, it comes back automatically to 4x2: 

https://github.com/PaulWoitaschek/Voice/assets/15843700/47aac155-9933-4ec8-9934-bbde3d76990a
