### ISSUE TITLE
App increased in size by an order of magnitude between 5.0.0-rc9 and 5.0.0-rc10

### ISSUE THREAD

**Issue by jkidd** [PaulWoitaschek/Voice#1056]
5.0.0-rc9 apk is 5.73MB
5.0.0-rc10 apk is 85.8MB

Looks like it was due to the introduction of ffmpeg.

By the way - l love this app and use it daily. Please include a donate link on your profile so I can send some money your way :)

**Comment by PaulWoitaschek** [comment]
Yes, that's expected. With using Google Plays App bundles the app should still be fairly small.
