### ISSUE TITLE
[bug?] All books from same author shown as one big book

### ISSUE THREAD

**Issue by DaemonPID** [PaulWoitaschek/Voice#1058]
In my books collection I have several books written by the same author. Who woulda guessed? :-)

Strangely, the books from one author (e.g. Jim Butcher, Richard Dawkins etc.) are kinda made into one book. Each book is one (large) m4b file that includes chapter marks. Voice does seem to recognise these correctly, as it jumps from chapter to chapter correctly. However, when I use the pulldown-menu for the chapters, there are two numbers in every line. The first seems to show the chapter numbers off all books as if they were one book, the second shows the chapter number of the current book (correctly). I'll add a screenshot at the end.

As a side effect, the cover art of the book never changes, so while I can listen to all the books without any issue, I only get to see the art and title of the first book.

My first guess was that this was a problem with the tags, so I checked them. The fields I checked showed nothing that I could attribute to the problem. I even changed the tags to make sure, but the result was the same.

Is this a tagging issue or a bug?

![Voice_Chapters png](https://user-images.githubusercontent.com/84448151/118809290-b7a61c80-b8aa-11eb-86e1-2bc5c73e9a57.png)

**Comment by PaulWoitaschek** [comment]
Probably you have selected "Folder with multiple books". 
What it does is that it recognizes each folder / file within that folder as a book. When you now put multiple books into one folder they are treated as a single book. 

Can you post a screenshot of your folder structure?

**Comment by DaemonPID** [comment]
I have a folder "parrots" on my SD-card and I told Voice to scan the complete folder.

At first I thought the same thing as you did. So I changed the folder structure from

/author/
  book01.m4b
  book02.m4b

to

/author
  /book01/book01.m4b
  /book02/book02.m4b

That didn't make a difference - and yes, I told Voice to rescan the folder. I have now put additional books under /author, however, I have not bothered creating directories for them. Voice finds them all - even in the right order (as far as I could tell thus far), but as one large book.

**Comment by PaulWoitaschek** [comment]
Click on "folder with multiple books" and add /author there.

**Comment by DaemonPID** [comment]
Ok, this is a little weird now.

As you will know, I had to remove the parent-folder parrots/ to be able to add author/. I'm glad, I remembered my progress. :smiley: But now, I see all books listed correctly - at least those from the author in question. Note that I did not change anything in the folder, so there are still two subfolders with book1 and book2, but four m4b-files directly in author/ - and these too are listed correctly. Ok, they are not in order, but we'll take it one step at a time. :smile: 

Is this normal/wanted behaviour? The player does suggest adding a folder with multiple audio-books (it even gives "audio-books" as an example).

Just so I don't forget to write this:
I appreciate your support very much!

**Comment by PaulWoitaschek** [comment]
Well it's really simple:

When you add "Folder with multiple books", each subfolder and file will be a book.

I.e if this is your folder structure:

```
audiobooks
    hp1
    myOtherAudiobook
    joanneKeyRowling
        hp2
        hp3
```

If you now add `audiobooks`, then `hp1`, `myOtherAudiobook` and `joanneKeyRowling` will be each recognized as a single audiobook.

To have this correctly, you have multiple options:
* Move hp2 & hp3 one level up and keep using the `audiobooks` folder as the root
* Add `hp1` as a single book, add `myOtherAudiobook` as a single book and `joanneKeyRowling as a `folder with multiple books`.
