### ISSUE TITLE
Cant build app

### ISSUE THREAD

**Issue by newhinton** [PaulWoitaschek/Voice#1060]
The current master cant be build by android studio 4.2 installed via snap.

Android Studio 4.2
Build #AI-202.7660.26.42.7322048, built on April 29, 2021

Building Voice fails with the following error:

> Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'

When reverting gradle to 
>distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-all.zip

it fails with:

> A problem occurred configuring project ':app'.
> \> No supported plugins for Anvil found on project ':app'. Only Android and Java modules are supported for now.

What version/combination do i need to successfully build voice?

**Comment by newhinton** [comment]
it seems android studio canary solves this particular isse, with gradle 7.1 (com.android.tools.build:gradle:7.1.0-alpha03)

Android Studio Bumblebee | 2021.1.1 Canary 3
Build #AI-211.7442.40.2111.7518594

However, it seems the dependencies are out of date so that gradle still errors out building the app

**Comment by PaulWoitaschek** [comment]
You should be able to build all versions from the command line.

I'm currently working on the `compose/book_play` branch which is compatible with AS `2020.3.1 RC 1`

**Comment by PaulWoitaschek** [comment]
@newhinton did it work?

**Comment by newhinton** [comment]
I have not tested using the cli, but the `compose/book_play`-branch works with:

Android Studio Bumblebee | 2021.1.1 Canary 3
Build #AI-211.7442.40.2111.7518594, built on July 2, 2021

I have already created a feature based on that branch, is it reasonable to already create pr's to it?

**Comment by PaulWoitaschek** [comment]
Sure you can do that. The branch itself is very wip. 

I'm very picky on new features 🙈
What are you working on?

**Comment by newhinton** [comment]
Recursive Folderadding. I already implemented something similar, but this time i did it properly regarding the mediascanner (at least in comparison to the last try)

**Comment by newhinton** [comment]
When i build the app with the compose-branch, running it on an actual device results in some strange behavior: It shows two media player, a purple one with a broken layout, which can be closed to reveal the proper one. Is this expected on the branch?

**Comment by PaulWoitaschek** [comment]
Yes
