### ISSUE TITLE
[BUG] App randomly stops playing.

### ISSUE THREAD

**Issue by jeffaphailee** [PaulWoitaschek/Voice#1061]
Huge fan. Been using for a long time. Thank you so much. 

I saw there was an update to help fixed some issues but wasn't sure if mine was one of them and my Voice app is up to date.

It is frustrating, but right now it seems to stop playing the audio randomly. It occurs mainly when I have a book playing in the background and have a different app in the foreground. 

When I go back to the app there are two different scenarios:

1. I go back to the app and find it paused. Then I just hit play and continue the book.

or 

2. I go back to the app, visually the app looks like it is still playing, but the book is not progressing. When I see this I  pause the app and play again then it starts playing right where I left off. 

Please help.
Thank you.

**Comment by kanjieater** [comment]
I also have this issue. It only happens when I first start the app though. The first book I play will only play for about 2 seconds. Even if I pause it myself then unpause it, it will autopause again at that ~2-5 second mark.

So now I have to start a book. Wait. Unpause it, then it's fine from there.

**Comment by HighElder** [comment]
I also have a similar/same problem.
The audio book often plays regularly. Sometimes the audio book pauses after a few minutes. I can restart it but it pauses again after a few minutes. A complete kill of the process helps sometimes, but not nessesarly.

So far, the bug appeared during the use of bluetooth earplugs and phone-speaker. Never with wired earplugs (but that may be random). Unfortunately I can't reproduce it exactly. I thought it might correspond to Bluetooth or WiFi connection, but an attempt to trigger the bug failed.

**Comment by PaulWoitaschek** [comment]
Which app version are you using?

**Comment by HighElder** [comment]
I am using Appversion 6.0.9 via fDroid.

Android 10; Honor 20 Pro

**Comment by PaulWoitaschek** [comment]
Huawei is known for crazy battery optimizations:
https://dontkillmyapp.com/huawei

Can you try if using the suggested solution solves your problem?

**Comment by HighElder** [comment]
My device is running on EMUI 4, so there is no easy solution that I can use.
The problem occured this morning and putting the device on the charger solved the problem for now. Even after detaching it, the bug does not appear again.

I will continue trying to reproduce the problem and will write you, if I find out what triggers it.
Maybe EMUI stopps the process, when the audiobook was paused (an the app not stopped). If I understand correctly, battery optimization is very aggressive against self-launching apps/processes. If the system doesn't recognize the restart of the audio book as an user interaction, that would explain why the playback keeps getting killed. I will try to reproduce that...

**Comment by HighElder** [comment]
Okay, no progress until now. I cannot reproduce the error. It appears sometimes over night, with and without using the sleeptimer before.
Killing the app does not help sufficiently. Even a phone restart does not solve the problem. Last time the bug disappeared after i received a message during listening to an audiobook, making the chapter automatically pause and restart after the alert-sound.

Over all, I think it is a Huawai problem, not in the app. I also checked some code fragments and did not find anything suspicious. If the problem continues with the next version, I will try to downgrade. On my older android, there is no need for the new data-access feature (I think this was the main reason for voice 6.0). Anyway, one more reason to to get a hardware upgrade for me...

@PaulWoitaschek Danke für den Support :-)
(Thank´s for the support).

**Comment by kanjieater** [comment]
I have a samsung note 8 and also have this issue. I have battery saving disabled for voice.

**Comment by HighElder** [comment]
Can you please tell us your App- and Androidversion?

Is it the exact same issue or do some actions like a manual stopping of the app help to solve the problem temporary?

**Comment by kanjieater** [comment]
I am on 5.0.1, Android 9. It seems to happen when i start the playback. I havent noticed any different behavior if i manually stop it. (Un)fortunately its very inconsistent for me.

**Comment by libing-peng** [comment]
> Huawei is known for crazy battery optimizations: https://dontkillmyapp.com/huawei
> 
> Can you try if using the suggested solution solves your problem?

I have a Huawei machine and have the same problem even with battery optimization turned off for Voice 6.12. In the first 24 hours or so it works fine. After that random stop starts and happens quite often. It's not the same as manual stop. For a manual stop, Voice will rewind 20 seconds (as I have set), but for this, there is no rewind.

**Comment by PaulWoitaschek** [comment]
Please capture a bug report when that happens and send it to me:
https://developer.android.com/studio/debug/bug-report

**Comment by PaulWoitaschek** [comment]
(with 7.0.3, not with earlier versions please)

**Comment by MagTun** [comment]
I have reinstalled 7.0.3 and I can't reproduce this bug anymore. It's strange as yesterday the audio stopped each time I opened another app and this happened at least 10 times! Anyway, if it comes back, I will make a bug report.

**Comment by PaulWoitaschek** [comment]
Great! I it happens again - open a new issue please and attach a bug report 😊
