### ISSUE TITLE
app crash with M4B and xHE-AAC codec

### ISSUE THREAD

**Issue by alexminder** [PaulWoitaschek/Voice#1062]
**Is your feature request related to a problem? Please describe.**
If library folder have .M4B audiobook with xHE-AAC codec the Voice app crashes at update library stage. Android 11.

**Describe the solution you'd like**
No crash. Read all the metadata like tags, chapters.

**Comment by PaulWoitaschek** [comment]
Thanks for your report!
I assume this is no longer happening with the latest versions. If yes please open a new issue with the required template values.
