### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by awaisfarooqroy** [PaulWoitaschek/Voice#1063]
I love this app beyond words but as I recently purchased a Nest Mini, I've realized it doesn't support Chromecasting. I tried the cast screen feature but that way the volume is different on device vs the speaker. I am using Smart Audiobook Player for now but it would be brilliant to have Chromecast support in my favorite app ❤️

**Comment by PaulWoitaschek** [comment]
Duplicate https://github.com/PaulWoitaschek/Voice/issues/76
