### ISSUE TITLE
Cover: maintain the right cover

### ISSUE THREAD

**Issue by andreiaspf** [PaulWoitaschek/Voice#1068]
After adding some books without a cover attached, I added a manual cover. However, each time I add a cover to one of them, all books get the same cover.

![Screenshot_20210629_202246_de ph1b audiobook_edit_291402587831576](https://user-images.githubusercontent.com/41141597/123848422-fef6e280-d917-11eb-8dc0-0126de5636d4.jpg)

**Comment by Zazon3** [comment]
A similar thing is happening for me. After adding a cover to (the files of) the audiobook via Kid3, the previous one not belonging to the audiobook in question is showing in the app.

Love the app. Thanks a lot Paul.

**Comment by PaulWoitaschek** [comment]
That's fixed with the latest versions (currently in beta)
