### ISSUE TITLE
Feature request, support Google assistant spoken commands to start and stop playing

### ISSUE THREAD

**Issue by cpsj** [PaulWoitaschek/Voice#1071]
When driving, I can use Google Assistant to launch this application totally hands free. However once the application is running I would love to have the ability for the application to respond to a "Start Playing" and "Pause Playing" by voice commands.  This is much safer, and in Canada is the only legal way to do this while the vehicle is in motion.

I use this to listen to audio books when bicycling, and when driving using a hands free blue tooth adaptor for the car radio.

I have also thought that the name of the app would be a problem, since there are so many things in Android the have the word voice in the title. A different name that was unique would be helptfull for hands free lauching. Today I managed to launch it by a spoken command while in the past this never seemed to work.  The phrase "OK Google app Voice" does start this app now.

Thanks
Pixel 3A phone.

**Comment by PaulWoitaschek** [comment]
https://github.com/android/uamp/issues/432

It's not related to the title. Even renaming the App to sth really unique like MushroomPlayer wouldn't fix this.

This is a limitation of the Android Assistant. There are only a few players who are in direct contact with Google that are whitelisted within the Assistant.
