### ISSUE TITLE
The project is using an incompatible version (7.0.0-alpha14) of the Android Gradle plugin.

### ISSUE THREAD

**Issue by mopenstein** [PaulWoitaschek/Voice#1074]
Trying to build this project using Android Studio but cannot because:

`The project is using an incompatible version (7.0.0-alpha14) of the Android Gradle plugin.`

The automated upgrade tool also fails.

Any way I can get this to build?

**Comment by newhinton** [comment]
See if this helps you aswell: #1060

**Comment by PaulWoitaschek** [comment]
Yep that branch works with the agp 7. You can build the current version by executing gradlew app:assembleDebug
