### ISSUE TITLE
Crash after rewind or back a chapter on M4A audio book.

### ISSUE THREAD

**Issue by berettavexee** [PaulWoitaschek/Voice#1080]
The application crashes when I try to resume play on book in M4A. The application has been downloaded from the google store and is up to date. the phone is a SM-A600 running on Android 10, provided by samsung.

1. listen to an audio book made of about twenty M4A
2. fall asleep 
3. resume reading the next day
4. go back a few minutes or a chapter
5. hit play, application crashes
6. relaunch the application, hit play on the same e-book, the application crashes

How can I collect more information to investigate this bug? 

Thanks to all the contributors to this project for their efforts.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
