### ISSUE TITLE
Disable volume decrease on notification

### ISSUE THREAD

**Issue by temporarium** [PaulWoitaschek/Voice#1088]
Whenever I get a notification with sound, Voice decreases the volume. However, because I depend on a volume booster app for my system, this app is terminated and I have to reopen it to bring back the volume to a level I like. Only Voice does this; other audio-playback apps don´t modify the system volume.

Please add option to disable this behaviour.

**Comment by PaulWoitaschek** [comment]
In the current version, Voice should pause instead of ducking. It not please open a new issue.
