### ISSUE TITLE
Payback stuttering/skipping

### ISSUE THREAD

**Issue by smokingmerlin** [PaulWoitaschek/Voice#1095]
The play back stutters unless phone screen is on at all times.

**Comment by 62niffer** [comment]
Any news on this? I have this issue too.

**Comment by PaulWoitaschek** [comment]
If this is happening on Version 6.1+ as well, please open a new issue, containing the version.
If possible please attach a [Bug Report](https://developer.android.com/studio/debug/bug-report)
