### ISSUE TITLE
Stops playing when there is a long silence

### ISSUE THREAD

**Issue by BruceFraser1** [PaulWoitaschek/Voice#1096]
... a long silence, such as a new section or chapter (still the same MP3 file).
When I open the app and manually press the "play" button, it just sits there, doing nothing.
I play the same file, at the same location, in an ordinary media player (VLC), and it plays through that place without stopping.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is old and a lot changed in the meantime. If not please open a new issue.
