### ISSUE TITLE
Playing mp3 file made with mp3wrap

### ISSUE THREAD

**Issue by rl1234567890** [PaulWoitaschek/Voice#1137]
Hi, 

Thanks for your app! I noticed that it cannot play mp3 files made of multiple files with [mp3wrap](http://mp3wrap.sourceforge.net/).

**Comment by PaulWoitaschek** [comment]
Can you upload a sample file?

**Comment by PaulWoitaschek** [comment]
Ah I just read on http://mp3wrap.sourceforge.net/

It just stitches together the files. Afterwards it will have broken headers that you need to repair, for example:

`ffmpeg -i wrapped.mp3 -acodec copy wrapped-repaired.mp3`
