### ISSUE TITLE
Separate off button

### ISSUE THREAD

**Issue by Pestkov** [PaulWoitaschek/Voice#1144]
Please make separate turn off button in notification panel . Now it can't be closed :(
Even nothing playing

**Comment by PaulWoitaschek** [comment]
When nothing is playing you can swipe the notification away.

**Comment by Pestkov** [comment]
Unfortunately it is not working for me and broken player (buttons not
respond) stay in tray only until reboot

**Comment by PaulWoitaschek** [comment]
That's probably a bug that's already fixed. Can you check if it's fixed in the beta?

https://github.com/PaulWoitaschek/Voice/wiki

Attention: you will lose your book progress.

**Comment by Pestkov** [comment]
Paul thank you beta works great!
player removes by swype

one more question/suggestion
is it possible to remove large book cover from phone`s wake up background

Best regards,
Timur

**Comment by Pestkov** [comment]
Unfortunately beta also have same problem. Can't be swiped out. It also
started by itself in notification menu

чт, 24 февр. 2022 г., 10:12 Timur Designer ***@***.***>:
