### ISSUE TITLE
Reduce/Analyze Powerconsumption on Playback

### ISSUE THREAD

**Issue by newhinton** [PaulWoitaschek/Voice#1152]
Something i noticed on "every" version of voice, the app requires a rather large amount of power. In comparison:
Vlc ~3% for 1 hour 30 min
Voice ~14% for 2 hours 15 min
Phonograph ~9% for 2 hours

Those numbers are reported by my settings, so they may be flawed in some way, and also they are not what i would call scientifically sound. But if this can be confirmed on other devices aswell, this may be worth investigating.

I will update this ticket with information as i gather it.

This is a profiler capture from a (presumed) updatecall:
![grafik](https://user-images.githubusercontent.com/25279821/155622977-c815714b-0b26-4319-82c9-b191b13f3ec5.png)

It seems the BookContentRepo.put() function does quite a lot of work for just storing a timestamp.
![grafik](https://user-images.githubusercontent.com/25279821/155623183-c541c91b-cebf-42d9-abec-7f02fda20598.png)
![grafik](https://user-images.githubusercontent.com/25279821/155624042-cabbab12-eb7f-420f-aaf0-03906219bece.png)
It runs for 70ms, but for more than 150 times, which amounts to over 5.5 seconds of activity. The removeAll&add calls amount to approximately 11ms together. 

I am now running a test where the delay in MediaPlayer.kt#L131 is set to 10 seconds instead of 200ms. I will report back if that changes the consumption.

**Comment by PaulWoitaschek** [comment]
Please make sure you run your tests using a release build, not a debug build

**Comment by jochym** [comment]
This is also my observation. It can make even speedy phone crawl. This is actually the only drawback of Voice for me.

**Comment by newhinton** [comment]
@jochym Which version did you use? The one from github, the playstore or fdroid?

**Comment by newhinton** [comment]
>I am now running a test where the delay in MediaPlayer.kt#L131 is set to 10 seconds instead of 200ms. I will report back if that changes the consumption.

It seems that this does not have an appreciable effect. 
The current build eats through 6% per hour wich seems excessive. It would be nice if others could confirm those findings so that we can properly investigate this. There is also [Audio Offloading](https://medium.com/google-exoplayer/exoplayer-2-12-whats-new-e43ef8ff72e7) which could help.

**Comment by PaulWoitaschek** [comment]
Yep, audio offload is one of the next things. I'm planning to create an experimental setting for this that people can make use of. I'll create a roadmap.

**Comment by PaulWoitaschek** [comment]
Little update: I experimented with the audio offload and it has several flaws. For instance adjusting the playback speed is no longer possible. Also it's buggy on several Android versions. And it doesn't work with Headsets.

https://github.com/androidx/media/issues/136

I'm closing this for now due to lack of activity and due to lack of ideas how to tackle this.
I'm very open to ideas and PR's though!
