### ISSUE TITLE
[FEATURE_REQUEST] Audiobook folders list shows long path rather than a meaningful folder name

### ISSUE THREAD

**Issue by varunrao1991** [PaulWoitaschek/Voice#1172]
**Is your feature request related to a problem? Please describe.**
The audiobook folders list shows a long path instead of the short file name, I will have no clue which book has been added and which has not.

**Describe the solution you'd like**
Pathname along with a short small folder name can be intuitive.

**Describe alternatives you've considered**
The pathname can be shown in small size only on clicking the folder.

**Comment by PaulWoitaschek** [comment]
Can you post a screenshot and which version you are using?

**Comment by varunrao1991** [comment]
I just installed the latest build and looks like the folder structure is changed. Now we have a simple folder structure. Ignore this issue. I am closing it now.
