### ISSUE TITLE
App network connections

### ISSUE THREAD

**Issue by johnstonesnow** [PaulWoitaschek/Voice#1232]
I read the permissions and this concerns me. Can someone explain why this app needs network connections?

view network connections
Allows the app to view information about network connections such as which networks exist and are connected.
run foreground service
Allows the app to make use of foreground services.
have full network access
Allows the app to create network sockets and use custom network protocols. The browser and other applications provide means to send data to the internet, so this permission is not required to send data to the internet.

**Comment by PaulWoitaschek** [comment]
It’s for the cover scanner (long-click on a book and press Cover (Internet).

Also on Google Play Builds, (not on fdroid builds) the app is transmitting crashes to Firebase Crashlytics

**Comment by sezanzeb** [comment]
I'm using AudioAnchor instead, it works flawlessly without any network access: https://f-droid.org/en/packages/com.prangesoftwaresolutions.audioanchor/, https://github.com/flackbash/AudioAnchor
