### ISSUE TITLE
[feature request] Allow choice between pause and ducking when doing things like turn-by-turn navigation

### ISSUE THREAD

**Issue by Peter4487** [PaulWoitaschek/Voice#1236]
Right now Voice ducks (lowers the volume) when interrupted by e.g. turn-by-turn navigation instructions from Google Maps. This might work okay for music, but for an audiobook it is really frustrating since you miss dialogue. Hearing everything is important with audiobooks, whereas being continuous is important for music.

I suggest a setting that allows the choice between ducking and pausing when playing via bluetooth and interrupted by something else.

**Comment by PaulWoitaschek** [comment]
Which version are you using? It should not duck, it's speech content.

**Comment by Peter4487** [comment]
Apologies for never replying, I am using 8.1.2 at the moment.
I should clarify: this works properly when I am navigating with e.g. Google Maps on the device, but when I am connected to another device (like a car's audio system) via Bluetooth, I experience ducking rather than pauses.
