### ISSUE TITLE
6.x is missing adding bookmarks and volume boost

### ISSUE THREAD

**Issue by voidplayer** [PaulWoitaschek/Voice#1241]
I decided test the new 6.x voice and is missing:

* adding bookmarks by long pressing the bookmark icon
* volume boost

I used both of this. Are they planned to come back?

**Comment by PaulWoitaschek** [comment]
The bookmarks yes, the volume boost unfortunatelly not to simplify the UI options for less used functions. Sorry that you were one of the users.

**Comment by Faerbit** [comment]
Volume boost is a killer feature for me. Androids volume control is way not granular enough to find a comfortable listening volume for me. I don't know why there still isn't any option to improve on this, but this app provides a great work around. While I can continue to just run version 5, I would prefer if you could reimplement it :)

**Comment by voidplayer** [comment]
Im still holding to 5.x because of this too
