### ISSUE TITLE
Playback fails on latest beta

### ISSUE THREAD

**Issue by dubsflyt** [PaulWoitaschek/Voice#1260]
Since the last beta update on 18th June cannot play audiobooks. They are m4b format files encoded aac. 
Pressing play the button animates from the play icon to the pause icon then immediately reverts back. Nothing is played. Same from notification.
Reverting back to stable and it works fine again. Worked on all the 6.x alphas and betas up until the last update

**Comment by PaulWoitaschek** [comment]
Thanks for the report! Can you mail me one if the failing files?

**Comment by codingCoffee** [comment]
I was facing the same problem. I found a trivial solution by renaming the `m4b` extension to `m4a`, since they are both essentially the same audio file extension of the MP4 codec. And it worked out for me, Voice was able to play the audiobook.

**Comment by dubsflyt** [comment]
I can confirm changing the file extension doesn't help with this for me. Am I right in reading the commits that a change to exoplayer happened before the last beta? Could that be cause? I'd love to share the book affected with you but it's copyrighted book I ripped from disk so can't really share. Happy to provide any technical info of it you need though?

**Comment by PaulWoitaschek** [comment]
I reverted the media3 change and will push an update for beta03 right now.

**Comment by dubsflyt** [comment]
Unfortunately same issue persists on 6 beta 03 released today

**Comment by PaulWoitaschek** [comment]
Hmm without a file to reproduce there is not much more I can help with

**Comment by PaulWoitaschek** [comment]
https://github.com/google/ExoPlayer/issues/10381

It's this issue

**Comment by dubsflyt** [comment]
If you need it I can probably convert some generic file with the same format and upload it for testing but I guess if its that issue that wouldn't really help? Let me know if you need it still

**Comment by PaulWoitaschek** [comment]
Thanks but the issue is already known upstream and they already have files reproducing this.
In the meantime this will be fixed in beta04 by ef46ea7b9fe43bdeb18a93b80e33211e362eb726
(I downgraded exoplayer)

**Comment by dubsflyt** [comment]
Just to let you know all works perfectly now on new beta. Thanks for sorting
