### ISSUE TITLE
Updating translation

### ISSUE THREAD

**Issue by homocomputeris** [PaulWoitaschek/Voice#1262]
**Is your feature request related to a problem? Please describe.**
I've found some minor mistakes and missing translations in v6 beta. I'd like to contribute by translating and proofreading at Transifex, and I've sent a request there some time ago.

**Describe the solution you'd like**
I'd like to accepted to the translation team at Transifex as a proofreader

**Comment by PaulWoitaschek** [comment]
Thanks for wanting to contribute! I accepted the invite :)

**Comment by homocomputeris** [comment]
Thanks a lot!
