### ISSUE TITLE
Shake does not rewind by length faded out 

### ISSUE THREAD

**Issue by SantoshGuptaML** [PaulWoitaschek/Voice#1376]
### What happened?

According to this conversation, if a shake occurs to reset the timer, the playback is rewinded by the time faded out. 

This does not occur with me. 

https://github.com/PaulWoitaschek/Voice/discussions/1375#discussioncomment-3174309

### Version

5.0.1

**Comment by PaulWoitaschek** [comment]
Thanks for the report! This is fixed in the latest beta:
https://github.com/PaulWoitaschek/Voice/wiki/FAQ#how-can-i-join-the-beta
