### ISSUE TITLE
M4b files don't play

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/Voice#1429]
### What happened?

M4b files refuse to play. Renaming them to mp4 fixes the playback. 
@newhinton 
I'm on vacation for the next three weeks without a machine with me. Could you take a look if you can fix this?

### Version

6.0.8

**Comment by newhinton** [comment]
I can give it a try!

**Comment by PaulWoitaschek** [comment]
@shirish87 if you could take a look as well? 🙈
It's really effecting a lot of users. 

My main suspicion is, that a downgrade to exoplayer .17 fixes it.

**Comment by PaulWoitaschek** [comment]
It seems to be somehow connected to updating from an older version. 
People have reportet, that reinstalling fixes it.

**Comment by shirish87** [comment]
M4B playback works fine in my early testing. Tried upgrading from an earlier version as well as a fresh install.

Book covers take a while to show up, but no issues with playback. Have ~70 books, all m4b.

Minor note: I had to downgrade AGP to 7.2.2 to work with my build env.

**Comment by PaulWoitaschek** [comment]
Thanks! I tried to contact some issue reporters so they can provide more detailed answers here. 

From my understanding it is rather the case that books don't show up at all instead of not being able to play them.

Another suspicion: maybe it is related to R8 and it doesn't reproduce because your Agp version doesn't have a bug?
Might be worth a shot.

**Comment by PaulWoitaschek** [comment]
Whoever has this issue:
Please try the apks from the github releases page and identify, from which version this issue started appearing.

**Comment by shirish87** [comment]
ah, if the books aren't showing up, I guess ffmpeg metadata extraction or cover extraction could be the reasons. possibly native code. I think we can rule out exoplayer.

Is there any way to know which version they were upgrading from?

**Comment by PaulWoitaschek** [comment]
The reports so far are mixed and I don't really know. 

This issue is somewhat related:
https://github.com/PaulWoitaschek/Voice/issues/1260

@codingcoffee can you reproduce this?

**Comment by codingCoffee** [comment]
Hey @PaulWoitaschek 

Playback of `m4b` files is working for me **without** renaming the file extension to `mp4`. I upgraded to `6.0.8` from an older version of Voice (most likely `6.0.2`, though I can't be sure). And also uninstalled and reinstalled the app. In both the cases, playback and loading book covers for `m4b` files worked just fine. Also repeated the same from `6.0.7` to `6.0.8` and it's working perfectly.

Could it be something device/vendor specific? I'm using a OnePlus 6. Getting some more metrics on the devices it's failing on might give us a hint about the issue.

**Comment by PaulWoitaschek** [comment]
I think it was due to a bug in Androids mime type. I think that last commit of mine fixed it. 
Can someone verify this? Probably on an older emulator it should be reproducible. 
Can you also take a look, what kind of mine type a m4b file returns if it reproduces?

**Comment by codingCoffee** [comment]
**Unrealted**
But I want to know what all you used :P ? I'm sure [termux](https://play.google.com/store/apps/details?id=com.termux&hl=en_IN&gl=US) was involved. Was that it or does there exist any native app to commit code :P ??

On a related note, I checked out the latest release, things are working just fine! Wasn't able to reproduce the issue (fortunately or unfortunately :P)

**Comment by shirish87** [comment]
It may be useful to keep the m4b that failed around. If it is copyrighted media, I suppose sharing it would be an issue. But I wonder if sharing an insignificantly short clip would be considered "fair use"? Any thoughts?

You could use `ffmpeg` like so to create a 10 sec m4b file with just audio streams:
`ffmpeg -i "the-file-that-will-not-play.m4b" -map a -t 00:10 -dn -c copy broken-10s-clip.m4b`

**Comment by PaulWoitaschek** [comment]
> But I want to know what all you used :P

The GitHub web interface 😅

On the issue itself:
It's probably possible to create a test with an empty m4b file and see if that is being picked up by the cover scanner. 
I assume that m4b was added to the mime type map with Android 11 / 12 and therefore wasn't on older Android Versions.

**Comment by shirish87** [comment]
You were right about the mime type issue. `v6.0.8` fails to parse m4bs in an Android 9 emulator, whereas `v6.0.9` works.

Before:

https://user-images.githubusercontent.com/304687/183819005-24cbd7c7-6485-4cf9-8929-aec83d251dd1.mp4

After:

https://user-images.githubusercontent.com/304687/183819034-b1c51afc-bb63-42f2-95be-8264b3f6da28.mp4

**Comment by PaulWoitaschek** [comment]
Thank you for your help everyone ❤️ 🪲
