### ISSUE TITLE
6.0 when adding a folder, no longer get option between 'Single book' or 'Folder with multiple books' as prior versions

### ISSUE THREAD

**Issue by 13048** [PaulWoitaschek/Voice#1445]
### What happened?

6.0 when adding a folder, no longer get option between 'Single book' or 'Folder with multiple books' as prior versions

as a result, no longer able to continue my prior use case and had to revert to older version of the app.

### Version

Version 6.0.7 (3060384)

**Comment by PaulWoitaschek** [comment]
Thank you for your report. Can you describe your use case and elaborate why the simplified structure does not work for you?

**Comment by mutoroglin** [comment]
Hi Paul, just browsed here to your project page to flag this simplified structure as an issue for me as well.

You ask what my use case is and why it doesn't work for me: I use FolderSync Pro to download files (= new audiobooks) from my server on my cell phone. They all are copied in a single folder which I included to Voice as a "folder with multiple audiobooks".
Surely, I understand I could change my approach on uploading audiobooks but frankly I am not very keen to do so as that would require several hours on the cells phones and tablets of me and my family.

May I ask what your intention behind that simplification was, why would you remove features at all?

**Comment by 13048** [comment]
> Thank you for your report. Can you describe your use case and elaborate why the simplified structure does not work for you?

via fdroid, previously i was using Version 5.0.2 and was able to choose between 'single book' or 'folder with multiple books' option when adding a folder.

i was using the 'single book' option to treat multiple mp3s in one folder as played one sequence (e.g. separate audiobook chapters or transferred podcast episodes in order)

when i use v6, no choice prompt occurs either on adding or any setting that i can see. it instead just displays as 'folder with multiple books' and (poorly) arrays and treats each mp3 file separately rather than in sequence.

upon further investigfation of v6, looks like to replicate my old set up that i used in v5 i need to select a root folder e.g. podcast and then just move my files into a sub folder instead .eg. podcast/files

**Comment by strider72** [comment]
More specifically: `voice\booktitle`

**Comment by PaulWoitaschek** [comment]
I made a first draft on how the UI could look like that allows to select both folder modes.

https://drive.google.com/file/d/14xFhQ_ykYfqxM20Jd9eT2umK27CD-PgZ/view?usp=sharing
I'm looking forward to feedback!

**Comment by newhinton** [comment]
This looks nice! 

How exactly does it work, does it differentiate between the two folder "types" automatically?

**Comment by mutoroglin** [comment]
Hi Paul,

I installed your test version and tested:
1) adding a folder with multiple audiobooks as "Root audiobook Folder"; looks good and works fine
2) adding a folder with several files as chapters of a single audio book as "Single audiobook folder"; looks good and works fine
3) adding a single file; looks good and works fine

From my end this is what I was looking for, that could go like this in the next released version.
Thank you for considering the feedback about the missing feature!
