### ISSUE TITLE
Filenames in chapter titles are too long

### ISSUE THREAD

**Issue by gullcomb** [PaulWoitaschek/Voice#1447]
### What happened?

In some books, presumably because the relevant metadata is not available, chapter titles display the files' full paths. However, that is often unusable because the display is truncated before showing any chapter-specific information (e.g. `Device:Audiobooks/Very Long Book Title/…`). It would be much more useful if the path was instead relative to the books' directories, or even just the filename without any directory at all. (I don't use subdirectories inside books so those would be the same to me.)

### Version

6.0.7 (via F-droid)

**Comment by PaulWoitaschek** [comment]
Could you attach / send a file by mail that reproduces this issue?

**Comment by gullcomb** [comment]
I can reproduce with just the two attached files (as a "book" with two "chapters"): [Test.zip](https://github.com/PaulWoitaschek/Voice/files/9333929/Test.zip) (courtesy of https://github.com/angband/angband)

If it helps, the audiobooks' folder is on a SD card formatted as removable storage (even though it isn't actually removable) and the phone is running Android 11 (via LineageOS 18.1).

I also did a bit of code diving and the only relevant thing I could find was [this change](https://github.com/PaulWoitaschek/Voice/commit/f00a297c31f94d18887c51130b3a2d38f89122ec#diff-a03355471c266c69da52b962ab5bf55d1c0b7e4c96ca2676cb0f7d400cd6bc19L91-L92). With the files I just uploaded I could see the full chapter title without truncation and the file extension is correctly removed.

In light of the above, my current theory is that `file.lastPathSegment` somehow does not work as intended if the file is on removable storage.

**Comment by thezeroalpha** [comment]
Same issue here, not related directly to removable storage. Even on a device with no SD card, I get the full path, prefixed with `primary:`.

The chapter name comes from [`chapterNameFallback`](https://github.com/PaulWoitaschek/Voice/blob/7bfb6dec2cc2b7046afb81da129844b67643cd7e/scanner/src/main/kotlin/voice/app/scanner/MediaAnalyzer.kt#L83-L89). In version 5.0.2, [this function had a File parameter](https://github.com/PaulWoitaschek/Voice/blob/9cf1dc1ab0d14bfbe13031bd5167eff03d179650/app/src/main/java/de/ph1b/audiobook/misc/MediaAnalyzer.kt#L93), but now it has a Uri parameter. `Uri.lastPathSegment` actually returns the full path to the file. To get the equivalent of `file.name`, more string manipulation is necessary as far as I can tell.

I propose changing, in [scanner/src/main/kotlin/voice/app/scanner/MediaAnalyzer.kt](https://github.com/PaulWoitaschek/Voice/blob/7bfb6dec2cc2b7046afb81da129844b67643cd7e/scanner/src/main/kotlin/voice/app/scanner/MediaAnalyzer.kt), the function [chapterNameFallback](https://github.com/PaulWoitaschek/Voice/blob/7bfb6dec2cc2b7046afb81da129844b67643cd7e/scanner/src/main/kotlin/voice/app/scanner/MediaAnalyzer.kt#L83-L89), from this:

```kotlin
private fun chapterNameFallback(file: Uri): String {
  val name = file.lastPathSegment ?: "Chapter"
  return name.substringBeforeLast(".")
    .trim()
    .takeUnless { it.isEmpty() }
    ?: name
}
```

To this (or something similar, I'm not very experienced writing Kotlin):

```kotlin
private fun chapterNameFallback(file: Uri): String {
  val path = file.lastPathSegment ?: "Chapter"
  val name = path.substringAfterLast('/')
  return name.substringBeforeLast(".")
    .trim()
    .takeUnless { it.isEmpty() }
    ?: name
}
```

If `path` evaluates to `"Chapter"`, the `substringAfterLast` call returns `"Chapter"`, so imo nothing breaks there.

@PaulWoitaschek what do you think? Testing it on my phone, the chapter names show up as they did in version 5.0.2 (much shorter and more readable). The [scanner tests](https://github.com/PaulWoitaschek/Voice/blob/490b3ebff0df3ad31de7076195b649f6ba1031ef/scanner/src/test/kotlin/voice/app/scanner/MediaScannerTest.kt) also pass.

**Comment by PaulWoitaschek** [comment]
Thanks for investigating. I think the correct solution in this case is to to pass a `DocumentFile` instead of an Uri and use the name of the document as the fallback.
Open for a PR (including some tests around this). Just let me know if you are working on this, else I'll tackle this this weekend.

**Comment by thezeroalpha** [comment]
I created #1464 to address this.
