### ISSUE TITLE
A cover image in a folder is displayed as an additional chapter/track.

### ISSUE THREAD

**Issue by Murdertoni** [PaulWoitaschek/Voice#1457]
### What happened?

I save a Cover.jpg in my folders with the audio tracks.
In addition, in the mp3 fliles the covers are of course also included in the mp3Tags.
Now the cover is displayed as another track in the title selection of the player.
When playing it then also ends with the display of this "cover track".
The name of the title is then: primary:Music/Hoerspiele/Titeldeshoerspiel/Cover
My strkuture is Music/Hoergames/Titeldeshoerspiels/Tracks.mp3 + Cover.jpg

Can the cover.jpg be turned off as a single audio track?
Of course, the mp3 embedded cover or the cover.jpg should remain possible for displaying the cover as album art.

Thank you and...
Voice is for me the best and slimmest player I know! :-)

### Version

6.0.9
![Screenshot_20220820](https://user-images.githubusercontent.com/111637155/185779735-e3ceb117-e609-4186-876e-c09a94955ba4.jpg)

**Comment by xamanu** [comment]
I love the Voice player. Thanks for creating and maintaining it!

In version 6.0.9 and using cover images in the same directory as the audiobook file I get them listed as separate audiobooks. It would be nice to have the new version of Voice also handling this as the cover of the audiobook instead.

![Screenshot_20220821-135219](https://user-images.githubusercontent.com/97706/185789712-fc3554cd-a2a6-48ba-823c-b219d00010b7.png)
