### ISSUE TITLE
Problems wit adding books - Version 6.0.7

### ISSUE THREAD

**Issue by StuntmanWerner** [PaulWoitaschek/Voice#1459]
### What happened?

Hi there,
First thing: i am a big fan of your work. Voice is my favorite audiobook-player. 

Sadly i am not able to use it anymore.
Lastly i was adding a new audiobook. I selected the folder with the audiofiles in it, but Voice added each chapter as a new book.
I have another Audiobook as a single file which i am not able to select to add it to my libary. 
I hope you can fix the problem.

### Version

6.0.7

**Comment by PaulWoitaschek** [comment]
Is this issue the same as https://github.com/PaulWoitaschek/Voice/issues/1445 ?

**Comment by StuntmanWerner** [comment]
Thank you for your fast response.
Yes and no. I also do not have the option to choose between  'Single book' or 'Folder with multiple books'. 
But i also have the Problem that if one book is in a folder, every chapter (file) would be treated as a whole new book.

**Comment by PaulWoitaschek** [comment]
But if you had the option "Single Book", then every file within it would be treated as part of that book?

**Comment by StuntmanWerner** [comment]
Good question. I got the book after the update on the never version.

**Comment by PaulWoitaschek** [comment]
I'll close this as a duplicate for now. I have an idea to fix your use case, stay tuned. 
For now I can recommend the structure.

audiobooks/book2
audiobooks/book3

And only select the single root audiobook folder.
