### ISSUE TITLE
Bookmarks lost

### ISSUE THREAD

**Issue by xcy7e** [PaulWoitaschek/Voice#1470]
### What happened?

Sometimes, overnight - bookmarks appear to be missing. For now I can only assure that this happens for manually added bookmarks.
I suspict it happened when the timer feature tried to add a bookmark when I fell asleep and therefor overwrote the recently manually created bookmarks.

I have disabled any energy saving features for the app. 

Using a Galaxy A51 with android 12.

Sorry that I do not have more facts, I'll keep that in mind and will add more details here whenever possible.

### Version

5.0.1

**Comment by PaulWoitaschek** [comment]
5.0.1 is a very old version. If it's still happening in 6.x, comment and I'll re-open.
