### ISSUE TITLE
Requesting file rights missing?

### ISSUE THREAD

**Issue by tomdmr** [PaulWoitaschek/Voice#1472]
### What happened?

After upgrade to version 6 I cannot see folders or files. On start I get to the screen "audiobook folder", which is blank except for the Add-button.  In the app manager I can see that the app does not request access to file system. Maybe this is a packaging bug from f-droid?

### Version

6.0.9 from f-droid

**Comment by PaulWoitaschek** [comment]
Did you try clicking on the add button and adding something?

**Comment by tomdmr** [comment]
Yes. The button briefly changes colour to slightly brighter, so it seems to be enabled, but otherwise no reaction.
OS is LineageOS, Android 10, API level llama. I am travelling currently, but on the weekend I can try to look into a logcat.
What I find strange us that the OS does not ask me if I want to grant file/media access to the app.
Ciao
Tom

Am 30. August 2022 22:40:26 MESZ schrieb Paul Woitaschek ***@***.***>:
>Did you try clicking on the add button and adding something?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1472#issuecomment-1232144502
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Gesendet von /e/ Mail.

**Comment by PaulWoitaschek** [comment]
Voice no longer needs file permissions and instead requests access using the Storage Access Framework. That should really be present on all Android versions and connected to your custom rom not behaving properly.

Can you try if installing a file manager fixes this?

https://f-droid.org/en/packages/me.zhanghai.android.files/

**Comment by PaulWoitaschek** [comment]
No, apparently that one doesn't implement `android.intent.action.OPEN_DOCUMENT_TREE`.

Maybe you disabled the "Files" App on your phone?

**Comment by tomdmr** [comment]
The file app is a clue... I replaced it by the Simple File Manager from f-droid. Not sure if this implements the action. Do you know another app that requires OPEN_DOCUMENT_TREE so I could test if it also fails?

Am 31. August 2022 08:07:23 MESZ schrieb Paul Woitaschek ***@***.***>:
>No, apparently that one doesn't implement `android.intent.action.OPEN_DOCUMENT_TREE`.
>
>Maybe you disabled the "Files" App on your phone?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1472#issuecomment-1232502412
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Gesendet von /e/ Mail.

**Comment by PaulWoitaschek** [comment]
Not that I know of. Can you try it with the default files app? Voice shouldn't be the only app that's broken.
What's really strange though is that the app doesn't crash. I just reproduced it by installing an emulator, rooting it and disabling the files app. That makes Voice crash.

**Comment by tomdmr** [comment]
I disabled it and apparently removed it. Could be I saved it to my home PC, otherwise I need to search or build it myself. Could take a while.

Am 31. August 2022 08:21:28 MESZ schrieb Paul Woitaschek ***@***.***>:
>Not that I know of. Can you try it with the default files app? Voice shouldn't be the only app that's broken.
>What's really strange though is that the app doesn't crash. I just reproduced it by installing an emulator, rooting it and disabling the files app. That makes Voice crash.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1472#issuecomment-1232511569
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Gesendet von /e/ Mail.

**Comment by PaulWoitaschek** [comment]
https://github.com/1hakr/AnExplorer/blob/master/app/src/main/AndroidManifest.xml#L91

This app is declaring the intent filter, maybe that works.

**Comment by tomdmr** [comment]
In the mean time I checked voice on another lineageOS phone with the default file manager, works fine. I guess you can close this bug, I'd rather check if the missing intent handler can be added to Tibor's simple file manager
Ciao
Tom

Am 31. August 2022 08:39:40 MESZ schrieb Paul Woitaschek ***@***.***>:
>https://github.com/1hakr/AnExplorer/blob/master/app/src/main/AndroidManifest.xml#L91
>
>This app is declaring the intent filter, maybe that works.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/1472#issuecomment-1232524846
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Gesendet von /e/ Mail.
