### ISSUE TITLE
Voice app crashes System ui on Android 13 - GrapheneOS

### ISSUE THREAD

**Issue by methreebee** [PaulWoitaschek/Voice#1486]
### What happened?

Whenever I use the Voice app the system ui of my device will completely lock up, giving me a notication to either "force quit" system ui or "wait". The app doesn't crash, only the system ui does. It also doesn't do it immediately when starting an audiobook. After a length of time I notice that my phone is no longer responding to double taps or swipes and then the system ui crash notication would pop up.

Currently running version 6.1.0(the old 5.0 version also crashed system ui) of the froid varriant on GrapheneOS which is on android 13. Didn't have the system ui crashes when on Android 12. 

Not sure if related to running it on grapheneos or Android 13. 

### Version

6.1.0

**Comment by PaulWoitaschek** [comment]
As this is not something that is happening on stock Android. If a developer with Graphen OS finds the cause of this crash and can fix it I'd ofc accept a PR but right now there is not much that can be done here.

**Comment by flesser** [comment]
I experienced the same problem (GrapheneOS SystemUI crashing after a short while when using Voice) but lived with it.

However, since updating to 7.0.0 (via F-Droid) the problem seems to be gone :-)
There hasn't been a GrapheneOS update since, so I guess some of the 7.0 changes did the trick.

**Comment by PaulWoitaschek** [comment]
Cool! You should update to 7.0.3 though, that's more stable :)

**Comment by polyzen** [comment]
7.0.0 seems to still be the latest on F-Droid. It can take a while for updates to make it to their repos.

**Comment by arjan-s** [comment]
Too bad this issue is closed, as it's still a problem. Voice fully crashes my phone, making it reboot. Both GrapheneOS (2024121200) and Voice (8.2.3) are fully up to date
