### ISSUE TITLE
Deleted all my audiobooks

### ISSUE THREAD

**Issue by metbic** [PaulWoitaschek/Voice#1500]
### What happened?

So I got curious for 6.x and thought let's try it out. Current version was 5.0.2. Installed 6.0.1 via f-droid, added in both suggested ways my audiobook folder, which has both folders with audiobooks (multi-file and single-file) as well as single-file audiobooks. One of the added audiobooks showed up as a duplicate, one of them even with a wrong cover. It's an audiobook I wanted to delete anyway, so I used the delete function in Voice. Then I found out Voice had deleted the complete audiobook folder. No biggie, since I have them on my computer as well. Downgraded to 5.0.2.

### Version

6.1.0

**Comment by PaulWoitaschek** [comment]
This is very bad. I assume you added your root audiobook folder as one single audiobook and then deleted that.

**Comment by PaulWoitaschek** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/743462/191364261-a8c9b34b-bcc2-423c-85b0-39e3d3574fcb.png">

To add another safeguard I am now showing, which file will be deleted.
