### ISSUE TITLE
[Bug]  The cover is applied to the wrong object (folder/file)

### ISSUE THREAD

**Issue by serrq** [PaulWoitaschek/Voice#1519]
### What happened?

There is a big problem with adding a cover to the folder or file when it is not the only one in the directory.

To summarize when there is only one object (folder/file) in the directory Voice correctly adds the cover, however if it finds more than one object it randomly puts the cover despite me specifying which object it was intended for (it applies it to the wrong object).

### Version

6.1.2

**Comment by PaulWoitaschek** [comment]
I do not consider this as a bug. What else would you expect Voice to do in this case?

**Comment by PaulWoitaschek** [comment]
Can you screenshot your folder structure, and what you added in which way?

**Comment by PaulWoitaschek** [comment]
So the images are embedded into the audio files? 
Could you send me a zipped folder that contains the files how they were causing wrong covers to show up?

**Comment by PaulWoitaschek** [comment]
That problem should be fixed in version 7.x
