### ISSUE TITLE
Shake to reset sleep timer is gone 

### ISSUE THREAD

**Issue by whisperswild** [PaulWoitaschek/Voice#1533]
### What happened?

Feature missing from the new version. Also had to re-add my entire library, which took a long time to load with only the 50 books I have on my SD card right now

### Version

6.1.2

**Comment by PaulWoitaschek** [comment]
Hey,
It is not gone. It just enabled by default now.

**Comment by whisperswild** [comment]
> Hey, It is not gone. It just enabled by default now.

Thank you, but it is not functioning on galaxy note 8 with Android 9

**Comment by PaulWoitaschek** [comment]
Can you describe what you did and what you expected voice to do?

**Comment by whisperswild** [comment]
While playing an audiobook, I press the sleep timer and enter a time,  15:00 minutes. The timer begins to count down and when I shake the phone it never resets to 15:00 minutes.

I see now that it does work once the timer runs out and the book stops, which is slightly different functionality than it had before.
