### ISSUE TITLE
No thumbnail recognized

### ISSUE THREAD

**Issue by Adolfmope** [PaulWoitaschek/Voice#1535]
### What happened?

Hi, first off, thank you for the effort to create and update this app, is certainly the best for reading audiobooks, ( if you charge some fee for a paid version, i would support, because it helped me a lot ) more because it can recognize file structure and type of files better than none, it also has good features, last update, the program does not recognize the image that comes from the folder or sometimes embed into the audiofile, i would report this as an issue, since its cleatly easier to find audios from a large selection by image, i will attempt go to previous version for now. 

### Version

6.1.2

**Comment by Adolfmope** [comment]
It took a while to update thumbs database but seems ok now.

**Comment by versavius** [comment]
Same here, once the update for Voice 6.1.2 was installed it took me a few mins to sort everything out. I have about 25 audiobooks in my current folder on android.

Otherwise all working for me.

**Comment by PaulWoitaschek** [comment]
That's actually expected behavior. The cover scanning happens after the media scanning.
And the Android Storage Access Framework is slow - this is what is slowing down the media scan. There is nothing we can do to speed it up, unfortunately.
