### ISSUE TITLE
Voice shouldn’t autostart after reboot

### ISSUE THREAD

**Issue by arghfrank** [PaulWoitaschek/Voice#1536]
### What happened?

After each device reboot, the "player" is active in the notification/QQS shade, with the last played audiobook (paused, but still ..). Not sure why (or where to turn off this behaviour). I can "swipe away" the player just fine, I just think I .. shouldn’t need to? :-)

Expected behaviour (because I think that’s what a but report should include apparently): no visible player notification after reboot.

"Resume playback" is set to off (and that’s the only setting I can see that would influence something like that!?).

Stock Android 13 (latest (September 2022) update) on a Google Pixel 6a, Voice 6.1.2 from Play Store.

### Version

6.1.2

**Comment by PaulWoitaschek** [comment]
That's actually an Android 11 feature:
https://developer.android.com/about/versions/11/features#media-controls

**Comment by arghfrank** [comment]
even when i didn’t use voice before at all? as far as i understand it "recreates" a previous state, but no matter what (even after a forced stop), the next time i’ve rebooted the device the player is back again. doesn’t happen with any other media/audio player on my device, that’s why i was/am wondering ... :-/
