### ISSUE TITLE
Most audio files not showing when folder added

### ISSUE THREAD

**Issue by agentreno** [PaulWoitaschek/Voice#1540]
### What happened?

In a recent update, I needed to add a local folder again on my phone. But this only populates a single Not Started Yet entry when there are other MP3 files in that folder.

### Version

6.1.2

### Android Version

Android 13

### Device Model

Pixel 5

**Comment by PaulWoitaschek** [comment]
Can you screenshot, which steps you took to add the book?

**Comment by agentreno** [comment]
![Screenshot_20221005-230124.png](https://user-images.githubusercontent.com/3884999/194172447-69ff4b74-49ea-4bab-acf2-5cae1b3dd725.png)
![Screenshot_20221005-230137.png](https://user-images.githubusercontent.com/3884999/194172473-0411f061-ad2c-481c-a17d-688c79772463.png)
![Screenshot_20221005-230152.png](https://user-images.githubusercontent.com/3884999/194172538-9db9d321-8c87-4c7d-abdf-16112fd34314.png)
![Screenshot_20221005-230215.png](https://user-images.githubusercontent.com/3884999/194172555-ec8cb3af-8963-4a0b-81c7-19e20f3665c7.png)
![Screenshot_20221005-230244.png](https://user-images.githubusercontent.com/3884999/194172570-9dd22015-f3b3-4857-bbdf-1b4125e9f6d2.png)
![Screenshot_20221005-230252.png](https://user-images.githubusercontent.com/3884999/194172590-05070934-ba2c-42ad-b6c8-4f519f7c72a9.png)
![Screenshot_20221005-230301.png](https://user-images.githubusercontent.com/3884999/194172600-87112ae7-091f-4658-b353-7ba7d4d359b8.png)

**Comment by PaulWoitaschek** [comment]
Thanks! Can you now click on the book and show what you see then?

**Comment by agentreno** [comment]
![Screenshot_20221006-095438.png](https://user-images.githubusercontent.com/3884999/194268058-fc04f401-71dc-4994-9357-b467e2731728.png)

Oh okay! Sorry to bother you then, I found this UI a bit unintuitive if you're coming from the old UI particularly. But I've found my content now, thanks!

**Comment by PaulWoitaschek** [comment]
Do you have an idea what exactly confused you and how we could improve that?
