### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by EXOrdle** [PaulWoitaschek/Voice#1546]
### Overview

The app keeps crashing whenever I want to listen to an audio book. I just want to be able to listen to an audiobook for more than 5 minutes at a time.

### How to reproduce

1. Open app
2. Click on play
3. After about 5 minutes, Voice crashes

### Version

6.1.2

### Android Version

10

### Device Model

Huawei P20 Pro

**Comment by PaulWoitaschek** [comment]
As there is a major rewrite as of version 7, I'm closing this as fixed.
