### ISSUE TITLE
Voice stays open, even after closing it.

### ISSUE THREAD

**Issue by FlorianZahn** [PaulWoitaschek/Voice#1558]
### Overview

This happens everytime, but becomes visible, when using dynamic spot app from the play store. While the app controls disappear from the notification window it still stays somewhat open.

### How to reproduce

1. Play something
2. Minimize app
3. Pull down system tray and stop playback from there (where you turn off wlan aswell)
4. Go into the menu where you can see all opened apps. 
5. close Voice
notice that voice is still open

To close the App properly you need to:
1. Open the app
2. start playback
3. stop playback
(3.5 minimize the app)
4. open the app overview and close the app

### Version

6.1.2

### Android Version

android 13

### Device Model

Pixel 6

**Comment by PaulWoitaschek** [comment]
What do you mean by "Open"? In Android there is always only one App open. 
Can you post a screenshot of what makes you think that Voice stays open?

**Comment by Taylor-eOS** [comment]
I think he means the same as issue 1255, which should be solved in newer versions.

**Comment by FlorianZahn** [comment]
> I think he means the same as issue 1255, which should be solved in newer versions.

This might me related.

**Comment by FlorianZahn** [comment]
> What do you mean by "Open"? In Android there is always only one App open. Can you post a screenshot of what makes you think that Voice stays open?

Here is a Video: https://youtu.be/NwPWT0nUB7w

I first try to close the app, where the little dot at the top stays. After that i try to close it the way, where it should disappear, but it doesnt. After that i try the same again. This time the dot disappears. At last i try to force stop the app and the dot disappears.

The dot comes from [dynamic spot](https://play.google.com/store/apps/details?id=com.jamworks.dynamicspot&hl=de&gl=US) and it should only display the app while it is open (even in the background) but Voice seems to only close when following the steps i do in the video.

**Comment by PaulWoitaschek** [comment]
Ah yes, that's expected. You are only removing the app ui from the recents. 
If you want to stop the players service, swipe away the notification after pausing.

**Comment by FlorianZahn** [comment]
> swipe away the notification after pausing
This does not work consistently, sadly.

**Comment by PaulWoitaschek** [comment]
But what ist the problem here?

**Comment by FlorianZahn** [comment]
The app seems to stay open even if you close it after stopping playback and removing the notification. Often times only force stopping it closes the app. 

In the end it is kind of incompatible with the dynamic spot app i linked above, but i do not know enough about how android apps work to guess why "dynamic spot app" recognizes Voice as open.
