### ISSUE TITLE
Make the reverse / forward buttons bigger and easier to hit (add more space between them and the play/pause button).

### ISSUE THREAD

**Issue by JohnTheodore** [PaulWoitaschek/Voice#1567]
### Overview

Firstly, thanks for this app, it's great and I appreciate all the work you've done. The app does everything I want, and I generally don't have many complaints. For this app to work as seamlessly as it does for me, a lot of work had to be done! My "bug" is more of a UI/UX issue, which is easy to resolve, and also easy to summarily reject if your preferences don't agree (which I'm ok with). 5% of the time I _miss_ the previous/forward button, and hit the dead space around it. It could be PEBKAC and the problem is all me/I'm ngmi. My ask is for the previous/forward buttons to be bigger (I don't know exactly how much bigger), and for their distance to the middle button to be increased.

### How to reproduce

see above

### Version

*

### Android Version

13

### Device Model

Pixel 5a

**Comment by PaulWoitaschek** [comment]
Thanks for the report.

I assume that you used an older version of Voice where the buttons were smaller. If not please let me know which version you use and I'll reopen.

**Comment by JohnTheodore** [comment]
I had the latest version at the time when this report was made, but I just installed today's release and see the buttons are much bigger now. I love it, and it's a lot easier to flip back and forth without missing now. Thanks for writing this app, it is really great, I appreciate all your effort! You make listening to all my audiobooks easy!

**Comment by PaulWoitaschek** [comment]
Nice!

That version field is there for a reason though. Often times, you having the latest update the play store gives you is not the latest version due to staged rollouts.

**Comment by JohnTheodore** [comment]
I just always download the apk directly from the releases page on github. the playstore just gets in the way.
