### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by vajonmikl1969** [PaulWoitaschek/Voice#1572]
### Overview

I can no longer add or remove audio books. Version 6.1.2

### How to reproduce

No longer have add option. 
No longer recognizes new books in folder.
When I choose delete book nothing happens.

### Version

6.1.2

### Android Version

Android 10

### Device Model

SM-G960U

**Comment by PaulWoitaschek** [comment]
If this is happening with the latest Voice version, please comment attach a bug report, right after it happened:
https://developer.android.com/studio/debug/bug-report
