### ISSUE TITLE
option "shake to continue" disappeared 

### ISSUE THREAD

**Issue by rafaeln** [PaulWoitaschek/Voice#1594]
### Overview

Older versions displayed a "shake to continue" toggle when starting the sleep timer. The toggle isn't there anymore, even though the behaviour still works. Is that a feature or bug? In case it's a feature, the new user would benefit from a notice telling them they can shake their device to continue playing 

### How to reproduce

1. Open the app
2. Play a book
3. Enable sleep timer

### Version

6.4.1

### Android Version

30

### Device Model

Redmi Note 9S

**Comment by Nex-Carter** [comment]
To me, the whole feature is gone and dearly missed. I don't know where that went :/

**Comment by nbuechner** [comment]
It was one of the best features this application had :(

**Comment by gwarser** [comment]
It's still here, enabled by default.

**Comment by nbuechner** [comment]
Does not work on my device. Also why is there no toggle to disable it then?

**Comment by PaulWoitaschek** [comment]
Yes, it is :) Thanks for commenting.
