### ISSUE TITLE
Rotate screen

### ISSUE THREAD

**Issue by xmha97** [PaulWoitaschek/Voice#1596]
### Overview

https://user-images.githubusercontent.com/23485114/200431592-45162aa6-33a3-4de5-a0f9-7b7c25c85d22.mp4

### How to reproduce

1. Open the App
2. Rotate screen (change screen orientation to landscape)
3. Rotate screen (change screen orientation to portrait)
4. Screen content will not disappear!

### Version

6.4.1

### Android Version

31

### Device Model

21081111RG

**Comment by PaulWoitaschek** [comment]
I assume that this is fixed with Voice 7.x. If not, please comment and I'll reopen.
