### ISSUE TITLE
Stopped playback after a month

### ISSUE THREAD

**Issue by Limuxic** [PaulWoitaschek/Voice#1618]
### Overview

Hello
I'm using Voice on Huawei P40 Lite.
It worked very well for a month.
Today, the player will simply not play - Pressing the 'play' button does nothing.
I tried with different audiobooks, I also reinstalled it (from APKPure) but the same problem persists.
I have not changed anything substantial between now and a few days ago when the app last worked, as far as I can remember 

### How to reproduce

Open the app
Select a book
Click play
Nothing happens, the Play button goes back to the 'play' (triangle) sign

### Version

6.1.2

### Android Version

12

### Device Model

Huawei P40 Lite

**Comment by theAkito** [comment]
Can you play the same files in a different app, like e.g. VLC?

**Comment by Limuxic** [comment]
Hi, I was able to play the same files on a few different devices. 
But please forgive me, I meant to write this a few weeks ago: after the last update, when I clicked the play button, a small notification appeared about allowing it to play in the background; so, I enabled this and the app works well now:-) 
Thank you. What an amazing app it is!
