### ISSUE TITLE
Voice opens when I launch another app

### ISSUE THREAD

**Issue by Taylor-eOS** [PaulWoitaschek/Voice#1619]
### Overview

If I start playing something with my podcast app AntennaPod, Voice opens too. The notification is not persistent, I can swipe it away. But is shouldn't open at all. It somehow registers that "something to be played" is being launched, and opens even though that is another app. I don't know if that if a flaw in Voice or AntennaPod, but I assume it's Voice.

### How to reproduce

Have Voice paused with a started book and closed down. Launch a podcast with AntennaPod.

### Version

6.3

### Android Version

10

### Device Model

SM-A310F

**Comment by Taylor-eOS** [comment]
It happens whe  I open my music app too. Basically Voice opens whenever any audio-related app is opened.

**Comment by econads** [comment]
Possibly related to my issue where the playing notification is shown on starting the phone, and needs to open/close the app before it will disappear.

Android 12 / Fairphone 3 / LineageOS 19-20230306-NIGHTLY-FP3

**Comment by PaulWoitaschek** [comment]
I think this is fixed with Voice 7.x. If not, please comment and I'll reopen.
