### ISSUE TITLE
Adding a folder twice makes it appear twice in the folder list. then tapping the trash icon on one of the duplicates then results in removing both entries, and in loss of all of its audiobooks.

### ISSUE THREAD

**Issue by metbic** [PaulWoitaschek/Voice#1621]
### Overview

Adding a folder twice makes it appear twice in the folder list. then tapping the trash icon on one of the duplicates then results in removing both entries, and in loss of all of its audiobooks.

Add root folder. Add the same folder again (accidentally). Open folder list. See duplicate entry. Trash one of them. Restart voice. All audiobooks gone. Folder list does no longer contain any of the duplicates, although only one of them was trashed. 

### How to reproduce

Add root folder. Add the same folder again (accidentally). Open folder list. See duplicate entry. Trash one of them. Restart voice. All audiobooks gone. Folder list does no longer contain any of the duplicates, although only one of them was trashed. 

### Version

6.x

### Android Version

9

### Device Model

Xz1

**Comment by PaulWoitaschek** [comment]
That's fixed in 7.x, thanks for reporting.
