### ISSUE TITLE
Discontinued 

### ISSUE THREAD

**Issue by hansreil** [PaulWoitaschek/Voice#1623]
### Overview

I listen to a speach by ear phones. I switch the phones off and continue on the phone. But the speach continues on a quite different place. The former version was better.

### How to reproduce

Doesn't happen always

### Version

6.1.2

### Android Version

Android 10

### Device Model

Moto 7 play

**Comment by theAkito** [comment]
Can you point to which exact timestamp you switched it off on and which exact timestamp it continued to play?

Could you also provide screenshots of before it happens & after?

Additionally, it would be helpful if you could provide the audio file, with which this issue appears.

**Comment by PaulWoitaschek** [comment]
I think with the latest version it should happen pretty immediately.
If I understand the original message was that there was that the phone was playing the audiobook for a very short time after disconnecting the headset before it properly paused.
