### ISSUE TITLE
Nested audiobooks files show as a single audiobook

### ISSUE THREAD

**Issue by SirGregster** [PaulWoitaschek/Voice#1630]
### Overview

I have a situation I’d like to bring to your attention.  If I have multiple titles for a single author, the book shows up as a single book with the title of the first book (alpha-sorted).

Here’s an example, showing the file structure on my phone:
Author, Book (folder)
	BookOne (folder)
		BookOne files (epub, pdf, etc)
		BookOne (audiobook folder)
			BookOne audiobook files (mp3, generally)
	BookTwo (folder)
		BookTwo files (epub, pdf, etc)
		BookTwo (audiobook folder)
			BookTwo audiobook files (mp3, generally)

What I get in the app is:
Author, Book
BookOne (all files (chapters) for both books are here)

I wish that each book showed as a separate title under the author, but maybe the app isn’t designed to work that way.

### How to reproduce

Open the app.
I expect an audiobook tile for each audio book, but separate audiobooks for the same author show as a single audiobook.

### Version

5.0.1

### Android Version

12

### Device Model

Galaxy S20 FE 5G

**Comment by theAkito** [comment]
Could you create & post screenshots of the directory structure, how everything looks inside the app & with pointers and explanations on the screenshots displaying how it all _should_ look?

**Comment by Yavos** [comment]
I had the same problem when I had a subfolder for an author in my audiobook-root directory looking kinda like this:
```
audiobooks
├── book1
├── author
│   ├── book2
│   ├── book3
│   ├── book4
│   └── book5
└── book6
```
This will show up book1 and book6 correctly, but book 2-5 are combined under the title of book2.

I fixed this in my case by just moving the books to first level, but in the aforementioned case this solution is not the best.

**Comment by talal** [comment]
I can confirm that multiple audiobooks under a subfolder show up as a single audiobook.

My audiobooks folder structure is similar to @Yavos :

```
Audiobooks
├── author1
│   ├── book1
│   ├── book2
├── author2
│   ├── book1
├── author3
│   ├── book1
│   ├── book2
│   ├── book3
...
```

cc @PaulWoitaschek

**Comment by xcy7e** [comment]
Guys that's not a bug here. Sorry but so many people post their "issues" here that are just design cases.

Either make a clear feature request or leave it. Additionally many posting versions TWO major versions behind, so what's the point?

So many tickets here are feature requests shipped as bug reports.
I am not surprised the developer does not respond here but by spamming open tickets this rather hinders development than supports it.

**Comment by PaulWoitaschek** [comment]
Yep, that's currently a limitation. For now you'd need to add `author1`, `author2` etc as a root audiboook folder.
