### ISSUE TITLE
Cover picture 

### ISSUE THREAD

**Issue by DrewsR** [PaulWoitaschek/Voice#1643]
### Overview

i have a directory with many audio book mp3 files of a series, e.g. "die drei Fragezeichen". every mp3 file has its own cover picture. But the app displays always only the cover picture of the first file. i would expect, that always the cover is loaded when a new file is being played.

### How to reproduce

open the app
see the covers pictures

### Version

6.1.2

### Android Version

12

### Device Model

Samsung Galaxy tab a7

**Comment by theAkito** [comment]
> every mp3 file has its own cover picture.

So, if there are 31 MP3 files, there are 31 *.png files?

Could you please post an example of how the files look like? For example, a screenshot of the folder content, showing the files.
It's important, how the files are named.

**Comment by theAkito** [comment]
@DrewsR

I think, you need to add the screenshot via Github.

**Comment by DrewsR** [comment]
Screenshot1
![Screenshot1](https://user-images.githubusercontent.com/120211909/206868676-63320364-49ee-4e8b-b957-3c48ccaab9c4.jpg)

Screenshot2
![Screenshot2](https://user-images.githubusercontent.com/120211909/206868720-58a8e8d0-5579-46ac-a195-4100e17fa12e.jpg)

 Screenshot3
![Screenshot3](https://user-images.githubusercontent.com/120211909/206868754-07a7bb9c-c12b-4555-a014-3af8ea6933c1.jpg)

Screenshot4
![Screenshot4](https://user-images.githubusercontent.com/120211909/206868790-f58b5c6f-f318-4447-90fb-300eb341ab4b.png)

Screenshot5
![Screenshot5](https://user-images.githubusercontent.com/120211909/206868818-c58c9d6c-4833-4893-b9fd-ada042e27c42.png)

**Comment by DrewsR** [comment]
@theAkito Screenshot added

**Comment by allmynamesweretakenomoreideas** [comment]
@DrewsR You used the same Album Tag for the entire "Drei Fragezeichen Kids" Collection. An Album is intended to have only one cover, so usually a player takes the cover from the first Title and applies it to all. The album Tag is to be used when you have one Episode, e.g. "Fußballhelden" with seperate chapters (different Title Tags), then you use the Album Tag "Fußballhelden" so it merges the mp3 files to one logic episode. Like one CD with different tracks.
What you trying to do is seperating different Collections (Drei ???, Star Wars etc.) by using Albums, which is not correct.
You need a function merging multiple Episodes (which can be individual Albums) to a Collection, which is not possible in Voice.

**Comment by PaulWoitaschek** [comment]
Thanks for your idea. 
Though I think showing distinct covers is not the right solution here. I think in the long term we should rather allow for a way to really support this kind of series. 
Right now, the concept is rather: Every item is one book. And books conceptually only have one cover.

**Comment by sabi0** [comment]
Some books have "chapter images" though:
https://images.squarespace-cdn.com/content/v1/5372e4d2e4b0fca9449770f9/1560311619321-S7GF14PVJ7ETLWZPNBC5/polly1-book5_diana-toledano.png

Do you think Voice could accept this concept?

After all, if files in a book have the same cover image in their tags switching the display on the file change ... will not change anything (visually).
But if they do have different images, probably, that's intentional?

Take for instance a book with 20 "chapters" like this:
https://www.amazon.de/-/en/Miss-%C3%9Cberraschung-Mr-Men-Little/dp/3948410844
Having them all as separate books would not be particularly convenient.
