### ISSUE TITLE
App reopens in backrgound

### ISSUE THREAD

**Issue by Artyom-K** [PaulWoitaschek/Voice#1649]
### Overview

The app reappears in the notification panel after I close it swiping it away from recent apps. If then I swipe it away from notification panel, it reappears again.

### How to reproduce

1. Use the app.
2. Close it (removing from recent apps)

### Version

5.0.1

### Android Version

Android 9

### Device Model

HTC U11+

**Comment by polyzen** [comment]
On Android 10 (Nokia 6.1) as well.

**Comment by gachikuku** [comment]
On (Pixel 7 Pro) Android 13 as well.

**Comment by byronigoe** [comment]
On Samsung Galaxy S9 Android 10 too.

**Comment by PaulWoitaschek** [comment]
Version 5 is ancient, this should not happen in newer versions.

**Comment by sanderr** [comment]
I'm seeing this same behavior in 6.4.1 on Android 13 unless I restrict battery usage, which causes its own issues.

**Comment by PaulWoitaschek** [comment]
Please use the latest version for testing this.

**Comment by Artyom-K** [comment]
I'm not sure how to check which version I actually have. Google Play says current version is 5.0.1. If I use the button to report bug from the app it says I have 6.1.2. I tried downloading the latest .apk from F-Droid website but they won't install for some reason.

**Comment by PaulWoitaschek** [comment]
The latest version is 7.0.1  (currently in google play review)
https://github.com/PaulWoitaschek/Voice/releases/tag/7.0.1

**Comment by sanderr** [comment]
Thanks for the clarification. I just subscribed to beta testing for this App (Play Store version), is that what you meant by review? I don't see the newer version yet but I'll make sure to install it, from GitHub if need be. I'll report back if I see it still.

**Comment by PaulWoitaschek** [comment]
Review means that google play reviews the App for functionallity. Once that is passed the beta version will be updated.

**Comment by polyzen** [comment]
> Version 5 is ancient, this should not happen in newer versions.

I missed that the original report was using that version. I've actually been on 6.5.0. Will update once it hits F-Droid.

**Comment by polyzen** [comment]
Appears to be resolved with v7.0.0 🎉
