### ISSUE TITLE
UI inconsistency with Skip amount and Auto rewind

### ISSUE THREAD

**Issue by ctntt** [PaulWoitaschek/Voice#1651]
### Overview

If you go to the preferences and change the skip amount (f.e. to 30 seconds) it doesn't change the '20s' to '30s' below the skip buttons in the player. (Maybe one could remove the '20s' below the button and just display the arrows.)

Also if you go to the preferences and click on 'Auto rewind' the text 'Skip amount' is displayed above the slider instead of 'Auto rewind'.

### How to reproduce

1. Open the App
2. Click on the gear icon 
3. In preferences click on Skip amount 
4. Change the Skip amount
5. Close Preferences
6. Click on a book and look at the skip buttons
![Screenshot_20221230](https://user-images.githubusercontent.com/115667885/210020579-a29c863a-6f56-498c-9063-e658226a9283.png)

### Version

6.5.0

### Android Version

12

### Device Model

OnePlus 8t

**Comment by PaulWoitaschek** [comment]
This is fixed in 7.0 (by removing the seek time from the buttons)
