### ISSUE TITLE
Issue with playback of larger (2GB) audiobooks.

### ISSUE THREAD

**Issue by zsln** [PaulWoitaschek/Voice#1653]
### Overview

I have several audiobooks around the 2GB file size mark. So far, all of the files which are larger than 2GB have an issue with playback somewhere after 20 hours of playback.

The app goes silent, the time stamp is not updated anymore in the app (in the notification bar it is though) and scrubbing around a bit does not resume audio, except for scrolling back multiple hours.

Here is the exif data of one such file:
```
ExifTool Version Number         : 12.50
File Size                       : 2.2 GB
File Modification Date/Time     : 2022:05:24 19:23:20+02:00
File Access Date/Time           : 2022:09:11 16:58:24+02:00
File Inode Change Date/Time     : 2022:09:11 16:39:07+02:00
File Permissions                : -rw-r--r--
File Type                       : OPUS
File Type Extension             : opus
MIME Type                       : audio/ogg
Opus Version                    : 1
Audio Channels                  : 2
Sample Rate                     : 48000
Output Gain                     : 1
Vendor                          : Lavf59.27.100
Language                        : eng
Encoder                         : Lavf59.27.100
```

For the first file where this issue this occured somewhere between the 24th and the 25th hour of playback.

I assumed there was some intereger overflow going on with a sampling rate of 48kHz, as it would match with the 24th/25th hour mark where this occured. But on another file this issue occured way earlier.

Also all files below 2GB do not have this issue, even going beyond 30 hours. VLC has no issues with playback of any of these files.

This issue is similar to Issue #1094 however, the audio is not encoded using mp3.

### How to reproduce

1. Open the App
2. Play a .opus file, larger than 2GB
3. Skip to a timestamp beyond 25 hours
4. Playback hangs, no recovery

### Version

6.5.0

### Android Version

Android 11

### Device Model

Fairphone 4

**Comment by PaulWoitaschek** [comment]
Thanks for the report!
As it's not actionable from the perspective of Voice, I'll close this.

If you can send me a link to a file, I will try to reproduce it and file a bug on https://github.com/google/ExoPlayer

**Comment by PaulWoitaschek** [comment]
Thanks, here we go: https://github.com/androidx/media/issues/391

**Comment by PaulWoitaschek** [comment]
Good news: it's actually a bug in exoplayer and will be fixed.

**Comment by PaulWoitaschek** [comment]
Closing this as it will be eventually fixed when exoplayer releases and as there is nothing actionable to do here.

**Comment by zsln** [comment]
I just want to mention that in ExoPlayers [latest release](https://github.com/google/ExoPlayer/releases/tag/r2.19.0) they seemed to have fixed the bug, under:
"Extractors:
    Ogg: Fix bug when seeking in files with a long duration (https://github.com/androidx/media/issues/391)."
 
 As they released this only a few days after the lastest release of Voice, I wanted to ask whether this requires a rebuild of Voice with the new version of this library, or if the update is distributed via some Android library?
