### ISSUE TITLE
all files in a audiobook labeled as "ch0"

### ISSUE THREAD

**Issue by Yavos** [PaulWoitaschek/Voice#1655]
### Overview

When adding an audiobook folder which contains mp3 files with additional non-standard tags all the chapters/files in that audiobook are labeled "ch0" making it pretty difficult to see where you currently are at (file-/chapter-wise) or to find a specific chapter or point of time in there.

I can't figure out if specific tags are the cause or too many tags or whatever. Here's 2 examples of what's working and what not...
example of tags **not** working:
```
Artist Name : Terry Pratchett
Track Title : 006 - Der fünfte Elefant
Album Title : Der fünfte Elefant
Date : 2011
Genre : Audiobook
Composer : 
Performer : 
Album Artist : Terry Pratchett
Track Number : 6
Total Tracks : 129
Disc Number : 1
Total Discs : 1
Comment : Im Auftrag des Patriziers reist Sam Mumm von der Stadtwache in das geheimnisvolle Land Überwald...
<COPYRIGHT> : ©2000 Wilhelm Goldmann Verlag, München (P)2011 Random House Audio
<ENCODING SETTINGS> : Lavf58.29.100
<MUSICIAN CREDITS> : Author/Terry Pratchett
<PUBLISHER> : Random House Audio, Deutschland
```

example of tags **working**:
```
Artist Name : Terry Pratchett
Track Title : 0107 Das Erbe des Zauberers
Album Title : Das Erbe des Zauberers
Date : 2016
Genre : Hörbuch
Composer : 
Performer : Katharina Thalbach
Album Artist : 
Track Number : 
Total Tracks : 
Disc Number : 
Total Discs : 
Comment : 
<ENCODED BY> : iTunes 12.3.2.35
```

(At first I suspected an additional .m3u file in the folder being the culprit but deleting that one and rescanning the files with complete app reset resulted in the same problem. So I'm pretty sure the tags are somehow at fault.)

### How to reproduce

1. add folder with (several?) additional non-standard mp3 tags to Voice
2. open audiobook
3. see "ch0" in chapters list

### Version

6.5.0 (F-Droid)

### Android Version

10

### Device Model

Xiaomi Redmi Note 9 Pro

**Comment by Yavos** [comment]
Okay, so after manually deleting the non-standard-tags (with foobar2000) it still won't properly parse the chapters.
Maybe it's got something to do with another property...

I'm attaching a sample file for troubleshooting. (Simply add in a folder with any other mp3. You will see it popping up as "ch0" in the imported audiobook.)
[sample file.zip](https://github.com/PaulWoitaschek/Voice/files/10328966/sample.file.zip)

**Comment by xcy7e** [comment]
This has to be a bug with your idv3 Tags and not Voice itself.

**Comment by sojusnik** [comment]
Any ideas how to solve this idv3 Tags bug, because I already tried to rename the tags or remove them, but this issue remains?

**Comment by PaulWoitaschek** [comment]
Can you send me a file where you have this issue?

**Comment by sojusnik** [comment]
Just sent you a mail with the files

**Comment by PaulWoitaschek** [comment]
An ffprobe returns:

```
➜  Downloads ffprobe 01.\ Title.mp3 
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mp3, from '01. Title.mp3':
  Metadata:
    title           : Title
    artist          : Patrick McKeown
    track           : 1/29
    album           : The Oxygen Advantage
    date            : 2016
    encoder         : Lavf57.83.100
    album_artist    : Patrick McKeown
  Duration: 00:02:10.19, start: 0.023989, bitrate: 65 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 130.121000
      Metadata:
        title           : ch0
    Chapter #0:1: start 130.121000, end 130.171000
      Metadata:
        title           : ch1
  Stream #0:0: Audio: mp3, 22050 Hz, stereo, fltp, 64 kb/s
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      title           : Album cover
      comment         : Cover (front)
```

So in this file, there are two chapters, one called `ch1` and one `ch2`.

I'll close this for now.

Here is a chatGpt answer 🙃 


> Here are some OSS recommendations for editing mp3 chapter marks, along with the platforms they support:
> 
> 1. Mp3splt - Supported Platforms: Windows, Mac OS X, and Linux
> 2. Audiobook Cutter - Supported Platforms: Windows and Linux
> 3. MP3DirectCut - Supported Platforms: Windows
> 4. MP3tag - Supported Platforms: Windows
> 5. Kid3 - Supported Platforms: Windows, Mac OS X, and Linux
> 6. AudioShell - Supported Platforms: Windows
> 7. EasyTAG - Supported Platforms: Windows and Linux
> 8. Foobar2000 - Supported Platforms: Windows
> 9. Picard - Supported Platforms: Windows, Mac OS X, and Linux
> 10. MusicBrainz Picard - Supported Platforms: Windows, Mac OS X, and Linux
> 
> To use any of these tools to edit chapter marks in an mp3 file, you'll need to download and install the tool for your platform of choice, and then use the tool's interface to load the mp3 file and edit the chapter marks. Each tool will have its own unique interface and set of instructions for editing chapter marks, so be sure to consult the tool's documentation or online resources for guidance on how to use it.

**Comment by Yavos** [comment]
Just to give feedback: It was the same issue for me. I edited my mp3 tags with foobar2000 but that apparently doesn't support chapters, so I didn't see them at all. (In my case I only have a single chapter labeled "ch0", though.)

Knowing what it was I agree it's not a bug.
