### ISSUE TITLE
Low res default cover on Android 13

### ISSUE THREAD

**Issue by homocomputeris** [PaulWoitaschek/Voice#1662]
### Overview

Low res default cover in Android 13 system drawer
![Screenshot_20230202-174531_Voice](https://user-images.githubusercontent.com/7422433/216388461-41ce4963-d79d-467e-aba4-3af2e7039129.png)

### How to reproduce

Open a book without any cover image

### Version

6.4.1

### Android Version

33

### Device Model

ONEPLUS A6003

**Comment by PaulWoitaschek** [comment]
That's fixed by 7.0
