### ISSUE TITLE
Widget periodically doesn't respond to clicks to start

### ISSUE THREAD

**Issue by jedfonner** [PaulWoitaschek/Voice#1667]
### Overview

Multiple times a day, I will click the play icon on the Voice widget on my homescreen and nothing will happen.  Clicking multiple times has no effect.  If I click the book artwork on the left side of the widget, it will open Voice at which point I can click the play button which works fine.

### How to reproduce

1. Add widget to homescreen
2. wait an indeterminate amount of time
3. click play icon on widget
4. notice nothing happens

### Version

version 5.0.1

### Android Version

Android 13 Feb 5 2023 Security update

### Device Model

Pixel 6a

**Comment by jedfonner** [comment]
Note: I've already set the "App battery usage" for Voice to "Unrestricted"

**Comment by PaulWoitaschek** [comment]
This should be fixed in 7.0
