### ISSUE TITLE
Double and triple headset button press stopped working in 7.0.0 as opposed to 6.4.1

### ISSUE THREAD

**Issue by mars4science** [PaulWoitaschek/Voice#1710]
### Overview

Great app, been using it for several years already, thanks a lot for the work!

Bug:

I got 7.0.0 from f-droid (https://f-droid.org/en/packages/de.ph1b.audiobook/). Installed on newer phone and was surprised double and triple headset button press did not work. I've removed 6.4.1 from another phone, installed 7.0.0 and checked - 2 and 3 presses do not work, work on 6.4.1 on both phones.

One is 9 another 11 Android (just in case). Also with 7.0.0 subjectively even single press seemed to work not as promptly as in 6.4.1, but that is I'm not sure.

P.S. IIRC several years ago headset buttons events did not work, I guess it is a new feature I discovered "accidentally" after installing newer version on another phone, IMO would be good if readme on github or even better short help in menu of the app included such things for users, maybe there are even more useful functionality I and others do not know of. TIA

### How to reproduce

Start play, double press headset button, no skip forward noted.

### Version

7.0.0

### Android Version

9

### Device Model

CAT

**Comment by PaulWoitaschek** [comment]
Unfortunately fdroid is super slow in it's updates and didn't pick up the hotfix:
https://github.com/PaulWoitaschek/Voice/releases/tag/7.0.2-2

Let me know if that doesn't work for you!

**Comment by mars4science** [comment]
@PaulWoitaschek , thanks! Good to know you are so fast to response to issues!
