### ISSUE TITLE
Bluetooth connection crashes when starting a track

### ISSUE THREAD

**Issue by krihabu** [PaulWoitaschek/Voice#1716]
### Overview

The Bluetooth connection crashes when starting a track with the app.

This can be reproduced with two different Bluetooth devices (headphones and speakers).

This behavior started immediately after updating to 7.0.0.

### How to reproduce

1. Connect to Bluetooth device
2. Open Voice app
3. Start track
4. Error shows up ("Bluetooth wird wiederholt beendet",  translation "Bluetooth repeatedly terminates")
5. Stuck in loop with trying to reconnect and failing
6. Connection gets reestablished as soon the app is closed

### Version

7.0.0

### Android Version

e/OS 1.8.1

### Device Model

Fairphone 3+

**Comment by krihabu** [comment]
Sorry, only now discovered https://github.com/PaulWoitaschek/Voice/issues/1701
Is the fix already integrated in a newer version?

**Comment by PaulWoitaschek** [comment]
Yes, it is! Fdroid is only a little slow in deploying updates. Fantastic bug report though! 💯

**Comment by PaulWoitaschek** [comment]
(In the meantime you can grab the latest version from Github: https://github.com/PaulWoitaschek/Voice/releases/tag/7.0.3)

**Comment by krihabu** [comment]
Thanks and great app by the way :)
