### ISSUE TITLE
Phone crashes with Bluetooth

### ISSUE THREAD

**Issue by proedie** [PaulWoitaschek/Voice#1719]
### Overview

When trying to play a file via Bluetooth, first the Bluetooth app keeps crashing while playback is in progress (stuttering), after a few seconds the whole phone reboots. Reproducibly. 

### How to reproduce

1. Connect phone to a Bluetooth speaker.
2. Play an audio book.
3. Playback stutters.
4. Bluetooth crashes and restarts and crashes and restarts ...
5. Boot screen!

### Version

7.0.0 from F-Droid

### Android Version

Android 11 (/e/OS 1.8.1 no Google)

### Device Model

Fairphone 3+/IKEA Eneby 20 gen 2 speaker

**Comment by PaulWoitaschek** [comment]
Thanks for the report! Here are two more reports of the same issue:

https://github.com/PaulWoitaschek/Voice/issues/1716
https://github.com/PaulWoitaschek/Voice/issues/1701

**Comment by proedie** [comment]
Oops. Sorry, searched for it, but only in open issues. Thank you for the super quick response time!
