### ISSUE TITLE
Bluetooth/Launcher crashes when starting Voice playback

### ISSUE THREAD

**Issue by jo-grue** [PaulWoitaschek/Voice#1723]
### Overview

I recently encountered the problem, that the bluetooth of my device crashes, when i start the playback from voice, even if no bluetooth device is connected. One time it caused even the device launcher to crash and makes the device unresponsible until the launcher eventually restarts.
I assume the problem appeared with the new version 7.0, because I changed nothing but updating voice a few days ago. Before that everything worked fine with that nice app.
Sorry if my description lacks information, I am not familiar in bug-reporting.

### How to reproduce

1. Activate Bluetooth
2. Open Voice 7.0
3. Start playback

### Version

7.0

### Android Version

11 (Lineage OS 18.1)

### Device Model

Sony Xperia XZ1 Compact

**Comment by PaulWoitaschek** [comment]
Thanks for the report! Here are two more reports of the same issue:

https://github.com/PaulWoitaschek/Voice/issues/1716
https://github.com/PaulWoitaschek/Voice/issues/1701
#1719

**Comment by PaulWoitaschek** [comment]
I've now pinned the very first Report to stop more of these from coming 😊
