### ISSUE TITLE
Crashing when adding a folder.

### ISSUE THREAD

**Issue by BhaturaGuy** [PaulWoitaschek/Voice#1725]
### Overview

Simply crashes when I click on add folder. I can add files though.

### How to reproduce

1. Open the app.
2. Click Audiobook folders
3. Click add symbol on bottom right.
4. Select folder and click add.

### Version

7.0.3

### Android Version

13

### Device Model

DN2101

**Comment by PaulWoitaschek** [comment]
Do you have any kind of custom firmware?

It's the same issue as:
https://github.com/PaulWoitaschek/Voice/issues/1472

and really should not happen on Android devices.

**Comment by PaulWoitaschek** [comment]
https://android.stackexchange.com/questions/249521/oneplus-nord-file-manager-not-able-to-open-intent

Yep 🤷

**Comment by PaulWoitaschek** [comment]
At least it should no longer crash as of https://github.com/PaulWoitaschek/Voice/commit/da532af0abc866f5b283f5d2fd397463b4aaae67
