### ISSUE TITLE
Voice not in the list of the android auto apps

### ISSUE THREAD

**Issue by Ansem93** [PaulWoitaschek/Voice#1727]
### Overview

Voice doesn't compare in the list of the app that i can use with android auto. 
I don't get if it's a bug or if it's not possible to make voice compatible with android auto

### How to reproduce

Go into android auto -> list of apps-> try to find voice

### Version

7

### Android Version

13

### Device Model

Galaxy s21

**Comment by PaulWoitaschek** [comment]
Where did you get the app from? Imo Android Auto does some signature checking and only shows Voice if I signed the app (and not fdroid)

**Comment by Ansem93** [comment]
The app was installed from f droid.
If I try the play store link it say that is not compatible with my s21+ .
I also had to enable beta testing because otherwise the latest version was voice 5.0  (not compatible)

**Comment by PaulWoitaschek** [comment]
You need to uninstall the fdroid Version first

**Comment by PaulWoitaschek** [comment]
Weird. Please try the GitHub release apk

**Comment by Ansem93** [comment]
Installed the 7.0.3 from github without issues,just like from fdroid.
I rebooted the phone to be sure, but it still doesn't show up in the android auto app list

**Comment by PaulWoitaschek** [comment]
Does it appear now? By now 7.0.3 is also released on Play.

**Comment by Ansem93** [comment]
Can confirm that now i see it! And when I installed it by play store it works with android auto too!

Out of curiosity: what was the parameter that was making the app "not compatible"?

**Comment by PaulWoitaschek** [comment]
I have no idea actually. I think Android auto has some checks in place so that apps only appear after versions have been approved in Google Play.

**Comment by ViToni** [comment]
> Where did you get the app from? Imo Android Auto does some signature checking and only shows Voice if I signed the app (and not fdroid)

Maybe this would be a useful point for the FAQ. At least I wasn't able to find it and at first I thought of a bug (I'm using the f-droid version...)

**Comment by PaulWoitaschek** [comment]
Good idea, done!

https://voice.woitaschek.de/faq/
