### ISSUE TITLE
Can't see numbers and controls on lock screen 

### ISSUE THREAD

**Issue by cfreds** [PaulWoitaschek/Voice#1751]
### Overview

I decided upgrade the app, previous I was using from play store and was working nice (except can't play at 1.25x only 1.2x, 1.3x and always use at 1.25)

I love this version but I have one problem on lock screen (my lock screen is back) can't see the controls, or number, progress, nothing. Only white.

Already give all permission (except send multimedia messages). Only one thing: I can't see options for notifications.

I hope you could fix it. Here is what I see:

![IMG_20230325_230938](https://user-images.githubusercontent.com/49008136/227756602-5efe41e7-19cd-461d-a25e-f3c64f1db180.jpg)

### How to reproduce

1. Open the app
2. Turn off the screen.
3. Double tap to see lock screen and voice.
4. Only show me white, nothing of progress, controls, time. (This is because (probably) all of them are in same color white)

### Version

7.0.5

### Android Version

13

### Device Model

M2101K9G (Xiaomi 11 Lite 5G)

**Comment by PaulWoitaschek** [comment]
# Permission

> except send multimedia messages

What does that mean? Where do you see such a permission? Did you try to grant it?

# Interaction

This is how it's looking on stock Android.
![Screenshot_20230326-074139](https://user-images.githubusercontent.com/743462/227757594-91217ac1-f48c-434e-8d07-c9c404505be2.png)

What happens if you touch the notification? Can you touch it where the playback controls are on my phone?

# Bug report
Can you try to capture and send me a bug report, right after you started voice and saw the controls once?

https://developer.android.com/studio/debug/bug-report

**Comment by cfreds** [comment]
What happens if you touch the notification?
R:/ Once App info: there no option to activate notifications. No icon of notification on up side 

Can you touch it where the playback controls are on my phone?
R:/ Yes i can touch. And work but the color of actual time playing and total time is the same of the background check. As can you see in the image.

Also change the lock screen wallpaper and is the same problem.

Can you try to capture and send me a bug report, right after you started voice and saw the controls once?
R:/ Yes, already do it. But it's a big file, could you tell me where is the voice debug info.

![IMG_20230326_102220](https://user-images.githubusercontent.com/49008136/227799536-dc82295c-4395-43b8-8146-b0a59e68f819.jpg)

**Comment by PaulWoitaschek** [comment]
It's this some kind of a custom ROM? This is definitely not how Android 13 should look like

**Comment by PaulWoitaschek** [comment]
It looks like a bug on the miui side 🤷 

https://www.reddit.com/r/miui/comments/11iqxmt/help_with_notification_centre_contrast/

**Comment by cfreds** [comment]
Thanks for your time i appreciated a lot.

Maybe is not problem of MUI, because voice from play store works great, as can you see. Only don't have option to play a 1.25 or 1.35 only 1.10, 1.20, 1.30x. 

![Screenshot_2023-03-26-14-22-49-167_de ph1b audiobook](https://user-images.githubusercontent.com/49008136/227802621-0162b4a2-397d-41c0-b6cb-bbb8fc93df76.jpg)

**Comment by cfreds** [comment]
Thanks for your time i appreciated a lot.

Maybe is not problem of MUI, because voice from play store works great, as can you see. Only don't have option to play a 1.25 or 1.35 only 1.10, 1.20, 1.30x

![IMG_20230326_142201](https://user-images.githubusercontent.com/49008136/227802738-a1ff9628-3cea-4284-843d-32e67d1147e1.jpg)

**Comment by PaulWoitaschek** [comment]
The version that you see on play is targeting probably < API 13, that's why you see that behavior. Voice is doing absolutely nothing special with the notification and the whole handling is taken care of by Google:
https://github.com/androidx/media

**Comment by cfreds** [comment]
Yes. It target Android 10. SDK 29Q.
