### ISSUE TITLE
Google Play Doesn't Recognize Pixel 6a as Compatible Device

### ISSUE THREAD

**Issue by andspenrob** [PaulWoitaschek/Voice#1752]
### Overview

I tried to download/install this on my Pixel 6a but couldn't find it. Finally found the app page, but it says "App is not available for your device". Is there a flag that needs to be flipped to allow installation on Pixel 6a?

### How to reproduce

Find app on Google Play App Store, log into your Google Account, and attempt to click "Install".

### Version

5.0.1

### Android Version

Android 13

### Device Model

Pixel 6a

**Comment by PaulWoitaschek** [comment]
Do you have the fdroid version installed by any chance or any other version of voice?

**Comment by andspenrob** [comment]
I'm migrating from a Pixel 4a 5G on Google Android 13 where I had downloaded it thru f-droid and it worked great! I'm on a 6a with GrapheneOS and was hoping to avoid needing f-droid, so was trying to get the Google Play version... I could sideload it if needed, but figured I'd try to set it up to auto-update...

**Comment by tomsparely** [comment]
A friend of mine just migrated from a Pixel 3a to a Pixel 6a (both stock Android) and I had the same issue when trying to set them up with some audiobooks. I wonder if there is an issue with transferring apps/data from the old device? I believe they had Voice installed on the 3a.

**Comment by PaulWoitaschek** [comment]
I think this should be fixed now with the full rollout of 7.x.
If not, please report ASAP :)
