### ISSUE TITLE
v7 is missing covert art in Android Auto

### ISSUE THREAD

**Issue by jedfonner** [PaulWoitaschek/Voice#1770]
### Overview

When playing a book in Android Auto, no cover art is displayed when Voice is the frontmost app.  Strangely, when Voice is a mini-player under the Map, it shows the cover art.

![PXL_20230406_214507165 MP](https://user-images.githubusercontent.com/344481/230521741-87b168cb-4d62-4855-b4a5-99dce4bdce3a.jpg)

![PXL_20230406_214611197 MP](https://user-images.githubusercontent.com/344481/230521754-e2765de5-b47f-44f6-9142-921e3d91c079.jpg)

### How to reproduce

1. Start playing a book in Voice via Android Auto
2. Click the app to make Voice the frontmost app
3. Notice no cover image is displayed
4. Switch to Google Maps
5. Notice that the mini-player shows the cover art

### Version

7.0.5

### Android Version

13

### Device Model

Pixel 6a

**Comment by BartemX** [comment]
Same is happening here, after latest update (version 7.0.5).

**Comment by yeo-gen** [comment]
I also have a problem with the list of recent books. Previously, the list was sorted from the most recent to the oldest. Now the list has changed the sorting order, so the last book that is currently playing is at the bottom of the list, and it takes a long time to scroll down. Please restore the sorting list from the most recent at the top to the oldest at the bottom. 
(1+ 8 Pro, Android 13, Voice 7.0.7)
