### ISSUE TITLE
Version 7 breaks skip buttons

### ISSUE THREAD

**Issue by yusufmte** [PaulWoitaschek/Voice#1772]
### Overview

Hello,

First of all thank you for this wonderful app! It really has been the perfect audiobook app, simple and ingenious.

Since updating from version 6.5.0 to version 7.0.0, the skip button (forward and back) has not been working properly.

-It no longer says "20 s" (or whatever you set as the skip amount) under the button
-Clicking the skip button only moves 5 seconds, regardless of what the setting is
-Trying to use other devices' media buttons to skip (car, watch, earbuds) no longer works (this worked perfectly on the previous version)

### How to reproduce

1. Update from 6.5.0 to 7.0.0
2. Change Skip Amount in settings
3. Open a file and try to skip around

### Version

7.0.0

### Android Version

33

### Device Model

Pixel 7

**Comment by PaulWoitaschek** [comment]
Please update 🙃

**Comment by yusufmte** [comment]
> Please update 🙃

Haha, thank you! It is working now on 7.0.6 🙂

FYI not a big deal / not sure if it is intentional, but it still doesn't show the skip amount under the buttons anymore-- that was a nice touch.

**Comment by PaulWoitaschek** [comment]
Yeah sorry about that, i wanted to go for a more minimal approach

**Comment by yusufmte** [comment]
No worries, looks good either way IMO :) Just wanted to check in case it was unintended. Thank you for your help! 👍
