### ISSUE TITLE
Book title is displayed as a link

### ISSUE THREAD

**Issue by Tealk** [PaulWoitaschek/Voice#1773]
### Overview

Book title is displayed as a link:
![Screenshot_20230407-115449](https://user-images.githubusercontent.com/12276250/230588848-0a6eebdf-762f-478a-8b8c-0f2dcd18fc31.png)

### How to reproduce

Open the App
Click on Book icon
Add a Folder with subfolders

### Version

7.0.5

### Android Version

GraphenOS 13

### Device Model

Pixel 6

**Comment by PaulWoitaschek** [comment]
Could you send me the file with which this is happening?

**Comment by Tealk** [comment]
This is a folder with a lot of voice files, I don't think it's legal if I send them out

**Comment by PaulWoitaschek** [comment]
Closing this for now as I have no idea, how to fix this without a file with which this reproduces.
If someone manages to send me a file to my Email I'll reopen and investigate.

**Comment by Tealk** [comment]
So you can solve it by rebuilding the library, but it is a very ugly possibility.
Would it be possible to add a button that simply re-reads the data, but without losing the current status?

**Comment by PaulWoitaschek** [comment]
It was a bug that it wasn't recognized. It should be sufficient to rename the folder or file you want to rescanned.
