### ISSUE TITLE
Skipping backwards to last chapter always jumps to start of chapter

### ISSUE THREAD

**Issue by tomaThomas** [PaulWoitaschek/Voice#1776]
### Overview

In previous versions (I think < 7), it was possible to skip 20 seconds backwards when being at the beginning of a chapter. You ended up 20 seconds before the previous chapter ends (at least if the book was playing). In the current version this is not possible anymore and you always end up at the beginning of the previous chapter

### How to reproduce

1. Start a chapter that is not the first
2. Press the skip backwards button

### Version

7.0.6

### Android Version

Lineage 13

### Device Model

OnePlus 6

**Comment by PaulWoitaschek** [comment]
User report:
> The same is true for skipping forward

**Comment by tomaThomas** [comment]
> User report:
> > The same is true for skipping forward

True, altough this was also the behaviour before and I would even expect this; a chapter is a barrier you likely want to end up at. When skipping backwards (e.g. because you were distracted and missed the last seconds), ending up at the beginning of the previous chapter (which could be half an hour before) is definitely not what I would expect
The old behaviour was that you only landed in the previous chapter if you skipped backwards within the first second of the chapter, otherwise you landed at the beginning of the chapter playing. But I wouldn't mind if always exactly the interval is skipped...

**Comment by PaulWoitaschek** [comment]
Once the CI completes you should find an artifact APK.
https://github.com/PaulWoitaschek/Voice/actions/runs/4678809910/jobs/8287990353

Can you manually verify if this matches your expectations? I went with the "But I wouldn't mind if always exactly the interval is skipped..." way ;)

**Comment by tomaThomas** [comment]
Works like a charm, thanks!
