### ISSUE TITLE
have to force close to resume after stopping

### ISSUE THREAD

**Issue by bkw777** [PaulWoitaschek/Voice#1788]
### Overview

since last uptdate the play button does not start playing sometimes after pausing for some time.

but force closing the process and restarting makes play work again

### How to reproduce

1  start playing a book  
2  pause/stop  
3  ? unknown what must happen here, leave paused for some time, over 30 minutes or an hour? or maybe it also requires using some other media player? But do not reboot or manually kill the background sleeping Voice pro ess.  
4  press play (nothing happens), repeat any number of times.  
5  manually close the sleeping Voice process (lineageos long-press square, swipe the Voice card upwards)  
6 Open Voice and play. Play works.

### Version

7.0.6

### Android Version

33  LineageOS 20-20230326-NIGHTLY-bramble (Android 13)

### Device Model

Pixel 4a (5G)

**Comment by PaulWoitaschek** [comment]
But then the bug is this one https://github.com/PaulWoitaschek/Voice/issues/1777 and not that there is no force close button right?

**Comment by bkw777** [comment]
symptoms sound the same. I'm not asking for a force close button.
I'll try downgrading to 7.0.5 because the problem is new and I haven't changed the os or any settings recently.

**Comment by bkw777** [comment]
I have discovered that force-close is not the only way to get play working again. When the play button doesn't work, you can also select some other book, and play will work on that, then switch back to the original book, and play will now work on that book that didn't before, without ever force-closing the app.

When will the supposedly fixed version appear in F-Droid?

**Comment by PaulWoitaschek** [comment]
I don't know. I think they usually build every two weeks.

**Comment by marekmarecki** [comment]
Unfortunately it still occasionally happens to me, but another workaround is to rewind track back to start

[voice.webm](https://github.com/PaulWoitaschek/Voice/assets/776138/f871658e-068a-408d-916c-5864822c3c78)
