### ISSUE TITLE
Incorrect outcome when seeking backwards from beginning of chapter

### ISSUE THREAD

**Issue by somombo** [PaulWoitaschek/Voice#1800]
### Overview

> **From Discussion https://github.com/PaulWoitaschek/Voice/discussions/1758** 
> In v6 of the app I could keep pressing the "seek backwards" button until it goes to the end of the previous chapter. This was a very practical and useful feature please consider bringing it back, otherwise I am forced to use v6 and forgo other bug fixes and feature updates

Seeking backwards at begining of current chapter goes to begining previous chapter instead of (near the) end of the previous chapter

### How to reproduce

1. Open the app into an audiobook ready to play
2. Place the progress marker at  the begining of Chapter Two i.e time `ch2#00:00`
3. Tap the "seek backwards" button once  or until the current chapter changes to Chapter One (if you are not already at the beginning, as in step1, you may have to tap it more than once)

#### Expectation 
If we assume the previous Chapter1 is 12 minutes and 34 seconds long in total, and the "skip amount" (in the settings menu) is set to 15 seconds, then I expect tapping seek backwards to put the progress marker at 12 minutes and 19 seconds i.e: 
```
ch2#00:00 - 15s = ch1#12:34 - 15s = ch1#12:19
````
Which is indeed what happens in v6.4.1 of the app.

However, v7.0.6 is putting the marker at `ch1#00:00`   (begining of previous chapter) which is not helpful.

### Version

7.0.6

### Android Version

33

### Device Model

Pixel 7 Pro

**Comment by PaulWoitaschek** [comment]
Thanks for reporting! Please update to 7.0.7 :)

https://github.com/PaulWoitaschek/Voice/issues/1776

**Comment by somombo** [comment]
there's no 7.0.7 apk in the release. See:
![Screenshot_20230420-112129](https://user-images.githubusercontent.com/5506400/233351594-1e23a7ff-e7ec-431e-aa15-ef8296d4ca94.png)
