### ISSUE TITLE
Dismissing battery optimization toast permanently

### ISSUE THREAD

**Issue by deadcombo** [PaulWoitaschek/Voice#1801]
Version 7.0.6

Hello,

My phone uses the AOSP implementation of battery optimization which respects apps just fine, I don't need to disable it. Voice is kept alive as long as it's playing.
Please allow me to keep it from prompting me every I press play. 

Your app is lovely, thank you.

**Comment by PaulWoitaschek** [comment]
May I ask what kind of phone you use?

**Comment by deadcombo** [comment]
Yeah, I have a Pixel 7 Pro. Cheers for accepting this!
