### ISSUE TITLE
Cover art missing in notification drawer

### ISSUE THREAD

**Issue by jedfonner** [PaulWoitaschek/Voice#1805]
### Overview

When I play a book in Voice, a notification is added to the notification drawer with controls to start, rewind, fast forward, etc. For some books (not all), the cover art is missing from the notification.  I've tried updating the cover art both using "Cover from the Internet" as well as "Cover from the file system".

Here's Voice showing the book has cover art:
![Screenshot_20230422-074730](https://user-images.githubusercontent.com/344481/233783544-9b78664d-c34d-41ae-94b5-855132e1a15e.png)

Here's the notification drawer:
![Screenshot_20230422-074738](https://user-images.githubusercontent.com/344481/233783564-3cc0cea6-5ce9-4543-9568-9f49fc855a1c.png)

### How to reproduce

1. Open the App
1. Click on Play
1. Pull down the notification drawer

### Version

7.0.7

### Android Version

Android 13

### Device Model

Pixel 6a

**Comment by PaulWoitaschek** [comment]
I believe this was fixed by https://github.com/PaulWoitaschek/Voice/pull/1870 and should work in 7.0.10+

Due to restrictions in androidx media it's currently necessary to restart your app after changing the cover.
If it's happening nevertheless, please comment and I'll reopen.
