### ISSUE TITLE
Incorrect player for back mod

### ISSUE THREAD

**Issue by deppaa** [PaulWoitaschek/Voice#1809]
### Overview

Player controls 

### How to reproduce

Mi11lite 5g ne miui 11
Enable black mod
Open app
Start playing
![IMG_20230425_081024](https://user-images.githubusercontent.com/42480615/234165418-c4ee49a3-2b7d-4927-889c-ce6fd9d18979.jpg)

### Version

7.0.7

### Android Version

33

### Device Model

2109119DG

**Comment by PaulWoitaschek** [comment]
Can you file this bug against the developer of the "black mod"?

**Comment by deppaa** [comment]
Everything works fine in other apps.

**Comment by PaulWoitaschek** [comment]
Voice is using the standard Android notification style. Maybe other apps don't target Android 13 yet?
I'd file this bug against the mod developer; Voice is really doing only out of the box behavior here, without any special modifications.

**Comment by deppaa** [comment]
Ok, thanks
