### ISSUE TITLE
Audiobook playback not working during phone calls

### ISSUE THREAD

**Issue by somombo** [PaulWoitaschek/Voice#1812]
### Overview

When I am on a call (e.g. whatsapp or regular phone call), audiobooks are not playing regardless of how many times i try to hit the play button. They do finally play when once the call has ended.

However, what I expect is for the audiobook to play when I hit the play button during an ongoing call i.e. I ought to hear both the audiobook's audio and audio from whoever I am speaking to on the phone together simultaneously.

> Since this used to work correctly in prior versions (described below) but doesn't anymore, I decided to file this as a bug rather than a feature request ([discussed here](https://github.com/PaulWoitaschek/Voice/discussions/1759))

### How to reproduce

1. Start a phone call
2. (While on the call) Open an audiobook in the app 
3. Click on Play
(Nothing happens: no playback, no audio)

### Versions

I tested all of the following older versions and found that they actually all work **correctly** in the way that I expect (as described above): 
-  versions 4.3.0, 4.2.1, 4.0.2, 4.0.0-rc8, 4.0.0-rc7, v3.6.3, v2.9.3.7, v1.5.3

Additionally, I tested the following as well and  found that they **do NOT** work correctly: 

- v4.3.1, v4.3.3, playstore v5.0.1, 5.0.2, 6.4.1, 7.0.7 

### Android Version

33

### Device Model

Pixel 7 Pro

**Comment by PaulWoitaschek** [comment]
Yes, that's a behavior change. However I think it is correct:

https://developer.android.com/guide/topics/media-apps/audio-focus

Playback should only start if Audio focus can be gained.
