### ISSUE TITLE
Voice not listing all the chapters in a book

### ISSUE THREAD

**Issue by THEKIWSA** [PaulWoitaschek/Voice#1813]
### Overview

Used to show all the chapters in a book, now stops at 888. The holy bible has like 1135 chapters...

### How to reproduce

Setup Voice. Play time shown for large books eg. "The Holy Bible" is way short. Play any book with lots of chapters , cannot select later chapters, play stops after last chapter shown on dropdown.

### Version

7.0.7

### Android Version

28

### Device Model

SM-S767VL

**Comment by PaulWoitaschek** [comment]
Can you send me a file with which this is happening?

**Comment by THEKIWSA** [comment]
If gmail will let me send the large file...nope 25mb limit and this file is
over 600...do you have a way i can send it to you?

**Comment by PaulWoitaschek** [comment]
Yes, you can send me a link to Google drive.

**Comment by THEKIWSA** [comment]
Bible.zip
<https://drive.google.com/file/d/1--_nX9TvvKXEa20E5484BIw4uTbepAZ9/view?usp=drivesdk>
Done and done ;)

**Comment by PaulWoitaschek** [comment]
And is 888 an exact number? On my Pixel 7 it shows all of them.

**Comment by PaulWoitaschek** [comment]
Additional info by mail; leaving it here so we don't lose information:

> So after you told me you had no bug reproduction on the Pixel it got me to thinking... You probably have more free space on your internal drive for cache and such or at least more ram, I am not familiar with the Pixel's specs. So I freed a couple of gigs and it is now kind of working. Voice finds all the files in the Bible but doesn't find more than 4 books and I have a couple of dozen in the dir...they were all showing before I freed up more space. Also, with 2 copies of the files they show different play lengths. It is like Voice is stoping its search on some kind of caching or ram issue. Anyway I thought I would let you know, just incase it helps with tracking.

**Comment by PaulWoitaschek** [comment]
Actually I think this is mostly due to slowness of the scanning.

This should be fixed to some degree by https://github.com/PaulWoitaschek/Voice/pull/1874
However it will still take time. On my device it takes about 50ms per file. 

With 1135 files x 50ms that's about one minute for the scan now. That's not super great but at least better than before.
