### ISSUE TITLE
reboot in loop since v7.07

### ISSUE THREAD

**Issue by fnark69** [PaulWoitaschek/Voice#1819]
### Overview

hi, 
Since the new version 7.07 my phone Xiamoi MI9 reboot in loop since I start play for an audio book.
Since 3 years with Voice without any problem, it's the first time Voice bug. No problem with previous version. 
Thanks you a lot
Regards

### How to reproduce

reboot in loop since I start play for an audio book

### Version

7.0.7

### Android Version

11 RKQ1 200826 002

### Device Model

MI 9

**Comment by PaulWoitaschek** [comment]
Discussions are happening here: #1860
