### ISSUE TITLE
Playback speed setting ignored when used in  android auto.

### ISSUE THREAD

**Issue by matzman** [PaulWoitaschek/Voice#1827]
### Overview

After the last update when the  app starts from android AUTO the playback speed is set to 1.0. If I open the app on mobile and set the speed again it is fixed but I have to do it every time. 

### How to reproduce

Start app from Android AUTO (v9.3.631434). 
Start audiobook 

### Version

V7.07

### Android Version

13

### Device Model

Poco F3

**Comment by tduvally** [comment]
Seeing the same issue on Android 12, Samsung Galaxy S10+.

If the app hasn't been used in Android Auto for a few hours this occurs, but it remembers the speed setting if relaunched shortly after being used. I've tried adding it to "Never Sleeping Apps", but Voice doesn't appear on the list of available apps to add.
