### ISSUE TITLE
Додаток раптово закривається.

### ISSUE THREAD

**Issue by nahaba** [PaulWoitaschek/Voice#1830]
### Overview

Після останнього оновлення додаток періодично видає помилку з написом що він не відповідає і закривається. Це стається не завжди, але після паузи та виходу смартфона зі сну і спробі продовжити відтворення.

### How to reproduce

1 Відкрити програму
2 запустити відтворення аудіокниги
3 встановити на паузу.
4 вимкнути екран смартфона
5 ввімкнути смартфон
6 натиснути відтворити
7 додаток періодично після цього зависає.

### Version

7.0.7

### Android Version

11

### Device Model

TECNO KF6n

**Comment by PaulWoitaschek** [comment]
# Translation

### Overview

After the latest update, the application periodically displays an error message stating that it is not responding and then closes. This happens not always, but after a pause and when the smartphone is taken out of sleep mode and an attempt is made to resume playback.

### How to reproduce

1. Open the application
2. Start playing an audiobook
3. Pause the playback.
4. Turn off the smartphone screen
5. Turn on the smartphone
6. Press play
7. After this, the application periodically freezes.

### Version

7.0.7

### Android Version

11

### Device Model

TECNO KF6n

**Comment by PaulWoitaschek** [comment]
Спасибо за отчет. Это дубликат #1860 и сейчас исправлен.

Thanks for the report. This is a duplicate of #1860 and is fixed now.
