### ISSUE TITLE
Update to 7.0.7 removed previous config

### ISSUE THREAD

**Issue by facundoq** [PaulWoitaschek/Voice#1835]
### Overview

The latest update removed the config i had and all the book progressions

### How to reproduce

Install previous version, use it for years
Update to 7.0.7
Open voice

### Version

7.0.7

### Android Version

31

### Device Model

moto g(60)s

**Comment by PaulWoitaschek** [comment]
Did you see the in app explanation for this? There should have been an explanation within the app, explaining why that was necessary.
Sorry for the inconvenience.
