### ISSUE TITLE
Android 11 reboot

### ISSUE THREAD

**Issue by eliasbrg** [PaulWoitaschek/Voice#1840]
### Overview

After start play an audiobook the phone reboots

### How to reproduce

Open app, click on play, audiobook start playing, screen flashes and after while phone reboot

### Version

7.0.7

### Android Version

11

### Device Model

Mi A3

**Comment by ahskur** [comment]
I've had somehow the same problem. 
Was using 7.07 on Android 12.1 and had a sudden reboot after listening for just about 2 hours.
Haven't noticed this behavior on 7.0.9 as of today.

**Comment by PaulWoitaschek** [comment]
Discussions are happening here: #1860
