### ISSUE TITLE
After update to 7.0.7 all settings are gone

### ISSUE THREAD

**Issue by Digioso** [PaulWoitaschek/Voice#1845]
### Overview

I have voice installed on two Android Phones. On both the app was updated automatically last night. And on both all settings / audio books are gone in Voice! So I have to readd them... Honestly this should be a BIG no-go! If this happens again I'll be switching to another app...

### How to reproduce

1. Open the App.
2. See everything's gone.

### Version

7.0.7

### Android Version

12 & 8

### Device Model

Huawei Mate 20 Pro & Samsung Galaxy S7 Edge

**Comment by PaulWoitaschek** [comment]
That was necessary due to an update in the Android Framework. You should also have seen an explanation for this from within the App, as well as a hint how to restore your old configuration.
Sorry for the inconvenience.
