### ISSUE TITLE
Flickering screen and reboot when trying to play a file

### ISSUE THREAD

**Issue by Pjbdragon** [PaulWoitaschek/Voice#1860]
### Overview

When I try to play an audiobook, i get a message about not enough power snd something else (not enough time to read it), audio starts playing but screen flicker on and off. At this point, I lost all control of phone interface and shortly after phone reboots. During reboot it say something is corrupted and offers to retry. Upon retrying the phone reboots okay. Nothing more I can do, the update ruined it. I tried uninstalling and reinstalling again. Same problem. Please fix, it worked great the way it was.

### How to reproduce

I explained above.

### Version

7.0.7

### Android Version

30

### Device Model

moto g power

**Comment by eliasbrg** [comment]
I have exactly the same behavior

**Comment by PaulWoitaschek** [comment]
@eliasbrg 

Could you try noting down the complete message that you see?

And please capture a bug report and send it, right after it happend:
https://developer.android.com/studio/debug/bug-report

**Comment by Pjbdragon** [comment]
The message reads 'Due to power restrictions, playback interruption might happen'
This flashes on the bottom of the screen in a box overtop of the play controls for a couple tenths of a second before the screen starts flashing between black and my background image.
After 30 seconds to a minute the phone reboots itself but gets an error when it tries to load the Android system. This message reads ' Cannot load Android system. If you continue to get this message, you may need to perform a factory data reset and erase all user data stored on this device.'I'm given a menu with the choices: 'Try again' and 'Factory data reset'
No other application does this and I can reboot normally without errors.
[bugreport-sofia_retail-RPMS31.Q1-54-13-11-2023-05-11-13-28-54.zip](https://github.com/PaulWoitaschek/Voice/files/11454990/bugreport-sofia_retail-RPMS31.Q1-54-13-11-2023-05-11-13-28-54.zip)

**Comment by PaulWoitaschek** [comment]
Thanks. I suggest you to remove the file as it might contain sensible information.

**Comment by PaulWoitaschek** [comment]
Unfortunately it's not helpful. Apparently exactly the crash reason couldn't be determined. It would be helpful to get these bug reports from others (to my mail please)

```
--------- beginning of crash
11-02 13:56:55.586  root   782   782 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 782 (init), pid 782 (init)
11-02 13:56:55.642  root   782   782 F libc    : crash_dump helper failed to exec
--------- beginning of system
```

**Comment by PaulWoitaschek** [comment]
Ah btw:
Does it happen with 7.0.9 as well?
https://github.com/PaulWoitaschek/Voice/releases/download/7.0.9/app-release.apk

**Comment by eliasbrg** [comment]
> Ah btw: Does it happen with 7.0.9 as well? https://github.com/PaulWoitaschek/Voice/releases/download/7.0.9/app-release.apk

Yes, the same problem and with 7.0.9

**Comment by Pjbdragon** [comment]
Thank you for removing the file - I was concerned but didn't know how to get the bug report to you without sharing it here (this is the first time I tried retrieving and sending a bug report from my phone).

I never had problems with previous versions - the app has worked rock-solid for me up until the most recent update (boy do I miss it - hard to continue in my audiobook now). I will explore how to go to version 7.0.9, I get my apps through Google Play Store, so I need to do a little research - I will work on that later and let you know - any advice is appreciated.

**Comment by eliasbrg** [comment]
> @eliasbrg
> 
> Could you try noting down the complete message that you see?
> 
> And please capture a bug report and send it, right after it happend: https://developer.android.com/studio/debug/bug-report

 I don't know how to capture a report, the phone is flashing and It's not possible to access developer tools while flashing

**Comment by PaulWoitaschek** [comment]
Does it reproduce with one or both of these? The first one most certainly not
* https://github.com/PaulWoitaschek/Voice/releases/tag/6.4.1
* https://github.com/PaulWoitaschek/Voice/releases/tag/7.0.0-1

**Comment by eliasbrg** [comment]
> Does it reproduce with one or both of these? The first one most certainly not
> 
> * https://github.com/PaulWoitaschek/Voice/releases/tag/6.4.1
> * https://github.com/PaulWoitaschek/Voice/releases/tag/7.0.0-1

Both are OK!

**Comment by PaulWoitaschek** [comment]
Ha, that's a surprise!

First of all, thanks for your engagement to fix this, I've tried 5 different phones and a bunch of emulators and this issue is happening nowhere!

Can you try different versions to find out when it started happening?

**Comment by PaulWoitaschek** [comment]
Even weirder.

So it must be somewhere here:

https://github.com/PaulWoitaschek/Voice/compare/7.0.6...7.0.7

Is it happening with this one?
https://github.com/PaulWoitaschek/Voice/suites/12147565100/artifacts/640760310

**Comment by eliasbrg** [comment]
This is ok

**Comment by PaulWoitaschek** [comment]
I have a few theories:
1. It is generally only happening on release builds. If that's true then https://github.com/PaulWoitaschek/Voice/actions/runs/4709930101 should not show the problem
2. It's related to the UI. If that is true then the problem should not reproduce if you close the app and use the widget from the home screen to play a book
3. It's related to the Android Gradle Plugin update. If that's true then this: https://github.com/PaulWoitaschek/Voice/suites/12196684734/artifacts/644309307 should not reproduce the issue, but this should: https://github.com/PaulWoitaschek/Voice/suites/12256074695/artifacts/648790920
4. I have no clue and it would be great to know at which build it started. For that you could go here: https://github.com/PaulWoitaschek/Voice/compare/7.0.6...7.0.7, click on the green checkmarks and then `test details`
<img width="579" alt="grafik" src="https://github.com/PaulWoitaschek/Voice/assets/743462/d7afa3d0-392e-45a6-b303-865b872e48c9">

Then Summary:
<img width="424" alt="grafik" src="https://github.com/PaulWoitaschek/Voice/assets/743462/72d36ece-71d8-4993-ae2b-ea0f947ce133">

And then artifacts:
<img width="493" alt="grafik" src="https://github.com/PaulWoitaschek/Voice/assets/743462/1855922c-1634-4844-ae7c-e75c5a98f7b1">

**Comment by eliasbrg** [comment]
> I have a few theories:
> 
> 1. It is generally only happening on release builds. If that's true then https://github.com/PaulWoitaschek/Voice/actions/runs/4709930101 should not show the problem ->**The problem appears**
> 2. It's related to the UI. If that is true then the problem should not reproduce if you close the app and use the widget from the home screen to play a book  ->**The problem appears**
> 3. It's related to the Android Gradle Plugin update. If that's true then this: https://github.com/PaulWoitaschek/Voice/suites/12196684734/artifacts/644309307  **-> This is ok**  should not reproduce the issue, but this should: https://github.com/PaulWoitaschek/Voice/suites/12256074695/artifacts/648790920 **->The problem appears!**

**Comment by PaulWoitaschek** [comment]
Okay, continuing tomorrow.

So far we have it pretty narrowed down.

Bad:
b80ee65cbc79c97c0956d6cb6460439afebcc2a8

Good:
42d46d44b305de3596316f5716f0b2176673c4af

Diff:
https://github.com/PaulWoitaschek/Voice/compare/42d46d44b305de3596316f5716f0b2176673c4af..b80ee65cbc79c97c0956d6cb6460439afebcc2a8

**Comment by PaulWoitaschek** [comment]
I created a few more builds. Can you check which of these work and which don't?

https://drive.google.com/drive/folders/1qRcVqWpwNczPe7JlCsa8W7elrzXGLV5F?usp=sharing

For the reference: I've created this script to automate the building of all apks between two commits.
https://gist.github.com/PaulWoitaschek/d4686579441a01702e1c481a46f327d2

**Comment by eliasbrg** [comment]
0-8c5cbb585c370f7638aa4f2ed3251efc12a308d0.apk OK
2-81d0b8b2e9358cce37d9171cba2fdbccef06f73a.apk OK
6-a0a1afadfbf0bee1dfc80ddc160d1aa80b0d3381.apk OK
7-08e842a63afd06cdd483966077bb3ef33cd9ffde.apk Problem!
9-b80ee65cbc79c97c0956d6cb6460439afebcc2a8.apk Problem!

**Comment by PaulWoitaschek** [comment]
Lol, that's ridiculous.

This commit causes your phone to reboot? 08e842a63afd06cdd483966077bb3ef33cd9ffde

* What kind of phone do you use? (Model + Android Version)
* Does it crash when you try to play a book that has no cover?
* Which of these reproduces? https://drive.google.com/drive/folders/1zlb_X9CXSuJNcvMQx0p3kj-obqofDINU?usp=sharing

## Baseline
Current main

## no-android-auto-uri-grant
```patch
Index: playback/src/main/kotlin/voice/playback/session/ImageFileProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/playback/src/main/kotlin/voice/playback/session/ImageFileProvider.kt b/playback/src/main/kotlin/voice/playback/session/ImageFileProvider.kt
--- a/playback/src/main/kotlin/voice/playback/session/ImageFileProvider.kt	(revision 05f66e29c6a745120d16500e2207afb3c2576993)
+++ b/playback/src/main/kotlin/voice/playback/session/ImageFileProvider.kt	(date 1683916361696)
@@ -1,7 +1,6 @@
 package voice.playback.session
 
 import android.app.Application
-import android.content.Intent
 import android.net.Uri
 import androidx.core.content.FileProvider
 import java.io.File
@@ -19,12 +18,5 @@
         application.packageName + ".coverprovider",
         file,
       )
-      .also { uri ->
-        application.grantUriPermission(
-          "com.google.android.projection.gearhead",
-          uri,
-          Intent.FLAG_GRANT_READ_URI_PERMISSION,
-        )
-      }
   }
 }
```

## no-covers-at-all
```patch
Index: playback/src/main/kotlin/voice/playback/session/MediaItemProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/playback/src/main/kotlin/voice/playback/session/MediaItemProvider.kt b/playback/src/main/kotlin/voice/playback/session/MediaItemProvider.kt
--- a/playback/src/main/kotlin/voice/playback/session/MediaItemProvider.kt	(revision 05f66e29c6a745120d16500e2207afb3c2576993)
+++ b/playback/src/main/kotlin/voice/playback/session/MediaItemProvider.kt	(date 1683916361705)
@@ -141,5 +141,5 @@
     extras = mediaItemChapterMarkExtras(chapter.chapterMarks),
   )
 
-  private fun File.toProvidedUri(): Uri = imageFileProvider.uri(this)
+  private fun File.toProvidedUri(): Uri? = null
 }
```

**Comment by eliasbrg** [comment]
There is cover  jpg file in the audiobook folders. I delete it the problem disappears! ver 7.0.9 from playstore

**Comment by PaulWoitaschek** [comment]
Wow, what a ride! Thanks for your endless testing efforts.

I'm pretty certain that this is the fix, can you verify?

https://drive.google.com/file/d/1RL1CJyLGTHXLXBmW3LShqLpsFkic5wl0/view?usp=sharing

**Comment by eliasbrg** [comment]
Yes, all perfect now!! Thanks for your amazing support!
