### ISSUE TITLE
New m4b's not playing

### ISSUE THREAD

**Issue by RalfRoemling** [PaulWoitaschek/Voice#1866]
### Overview

Had copied some new m4b to my device and while the old ones do fine, the news ones won't play. I get a short "Play" animation (= Pause-Button) then it defaults to "Play-Button" no error or anything is shown.

When i try to open with vlc it works as intended.

### How to reproduce

see Overview

### Version

7.0.9

### Android Version

Lineage 18.1

### Device Model

Samsung S4 mini VE (aka GT-i9195i)

**Comment by PaulWoitaschek** [comment]
Thanks for the report. Could you send me a link to one of the non playing files to my mail?

**Comment by PaulWoitaschek** [comment]
Thanks. Could you check if this fixes it for you?
https://github.com/PaulWoitaschek/Voice/suites/12867157376/artifacts/693892258
