### ISSUE TITLE
Voice stopped after Minutes

### ISSUE THREAD

**Issue by ghost** [PaulWoitaschek/Voice#1871]
### Overview

Although the app has all the required permissions, it shuts down when the smartphone is in sleep mode!
Battery optimization is disabled and the app has permission to continue running in the background

### How to reproduce

1. Open the App
2. Click Play
3. After 2 Minutes the Smartphone-Screen changes to LockScreen
4. 1 Minutes later the App stopped play

### Version

7.0.9

### Android Version

EMUI 12.0.0

### Device Model

Huawei P20

**Comment by PaulWoitaschek** [comment]
Thanks for the report!

Could you send me a bug report to my mail?
https://developer.android.com/studio/debug/bug-report

**Comment by PaulWoitaschek** [comment]
Closing as the user deleted their account 🤷

**Comment by Plaete** [comment]
Count me in for this behavior.

I am using an Huawei P20 lite with Android 9 / EMUI 9.1.0.
As far as I can see, battery optimization is disabled for voice, so I have no idea why it stops the playback when screen is locked. No difference between playback over bluetooth or directly through the speaker of the phone.

I'll send you my bug report by email.

**Comment by PaulWoitaschek** [comment]
Thanks @Plaete 

Could you try if this build shows the same error?
https://drive.google.com/file/d/1hRm-3hMHETt0sjUDpXEK8r75ZCM2SSxP/view?usp=share_link
