### ISSUE TITLE
Rewind and forward buttons don't show in lock screen

### ISSUE THREAD

**Issue by Darrow555** [PaulWoitaschek/Voice#1904]
### Overview

before the update i had the rewind and forward buttons in the lock screen, now there is only the play/pause button

Before

![image](https://github.com/PaulWoitaschek/Voice/assets/133532843/b5c7b355-86bd-4b08-9e31-aaf92459d77a)

After
![WhatsApp Image 2023-05-13 at 19 37 36](https://github.com/PaulWoitaschek/Voice/assets/133532843/9a06ba05-f3ac-4a32-8001-442322f8b665)

### How to reproduce

1.Open the app
2.Click on Play
3.Lock the screen
4.Press the power button

### Version

7.0.10

### Android Version

11

### Device Model

Xiaomi Redmi Note 7

**Comment by PaulWoitaschek** [comment]
Thanks for the report. This will be fixed in Version 7.0.13

https://github.com/PaulWoitaschek/Voice/pull/1905
