### ISSUE TITLE
Loss off Bluetooth remote control functionality 

### ISSUE THREAD

**Issue by PsuedoSancrosanct** [PaulWoitaschek/Voice#1913]
### Overview

Before version 7 connecting to Bluetooth gave me full control and start/stop would make Voice play. With v7 after connecting bt the remote start button does nothing. Voice needs to be started through device, only after a manual start will bt remote controls work.

Edit: figured out notifications play now and playback need to be enabled to restore this function. 

### How to reproduce

See overview 

### Version

7.0.10

### Android Version

31

### Device Model

SC-41A

**Comment by shme14** [comment]
To add to this, ever since version 7.0 Tasker is unable to start playback via the "Media Control" action unless Voice is already opened in the foreground and has media focus. Before, at any point I could tell Tasker to tell Voice to play and it would even without focus. I have downgraded to 6.4.1 and it works great again!

**Comment by cromulent403** [comment]
Have run into the same problem with Tasker and Bluetooth with version 7+.  Thank you for tip as to which version to downgrade to.

**Comment by PaulWoitaschek** [comment]
Correct me if I'm wrong, but I believe all apps handle it like this.

I think that it actually was a bug that in previous versions Voice was always active and eating batteries.

Regarding tasker: For such support, someone would need to build dedicated functionality.

**Comment by shme14** [comment]
I can't speak for all media apps, but I use Power Amp for music and Voice for audio books. In Tasker you can select which app you want the "Media Control" command to target. With the old version of Voice and the newest version of Power Amp it worked flawlessly from a fresh boot.

I could capture media control using Tasker when a bluetooth device connects, and wait to see if Next or Previous track is pressed. If Next is pressed, Music will start Via PowerAmp and if Previous is pressed, then Voice starts my current book. It works great!

Now it does not. If this is intended that is fine. I will continue to use V6 Voice.

I really appreciate all the work put into developing this app!

**Comment by PaulWoitaschek** [comment]
Yep, they have dedicated support for that. 

And it would be totally possible for Voice, but as I don't use it and as it's a niche feature, this won't be implemented by me in the foreseen future. 
If someone wants to develop this I could give guidance though.

**Comment by PaulWoitaschek** [comment]
I need to revise my post and I think this is actually something we can easily bring back!

**Comment by cromulent403** [comment]
Thanks so much. Works perfectly in Version 7.0.14 using the built in Media Control action in Tasker - like it did in 6.4.1
