### ISSUE TITLE
Choosing Cover For Audiobook

### ISSUE THREAD

**Issue by ShawnNason** [PaulWoitaschek/Voice#1917]
### Overview

Recently the app is having a problem when you try to choose a cover from the internet for an audiobook, in that you now can't control the search, and you now can't center the pictur,e and it crashes the app when you click "set"

### How to reproduce

1. Open the app
2. Long press on an audiobook without a "cover"
3. Click on "select cover from internet"
4. 1st problem: doesn't show search, just shows various covers
5. Click on cover
6. No option to center the picture just a wide "guidance dot"
7. Click "set" (the only thing available to do)
8. App crashes and user is sent back to desktop screen

### Version

7.0.12

### Android Version

31

### Device Model

moto g stylus 5G

**Comment by PaulWoitaschek** [comment]
Thanks for your feedback. I added a search function as as part of 7.0.14. Also the crash was fixed.
