### ISSUE TITLE
Unable to add Audiobook folder

### ISSUE THREAD

**Issue by Synapscident** [PaulWoitaschek/Voice#1919]
### Overview

Hi. Voice was working fine on my phone, and I really liked it, and then it just ... stopped.

It fails when I try to add my audiobook folder (which it used to use).

### How to reproduce

Open the app
It says "Let's add your audiobook folder..."
It click that. It opens the Audiobook Folders window.
I click the "+ Add" button.
I choose to add a Folder
Nothing happens. I'm still in the Audiobook Folders window.
I can repeat over and over with no change in behaviour.

### Version

7.0.12

### Android Version

BraXOS

### Device Model

BraX2 (International)

**Comment by PaulWoitaschek** [comment]
It seems that a vital part of the Android Framework is missing - DocumentsUI - the built in Android File Manager.

com.android.google.documentsUI

Maybe you disabled it? There is nothing that can be done here from Voice.
