### ISSUE TITLE
Jumps forward while playing

### ISSUE THREAD

**Issue by Bombasticbo** [PaulWoitaschek/Voice#1948]
### Overview

Wonderful player, been using it for years. Since the last update, it occasionally jumps a few minutes during playback. Also, you can no longer switch to night/dark mode. 

### How to reproduce

Sporadical

### Version

7.0.12

### Android Version

33

### Device Model

SM-S908B

**Comment by PaulWoitaschek** [comment]
* Could you please describe the behavior of the jump in more detail? For example, does it skip forward or backward? How many minutes does it typically jump?
* How often does that happen?
* Does that happen while you are certain that you don't press any buttons; especially headset buttons?
* Can you see any patterns regarding with which files this is happening?
* Can you send me a file that triggers this issue?

**Comment by Bombasticbo** [comment]
Thank you for the quick response.
It has only occurred 4-5 times so far. Each time forward, about 6-15 minutes. I had the phone in my pocket and the display was off in all cases. Unfortunately, I do not know how to trigger this. The file was an MP3 file, about 40 minutes long.

**Comment by PaulWoitaschek** [comment]
Hm, this sounds media specific. Maybe it's possible that it was happening by accident and that somehow the buttons were pressed while in the pocket?

Regarding the night mode: Voice follows your system settings, so you can change your system to dark mode and Voice will follow.

**Comment by Bombasticbo** [comment]
Thanks for your reply.
Maybe your right. I'll keep an eye on it and let you know if it happens again.

Viele Grüße von Unterwegs

________________________________
Von: Paul Woitaschek ***@***.***>
Gesendet: Samstag, 3. Juni 2023 08:59
An: PaulWoitaschek/Voice
Cc: Bo; Comment
Betreff: Re: [PaulWoitaschek/Voice] Jumps forward while playing (Issue #1948)


Hm, this sounds media specific. Maybe it's possible that it was happening by accident and that somehow the buttons were pressed while in the pocket?

Regarding the night mode: Voice follows your system settings, so you can change your system to dark mode and Voice will follow.

**Comment by PaulWoitaschek** [comment]
Okay thanks! Then I'll close this for now.
