### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by zer0fl0w** [PaulWoitaschek/Voice#1955]
current release is tagged as v7.1.0 but gets installed as v7.0.15. very minor, just cosmetical.
update-trackers get confused by it, because they look for version-numbers.

**Comment by PaulWoitaschek** [comment]
Thanks! What do you mean by "gets installed as"? Where do you install it from?

**Comment by PaulWoitaschek** [comment]
Still curious to know what was wrong, but this will be fixed with the 7.1.1 that's coming now.

**Comment by zer0fl0w** [comment]
you grab the apk from releases.
install it. than you check the versionnumber of installed package. with an appmanager or under settings/apps/voice (scroll to botttom).

v7.1.1 fixed the issue. thanks.
