### ISSUE TITLE
Phone's native back button won't work if settings menu is open

### ISSUE THREAD

**Issue by xcy7e** [PaulWoitaschek/Voice#1964]
### Overview

A rather unimportant usabiilty bug, when the options drop down menu is open,the native back button does not work. I'd expect it to close the menu or go back directly.

### How to reproduce

Open the three dot menu in an audiobook detail view. Then press the native back button of the launcher/phone.

![Screenshot_20230604_184201_Voice](https://github.com/PaulWoitaschek/Voice/assets/5656573/a5faf175-19cf-4224-830f-a905d71bfd99)

### Version

7.1.2

### Android Version

13

### Device Model

Galaxy A51

**Comment by PaulWoitaschek** [comment]
Thanks for the report :) 

That's an upstream bug. I've reported it here and it will be fixed when it's fixed by Google:
https://issuetracker.google.com/issues/285847710
