### ISSUE TITLE
Internet fetched covers

### ISSUE THREAD

**Issue by metbic** [PaulWoitaschek/Voice#1971]
### Overview

Internet cover fetch now working on f-droid 7.0.14
The cover search delivers results but it doesnt lead me anywhere.
The select/save dialog is broken. 

### How to reproduce

1 open app
2 pick audiobook without cover
3 use internet cover search
4 pick one cover
5 the save dialogue is truncated, the selected image is not shown, saving is not possible 

### Version

7. 0.14 fdroid

### Android Version

9 pie 

### Device Model

Sony xz1c

**Comment by PaulWoitaschek** [comment]
Thanks for the report! This was already reported in #1962 and is fixed in 7.2.0
