### ISSUE TITLE
Cover from the internet bug

### ISSUE THREAD

**Issue by thangcuoi** [PaulWoitaschek/Voice#1973]
### Overview

The app keep showing the previous cover when clicking on the correct cover from the internet.

### How to reproduce

1. Choose download cover from the internet and click on any image to load the image in a popup.
2. Click within the popup image > Set
3. Repeat step 1 on another audiobook and click on a different image. 

The app would load the image from Step 1 instead of the image from Step 3. The only workaround is to force stop the app.

### Version

7.1.2

### Android Version

33

### Device Model

SM-G996B

**Comment by PaulWoitaschek** [comment]
Thanks for the detailed report!

This was already reported in #1962 and #1971 and is now fixed in 7.1.3. Please update :)
