### ISSUE TITLE
Resuming audio from quick settings pull down doesn't work

### ISSUE THREAD

**Issue by royweisfeld** [PaulWoitaschek/Voice#1985]
### Overview

Using android 13 on an LMI I'm having an issue with resuming from the media player widget on android 13, 
only when resuming playback from the app does it really work. Weird

Reproduces multiple times, I've also reinstalled the phone a few times. And the app itself.

### How to reproduce

1. Play an audiobook
2. Pause for about 30 minutes and play other media sources
3. Try to resume from quick settings pulldown

### Version

7.1.2

### Android Version

33

### Device Model

POCO F2 Pro

**Comment by PaulWoitaschek** [comment]
Can you please try this release and report back if it fixes your issue? (you can download and install the attached apk)

https://github.com/PaulWoitaschek/Voice/releases/tag/8.1.1

**Comment by royweisfeld** [comment]
Currently I'm all out of audiobooks but once I have a new one I'll update you :) Thanks!
