### ISSUE TITLE
covers are not shown when audiobooks are on SD card

### ISSUE THREAD

**Issue by stveg** [PaulWoitaschek/Voice#1986]
### Overview

My audiobooks are saved on sdcard. covers are all saved on internal memory, but not shown anymore in the app v7.1.3
![Screenshot_20230611_130554_Cx File Explorer](https://github.com/PaulWoitaschek/Voice/assets/136237438/f04035c2-1fc8-43db-813f-13f4366a558c)

### How to reproduce

open app

### Version

7.1.3

### Android Version

13

### Device Model

SM-A715F

**Comment by stveg** [comment]
![Screenshot_20230611_131147_Voice](https://github.com/PaulWoitaschek/Voice/assets/136237438/680265d4-af58-41af-86c0-452021d7cacc)

**Comment by PaulWoitaschek** [comment]
That's the place where old versions of voice used to save the covers. 
Could you describe more in detail, what you expect voice to do and what it doesn't?

**Comment by stveg** [comment]
Hi Paul,
old version had shown all covers.
In new version I was asked to add my audiobooks folder on sdcard, than all books were listed, but without showing a cover. Also during play the cover is not displayed (see picture in comments).
Maybe you expect the cover pictures on the same "drive" like the books. There is also a folder on sdcard named Android/data/de.ph1b.audiobook, but empty.
hope it helps to fix the sdcard issue on Android 13. Other audiobook players like MortPlayer had an issue with sdcard already with Android 12. Seems that sdcards will not be supported by Android in future, top phones have no sdcards anymore...
regards,
Stefan from germany




Am 11. Juni 2023 14:14:51 MESZ schrieb Paul Woitaschek ***@***.***>:

**Comment by PaulWoitaschek** [comment]
Thanks for the explanation.

Could you describe, how your file structure looks like and where do the images live?

Does it look like this and is your problem that these covers are not being recognized?

```
./
├── book1
│   ├── 1.mp3
│   ├── 2.mp3
│   └── cover.jpg
└── book2
    ├── 1.mp3
    ├── 2.mp3
    └── cover.jpg
```

**Comment by stveg** [comment]
After several hours of scanning the audiobooks folder finally all covers are back.

My structure is like this, but I don't have a  cover.jpg in each folder. Each mp3 has an internal cover picture and each folder had a folder.jpg (windows).

I have 65 audiobooks on my sdcard, 38GB, 10000 mp3 files.

Maybe during initial scan for audiobooks the found covers should be displayed faster.

Now I am happy again. VOICE is great app!


Am 11. Juni 2023 20:12:55 MESZ schrieb Paul Woitaschek ***@***.***>:

**Comment by PaulWoitaschek** [comment]
Yep, unfortunately the file access using the storage access framework is painfully slow. 
Voice does it's best to prioritize and cache what it can. 

Generally speaking: the less files, the faster voice scans. So if you can I'd suggest to rather have a few huge m4b files with chapter marks instead of a huge amount of smaller mp3 files. 

In addition: yes, first the media is being scanned, then the covers. 
This is for the simple reason that I believe that it's more important to get your books asap and that it's okay if covers follow later, at least people can start listening then.
