### ISSUE TITLE
App notification not staying away

### ISSUE THREAD

**Issue by Puuma** [PaulWoitaschek/Voice#1991]
### Overview

After updating the app from Play store repo yesterday, the app notification has gotten completely out of hand.

Even after closing all apps. A few minutes later a black and white notification of currently paused audiobook will appear on it's own. After I dismiss said notification, a few seconds later a color version notification of the curretly paused audiobook will appear. After I dismiss the color notificaiton, it will stay away for a while, only to appear eventually on it's own.

If I start the app manually, the notification (color version) will immediately appear (I'm not sure if this has always been the case), even if I don't press play. Then after closing the app, the notification will presist. If I then dismiss the notification, it will re-appear in about 3 seconds (color version). And if I dismiss that, it will stay away for a while, but eventually re-appear on its own.

I expect the notification to appear only if I do one of the following things:
1. Start the Voice app, AND press play
2. Press play on the Voice widget

### How to reproduce

1. Close all apps
2. Dismiss all notifications
3. Wait for it...

### Version

7.1.3

### Android Version

9

### Device Model

uleFone Armor 5

**Comment by PYCODR** [comment]
Same here on Galaxy A54 with Android 13

**Comment by PYCODR** [comment]
Same here on Galaxy A54 with Android 13 and voice 8.0.0

**Comment by PaulWoitaschek** [comment]
I believe this is closely related to https://github.com/PaulWoitaschek/Voice/issues/2008

Can you please try this release and report back if it fixes your issue?

https://github.com/PaulWoitaschek/Voice/releases/tag/8.1.1
