### ISSUE TITLE
Not possible to add anything, because the buttons are not visible

### ISSUE THREAD

**Issue by Digioso** [PaulWoitaschek/Voice#2007]
### Overview

The buttons to actually add something are not visible and it is not possible to scroll down to the buttons.

![IMG_20230623_142650](https://github.com/PaulWoitaschek/Voice/assets/10660450/270edbc8-f22e-47a1-a1f4-0d963f46c0f7)

### How to reproduce

1 Open the App
2. Click the books icon
3. Click on "Hinzufügen"
4. Then it says that I can add books. However the buttons to actually add folders or single tracks are not visible. It is not possible to scroll down to the buttons. On another phone with a larger display the buttons are visible.

### Version

8.0.0

### Android Version

8

### Device Model

Samsung Galaxy S7 Edge

**Comment by PaulWoitaschek** [comment]
Thanks for the report! 
As a workaround you can put the device into horizontal orientation.

**Comment by Digioso** [comment]
Thanks! The workaround works!

**Comment by PaulWoitaschek** [comment]
Can you please try this release and report back if it fixes your issue? (you can download and install the attached apk)

https://github.com/PaulWoitaschek/Voice/releases/tag/8.1.1

**Comment by Digioso** [comment]
Thanks, but there is no change.

**Comment by PaulWoitaschek** [comment]
Thanks for trying out.

Could you give this a try?

https://drive.google.com/file/d/1XVmvwDXuiFNmlSoaLLyGtgH0RQzIFM6P/view?usp=drive_link

A scroll bar is not a good solution because users will not know that they need to scroll. The correct solution is to make the image smaller, and or hide it.

**Comment by Digioso** [comment]
Thanks! That version works!
