### ISSUE TITLE
App requires restart to resume play

### ISSUE THREAD

**Issue by nookits** [PaulWoitaschek/Voice#2013]
### Overview

When the app is not in use for some time and then returned to content will not play. Clicking the play button does nothing. If you return to the app immediately there is not problem. 

To resolve the problem the app can be closed completely (pressing the overview button and swiping to clear the app). 

This is possibly an optimisation issue, but I have set the app to have unrestricted battery use and the problem persists. 

### How to reproduce

Open app
Play content
Pause content
Press home button
Go use some other apps. 
Return to app
Press play

### Version

7.0.6

### Android Version

12

### Device Model

Fair phone 4

**Comment by PaulWoitaschek** [comment]
Please update your App and report back if this doesn't fix your issue :)

**Comment by nookits** [comment]
Appears fixed with v 8.0.0. Apologies I thought I had the latest version.
