### ISSUE TITLE
Can't Open App

### ISSUE THREAD

**Issue by xomifred** [PaulWoitaschek/Voice#2014]
### Overview

![Screenshot_20230630_080103_Device care](https://github.com/PaulWoitaschek/Voice/assets/119944370/fcb8af4b-ea36-46b3-beea-3e5b395235a7)

### How to reproduce

1. Try to ope app. 
2. App crashes.

### Version

7.1.3

### Android Version

Android 13

### Device Model

Samsung A33 5G

**Comment by xomifred** [comment]
It's opening now.

**Comment by PaulWoitaschek** [comment]
What changed? Did you update?

**Comment by xomifred** [comment]
Not sure. I tried to open today and it worked. I'm not sure whether it updated in the background. Although I can see any recent update activity in the play store. Sent from my Galaxy
-------- Original message --------From: Paul Woitaschek ***@***.***> Date: 02/07/2023  17:35  (GMT+03:00) To: PaulWoitaschek/Voice ***@***.***> Cc: xomifred ***@***.***>, State change ***@***.***> Subject: Re: [PaulWoitaschek/Voice] Can't Open App (Issue #2014) 
What changed? Did you update?
