### ISSUE TITLE
The mini player always in the notifications 

### ISSUE THREAD

**Issue by klemcijada** [PaulWoitaschek/Voice#2029]
### Overview

The mini player keeps taking space in my notifications even if I haven't used the app in ages and even after force closing it.

### How to reproduce

Not use the app for a while.
See the mini player taking up space in the notifications.
Swipe it away/go to app and close it.
After a while it's back.

### Version

8.0.0

### Android Version

33

### Device Model

FP3

**Comment by PaulWoitaschek** [comment]
Please update your app :)
