### ISSUE TITLE
Cannot start playing via Tasker.

### ISSUE THREAD

**Issue by cromulent403** [PaulWoitaschek/Voice#2067]
### Overview

This issue was previously fixed in #1913.

But it stopped working in Version 8.1.2

I cannot start playback using Tasker using either the Tasker media control or by sending an intent using Tasker.

It only works if Voice is already launched.

This was working in 7.0.14

### How to reproduce

1. With voice closed and not in notification shade.
2. Try to start voice using Tasker media control.
3. Voice does not start

### Version

8.1.2

### Android Version

Android 13

### Device Model

Pixel 5

**Comment by PaulWoitaschek** [comment]
With the linked commit you should be able to send an intent to tasker:
https://tasker.joaoapps.com/userguide/en/intents.html

* Reciever: `voice.playback.receiver.WidgetButtonReceiver`
* Action: `voice.WidgetAction`
* Extras: key: `action` value: `PlayPause`

If that works you could please send a screenshot how it looks in tasker so we can add it to the Voice FAQ?

**Comment by PaulWoitaschek** [comment]
Here you should find an APK you can use to test it:
https://github.com/PaulWoitaschek/Voice/suites/14859337809/artifacts/846233394
