### ISSUE TITLE
Title and name errors like ??? Or aeüoeoeoaoo

### ISSUE THREAD

**Issue by User1l0** [PaulWoitaschek/Voice#2085]
### Overview

I think full utf-8 support for file, title and tag names will fix this issue. This problem is always in this app no matter the version or device model. I think this is a lack of name support feature.

### How to reproduce

While having books with russian names or even sometimes in English name it couldn't show the name properly. 

### Version

8.1.3

### Android Version

12

### Device Model

.

**Comment by PaulWoitaschek** [comment]
There is full utf8 support. Your media files have probably a broken encoding. 
Could you send one to verify?
