### ISSUE TITLE
Issue with ffmpeg-kit 6.0 and release apk

### ISSUE THREAD

**Issue by tomaThomas** [PaulWoitaschek/Voice#2124]
### Overview

It's not in a released version yet, but this issue seems to be present in the current Voice master branch: https://github.com/arthenica/ffmpeg-kit/issues/825
A downgrade to ffmpeg-kit 5.1 is working

### How to reproduce

Build and install the release apk
Try to add new files that will be scanned using ffmpeg

### Version

main

### Android Version

13

### Device Model

OnePlus 6

**Comment by bro1** [comment]
Same issue with emulator for Pixel 7 API level 34.
Same resolution: downgraded to ffmpeg-kit 5.1 in libs.versions.toml

**Comment by PaulWoitaschek** [comment]
Thanks for reporting! This is already fixed upstream and the patch was merged by renovate.
