### ISSUE TITLE
Podcast titles are all the same

### ISSUE THREAD

**Issue by sigmike** [PaulWoitaschek/Voice#2171]
### Overview

Hello,
I use Voice to listen to podcasts I download. When I add a folder with all the podcast tracks it works fine but all the tracks have the same title.
Comparing these titles with `mediainfo` of the files it looks like Voice uses the "Performer" attribute as the first title, and the "Album" as the second title. It would be more relevant to use the "Track name" as second title.

### How to reproduce

- Download [this file from the 80.000 hours podcast](https://media.transistor.fm/cbcc6bbe/278552ba.mp3) into a folder
- Add the folder
- The title is the album name `80,000 Hours Podcast` whereas it should be the track name `#167 – Seren Kell on the research gaps holding back alternative proteins from mass adoption`

### Version

8.1.3

### Android Version

8

### Device Model

Galaxy A3

**Comment by PaulWoitaschek** [comment]
Closing as completed, please report if it still happens

**Comment by wrenix** [comment]
I got the same problem with 8.2.0
