### ISSUE TITLE
Can't remove book

### ISSUE THREAD

**Issue by ansible42** [PaulWoitaschek/Voice#2178]
### Overview

I have tried to remove a book from the app and I it won't let me. I have tried uninstalling and reinstalling the app to no avail. I think the book hadn't finished downloading when I added it. 

### How to reproduce

Start downloading book
Dumbly try to add book.
Now it's there forever but won't play 

### Version

8.1.3

### Android Version

34

### Device Model

Pixel 6

**Comment by rubo77** [comment]
I have the same problem in android 8 with Samsung S9+

**Comment by ansible42** [comment]
Yeah weirdly sometimes a book that worked the day before stops working. I have to reset the cache/storage space, re-download the book and add it back in. Lose my place and such. 😭
