### ISSUE TITLE
Frequently stops playing/crashes

### ISSUE THREAD

**Issue by xcy7e** [PaulWoitaschek/Voice#2333]
### The Issue
Multiple Times per hour, sometimes minutewise, Voice stops playing and closes/crashes. It just close. Right before it is stuttering. 

### Behaviour
What helps Most of the time, is having voice activeley open on screen and prevent a display turn out. As soon As the Display goes out or I hide the App, it takes an irregular amount of time until it stops. On average 5-60 sec.

### Additional information 
The App is explicitly exluded from battery Management. I tried removing Memory demanding Apps like kwgt and run Voice on the builtin launcher (OneUi) without any difference. 
_Adaptive battery usage_ is disabled.
The incident does not appear in the "Wartungsbericht" in "Akku und Gerätewartung".
The issue **most likeley disappear while charging/at night**) -> it's def. excluded from Samsungs battery managment
I have a much better Phone (S20 FE 5G) than precviously (A51) where Voice ran fine on the same setup/apps. What changed is the sdcard (prev. 500GB, now 1TB) where all the Media is stored. It's a legit SanDisk Ultra.
**No other App** (games, benchmark, Youtube, audioplayer) Shows similar behaviour. 

### What I tried
- Wiping Voice's cache
- Reinstalling the app
- Reducing amount of audiobooks to ~50
- installed memory/CPU Monitoring Apps (no peaks/abnormalities)

---

RAM: **6GB** + 6GB Swap
CPU: Snapdragon 865 2x4 cores
Memory: **1TB** SanDisk Ultra
Audiobooks: **~50-200**

---

### Suspicions
- Could it be the large SDcard?
- Could it be large images of audiobooks overloading the list rendering/RAM? (Voice works the same perf. with +200 audiobooks) (most covers are 500px²)
- Bug with the App / my device (constellation) as other Apps work

Thank you for any Tips and relevant factors, regarding your understanding of the Code.

### How to reproduce

n/a

### Version

8.2.0

### Android Version

33

### Device Model

SM-G781U

**Comment by PaulWoitaschek** [comment]
Thanks for the report. Unfortunatelly I couldn't find anything suspicious in there and no reason what actually happend 😬

**Comment by xcy7e** [comment]
Thank you Paul, for taking the time to dig into the logs. That's more I've had expected.
