### ISSUE TITLE
per-chapter author / artist

### ISSUE THREAD

**Issue by aperomsik** [PaulWoitaschek/Voice#352]
It would be nice if the artist published to Bluetooth could be taken from the current chapter instead of assuming it is the same as the first chapter's artist. My main podcast/lecture series switches lecturers every so often within the same series.

**Comment by maslic** [comment]
Yes, it would be really nice in a poetry collection... 
![27 listopadu 2015 100814 sec](https://cloud.githubusercontent.com/assets/16031968/11574654/373b11fc-9a0d-11e5-98e2-fffb907c3955.jpg)

**Comment by aperomsik** [comment]
This commit seems to do the job for me, though probably you can do something cleaner: https://github.com/aperomsik/MaterialAudiobookPlayer/commit/61e0f0a1cadf84937723a3cd2829dc6a2faf8f0b

**Comment by PaulWoitaschek** [comment]
That looks good. A few points:

* Lets stay consistent. Author or artist
* The author field on the book can now be removed as its no longer used
* A DB migration needs to be done
* The author must be added to the chapters content values, else it won't be persisted
