### ISSUE TITLE
Player starts automatically when connected to car via Bluetooth

### ISSUE THREAD

**Issue by pcondello** [PaulWoitaschek/Voice#357]
I am using a Blackberry Priv (Android 5.1.1) paired with my car (2012 Subaru Outback), and if I start my car and the radio is on FM, the phone still connects (as it should) but the audiobook app starts playing. If I don't notice, it will play in the background and I'll lose where I was in the book. My Samsung Gear Circle headphones don't do this when I turn them on, so my car must be telling the phone to start playing something when it connects.

Is there a way to prevent this app from auto-playing?

**Comment by firecat53** [comment]
This happens in my car too...but it starts whichever audio-related app I used last: Spotify, Smart Audiobook Play, MAP, etc. I can't find a function in the car stereo system to disable this, but I don't think it's an issue the apps can fix.

**Comment by sandybeachit** [comment]
Can everyone provide what OS and OS version your using, also more importantly can everyone confirm if this is happening with all apps?

If this happens with all app's and not just Material Player then its likely an Android issue rather than a material Player issue.

**Comment by PaulWoitaschek** [comment]
This seems to be fixed in 5.x
