### ISSUE TITLE
Feature request: sleep timer fade out

### ISSUE THREAD

**Issue by auduner** [PaulWoitaschek/Voice#393]
Hi and thanks for the player. I like it, but when I try to use the sleeptimer I always wake up when the sound is cut. A slow fade would be good.
Audun

**Comment by sandybeachit** [comment]
Can we close off this PR as it has been completed or am i wrong ?

**Comment by sandybeachit** [comment]
Auduner can you confirm this is working as expected and if not explain why this is not quite working how you expected ?

Thanks

**Comment by nioncode** [comment]
This is not implemented, yet.
We only have a sleep timer with shake to reset, but no slow fade out.

**Comment by mtvjr** [comment]
I'm working on implementing this.

Do you think this should be an option or always fade? Also, should the user have a setting to customize the fade time, or just keep the duration at the suggested 5 seconds?

**Comment by PaulWoitaschek** [comment]
Great to hear!

Always fading is good. And best, rewind the time when the playback stops by the fade amount.

**Comment by auduner** [comment]
Thanks!
I think a fixed fade time would be OK.

Audun

**Comment by mtvjr** [comment]
I've submitted a pull request with the sleep fade at a fixed 10-second fade with an auto rewind to the beginning of the fade.

**Comment by 1mi** [comment]
I would also like to have this feature. The fade-out time could be also set to the number of seconds for autorewind. But anyway 10 seconds I think is reasonable. Thanks.

**Comment by Thelonious08** [comment]
Voice Audiobook Player is awesome in every way. The only feature that could make it better is 10 second fade out for the sleep timer. Thanks for a great app.

**Comment by PaulWoitaschek** [comment]
Implemented as of 2c0371c1ba44b508d3d2240ea7d685fc130115da
