### ISSUE TITLE
Use Chapter metadata along with title

### ISSUE THREAD

**Issue by arktyk** [PaulWoitaschek/Voice#437]
Material player appears to be only reading the title id3 tag.   When books spread across multiple files (each with its own chapter) are read by Material Player, they appear all with the same title and are not in chapter order, making it difficult to determine the order in which they should be played.

**Comment by bagarwa** [comment]
I have books spread across say 10 mp3 files and each mp3 file has 2 chapters each. Would the player be able to distinguish the chapters?

**Comment by PaulWoitaschek** [comment]
The chapter order is determined by the file name and natural sorting.
