### ISSUE TITLE
silence removal

### ISSUE THREAD

**Issue by kiuuik** [PaulWoitaschek/Voice#489]
Some podcast apps like overcast or "pocket casts" offer to cut/skip/trim silence to increase the listening speed (besides the general playback speed adjustments). I like this feature a lot. 
On Android I have only found one audiobook player that offers this feature. It's called "Listen Audiobook Player".
Maybe there is a foss library for this out there?

**Comment by ryanwalexander** [comment]
I'd use this feature.

**Comment by FaisalFehad** [comment]
Would be great to have!

**Comment by moshpirit** [comment]
Yes please!

**Comment by rinormaloku** [comment]
This is already implemented I saw a commit with this feature.

**Comment by ryanwalexander** [comment]
I don't see any evidence of it being implemented in the app. If it is
please tell me how to use it.

**Comment by rinormaloku** [comment]
@ryanwalexander still no release, am waiting as well, the implementation: https://github.com/PaulWoitaschek/Voice/pull/730

**Comment by moshpirit** [comment]
Thank you for replying! How long do you think it will take for us to get the next release?

cc/ @PaulWoitaschek

**Comment by PaulWoitaschek** [comment]
I just became a father of another child so it's probably a few months till I find the time...

I created a milestone with some issues, so once they are done we can release!
https://github.com/PaulWoitaschek/Voice/milestone/6

**Comment by deoren** [comment]
@PaulWoitaschek Congrats on the new kiddo! 

Regarding the app itself, many thanks for developing it. I use it often and look forward to each new release.

**Comment by moshpirit** [comment]
@PaulWoitaschek Congratulations! Hope everything is fine :) 

Sure, no problem! Thanks for all your hard work!

**Comment by PaulWoitaschek** [comment]
Thanks :) If someone would tacke the issues I would find time to review and release them.

**Comment by moshpirit** [comment]
I'm not a developer but if I can help in any way...
