### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/Voice#522]
The name of this player used to be nothing than a work title. So it's time to find a real name.

Post your suggestions!

**Comment by yetanothernerdk** [comment]
Audiobook Player.

**Comment by alfred300p** [comment]
How about [Elocution](https://en.wikipedia.org/wiki/Elocution)?

**Comment by zach-adams** [comment]
[Aural](https://www.merriam-webster.com/dictionary/aural)?

**Comment by deveshp** [comment]
Vaani Audiobook Player

Vaani is sanskrit for voice.

**Comment by sp4rkie** [comment]
kissplay / kiss player 

as  one of the main goals is to keep the player  stupid simple. There is an Android launcher called 'kiss launcher'. Just the way I like it:-)

**Comment by ImJustLearning** [comment]
el·o·quent
ˈeləkwənt
adjective
fluent or persuasive in speaking or writing.
"an eloquent speech"
synonyms:	fluent, articulate, expressive, silver-tongued; More
clearly expressing or indicating something.
"the touches of fatherliness are eloquent of the real man"
synonyms:	expressive, meaningful, suggestive, revealing, telling, significant, indicative
"her glance was more eloquent than words"

**Comment by shkp** [comment]
Recital.

Because every audiobook is kind of a performance in your ears.

**Comment by sandybeachit** [comment]
Do we really need a name change? Everyone knows the app as it is now, what do we benefit from a name change? I quite like it how it is.

**Comment by curreta** [comment]
Kesho Audiobooks

Means `tomorrow` in Swahili

**Comment by MPadgett** [comment]
Pages

**Comment by Flos** [comment]
"Booki"
The name should be short and easy to speak. "Play xx with Booki". "Resume Booki", "Continue Booki".

**Comment by cyreb7** [comment]
Autobook

I agree with Flos that the name should be easy to say with voice commands. But the name should also indicate the simplicity of the app.

**Comment by imuli** [comment]
I'd advise away from names that imply this is only for audiobooks. I use it for pretty much everything where I want to keep my place between playings or the order matters. So, books, podcasts, some music, language lessons, stories I've recorded for my kid… I like the current name - even if not for the proper etymology. If it's changed maybe something to convey persistance?

**Comment by dbdeveloper** [comment]
fabulist

**Comment by sandybeachit** [comment]
I think the only issue of changing the name of this app to something more generic to advise people to use it for podcasts etc which it will work i am sure but i only use it for audiobooks is has there been full and proper testing?

Im not doubting this project or code quality as the author and devs are awesome but any change and advertising change could cause a flood of bugs which were never an issue as the app was never trying to be a podcast / music player etc.

Perhaps best to test it doing all these other features if there is a bug found report it otherwise for the moment i would shy away from renaming to something more generic, stay as we are.

I would say quality over quantity any day.

**Comment by 0rAX0** [comment]
I better name and a new shiny icon would be quite awesome, I may even contribute the icon if needs  be. :)

**Comment by FaisalFehad** [comment]
Slim Audiobook Player 
Pocket Audiobook Player
Elemental Audiobook Player

**Comment by PaulWoitaschek** [comment]
Thanks for all the suggestions.

Voice 

that's the name :)
@0rAX0 Can you make a draft for an icon? It's got to be something minimal, that also works on a circle, on a square and rectangle.
-> https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by 0rAX0** [comment]
@PaulWoitaschek Sweet! Any particularities you have on mind for it?

**Comment by PaulWoitaschek** [comment]
First thing that came to my mind is using the shape of the **V** of voice as as a book shape.

But I'm really open to quite anything, I like the icons in your portfolio.
Also check out https://material.io/guidelines/style/icons.html#icons-product-icons

**Comment by 0rAX0** [comment]
@PaulWoitaschek Great, I was thinking the same thing. I'll be back shortly :)

**Comment by PaulWoitaschek** [comment]
@0rAX0 
How is it going? I really can't wait. :)

Also not that I changed the color primary to
#01579b
and the dark one to
#002f6c

**Comment by 0rAX0** [comment]
@PaulWoitaschek First draft.

![voice_1](https://user-images.githubusercontent.com/1044370/29673636-bfafc698-88e7-11e7-96e1-c25286933552.png)

**Comment by 0rAX0** [comment]
![voice2](https://user-images.githubusercontent.com/1044370/29673831-44da33bc-88e8-11e7-938d-d96fa0cad771.png)

**Comment by 0rAX0** [comment]
![voice2](https://user-images.githubusercontent.com/1044370/29673899-7469b378-88e8-11e7-8214-6aad344d9647.png)

**Comment by PaulWoitaschek** [comment]
![screenshot_20170824-175656](https://user-images.githubusercontent.com/743462/29675826-9eeec4f4-88f6-11e7-963a-aa09359c90ac.png)
![screenshot_20170824-175721](https://user-images.githubusercontent.com/743462/29675827-9ef62a6e-88f6-11e7-8d42-b6694da6fc92.png)

**Comment by PaulWoitaschek** [comment]
I really like both!

(with a slight preference to the blue one because it works better on light backgrounds.)

What about making the shadow darker?
We also need a notification icon, you can use 
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit
for that.

**Comment by 0rAX0** [comment]
Nice! They still need tweaking and I'll try what you suggested. Also, if you're not in a hurry I'd wait for it to mature a bit as well as other ideas and iterations before committing. :)

**Comment by PaulWoitaschek** [comment]
Hm, forget about making the shadow darker, that was only related to the white one.

**Comment by 0rAX0** [comment]
Oh, I did make the shadow darker in the white one but it looked bad. :\

**Comment by PaulWoitaschek** [comment]
> Nice! They still need tweaking and I'll try what you suggested. Also, if you're not in a hurry I'd wait for it to mature a bit as well as other ideas and iterations before committing. :)

How is it going? I'd like to do the rebranding soon. 

So to summarize what kind of assets we need:
* The icon itself (ideally in svg), or in a very high res png quality, as a all-in-one icon **and** as split layers (foreground & background) for adaptive icons: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
* The Status-bar icon in white,
 in a large size (https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html)

**Comment by 0rAX0** [comment]
Oh I'm so sorry @PaulWoitaschek I was out for a while. I'll prepare you the SVG and send it to ASAP.

**Comment by PaulWoitaschek** [comment]
Sorry to bother you again @0rAX0, but *ping* *ping*

**Comment by 0rAX0** [comment]
Haha, no worries. Here's the Adaptive icon (PNG): [Voice - Adaptive.zip](https://github.com/PaulWoitaschek/Voice/files/1267943/Voice.-.Adaptive.zip)

Please test. Rest coming shortly..

**Comment by 0rAX0** [comment]
Round Icon (PNG) [Voice_icon.png.zip](https://github.com/PaulWoitaschek/Voice/files/1267966/Voice_icon.png.zip)

**Comment by 0rAX0** [comment]
You might also find this version (On Figma) better: https://www.figma.com/file/KhsQ1hFgiCqLpvkjkk76SAIJ/Voice-Icon

**Comment by DreierF** [comment]
@0rAX0 @PaulWoitaschek What do you think about moving the white wave to the background to get a nice effect when parallax effect is applied on the layers?

**Comment by PaulWoitaschek** [comment]
@dreierf what do you mean by that?

I actually find the first draft the best in it's simplicity.

**Comment by DreierF** [comment]
It's hard to explain 😅 
@0rAX0 Could you please upload the svg or illustrator version of the icon?
Then I'll make a gif tomorrow illustrating what I meant 😉

**Comment by DreierF** [comment]
I have to admit the effect is not as big as I thought, but here you can see what I meant. the foreground wave and "background wave" behave slightly different.

![ezgif-3-a6e2715bac](https://user-images.githubusercontent.com/5631865/29969854-6291ec2a-8f22-11e7-8734-0f6c73f3604e.gif)

Here are the resources I used:
[both-in-foreground.zip](https://github.com/PaulWoitaschek/Voice/files/1270200/both-in-foreground.zip)
[wave-in-background.zip](https://github.com/PaulWoitaschek/Voice/files/1270201/wave-in-background.zip)

**Comment by PaulWoitaschek** [comment]
Ah that's nice. Can  you make that with the original wave form? And I can't see it properly in the gif: Does the background scroll synchronously?

**Comment by DreierF** [comment]
No the background does not scroll synchronously, but slower than the foreground, but all that is dependant on the launcher that is used (I used [Nick Butcher's Adaptive Icon Playground](https://github.com/nickbutcher/AdaptiveIconPlayground))
And you can of course apply the same effect to @0rAX0's icon, but I don't have the original svg and can't build it from the png 😉

**Comment by DreierF** [comment]
Ah, good to know. I'll try to rebuild your icon as vector graphic in the meantime 😉

**Comment by 0rAX0** [comment]
@DreierF I have it in Figma if you have an account. I can make it editable for you?

**Comment by DreierF** [comment]
Don't have an account. Can you export an svg form figma?

**Comment by 0rAX0** [comment]
Scratch that, I was able to export the SVG after disabling every drop shadow, here's the exact shape I'm using on the icon, this only contains the basic elements with no effects, but I'm sure you can do without until I finish remaking the final. 😉
 
[Voice-source-basic.svg.zip](https://github.com/PaulWoitaschek/Voice/files/1270560/Voice-source-basic.svg.zip)

**Comment by DreierF** [comment]
Perfect 🙂!

**Comment by DreierF** [comment]
Ah, but that's not the one from the first draft.
@PaulWoitaschek  should decide which one should make it into the final version.
I'd prefer the waveform of @0rAX0's first draft

**Comment by 0rAX0** [comment]
Hmm, I think it is, I only increased the stroke size and changed the colors!

**Comment by DreierF** [comment]
<img width="447" alt="screen shot 2017-09-01 at 16 48 10" src="https://user-images.githubusercontent.com/5631865/29975080-6c16f138-8f35-11e7-88d2-3da22d2a0a46.png">
The black waves are from the first draft vs. the white and blue/white ones from the current 🤔

**Comment by 0rAX0** [comment]
Maybe you're talking about this one?

[Voice_old_waves.svg.zip](https://github.com/PaulWoitaschek/Voice/files/1270622/Voice_old_waves.svg.zip)

**Comment by 0rAX0** [comment]
I made them taller so the V is more evident, as opposed to the shorter ones which could be lost on some people.

**Comment by DreierF** [comment]
💡Ahh. Totally forgot that the waves should also symbolize **V**oice.

My question regarding which waveform to use originates from Paul saying: 
> I actually find the first draft the best in it's simplicity.

And as I said I would also prefer the "old" version.

**Comment by 0rAX0** [comment]
I can totally revert back to the old waveform if you don't think that it downplays the V, also, Paul might have been talking about the overall look and feel not the actual drawing of the waves.

In the meanwhile, I took the liberty to explore some other styles and colors (I think the current colors are a little too dark). Anyways, just a proposal on the side I'm toying with, while we wait for Paul: 

![voice-icon alt](https://user-images.githubusercontent.com/1044370/29976152-fa1e398c-8f30-11e7-8b52-ea77db123bed.png)

**Comment by DreierF** [comment]
Really nice work 👍
But unfortunately does not play well with adaptive icon sizes.

**Comment by 0rAX0** [comment]
Yeah 😩

**Comment by 0rAX0** [comment]
Additional one, with a fill:

![voice icon fill_alt](https://user-images.githubusercontent.com/1044370/29985989-65407fd6-8f59-11e7-8ccb-a9ab79f74f5a.png)

**Comment by 0rAX0** [comment]
v2: 

![voice icon fill_alt2](https://user-images.githubusercontent.com/1044370/29986053-a93c0836-8f59-11e7-958b-51bd5b1215a8.png)

**Comment by PaulWoitaschek** [comment]
I think the very first icon just matches perfectly to the core concept of the player.

**Comment by 0rAX0** [comment]
Here's the original: 

![voice icon original](https://user-images.githubusercontent.com/1044370/29995162-d75ad144-8fda-11e7-9cff-d46591116723.png)

**Comment by PaulWoitaschek** [comment]
And split in layers for adaptive icons? As svg?

**Comment by DreierF** [comment]
Here are the android vector resources 😉
[vector-final.zip](https://github.com/PaulWoitaschek/Voice/files/1272128/vector-final.zip)

**Comment by 0rAX0** [comment]
Adaptive: 

[Voice-Original-adaptive.zip](https://github.com/PaulWoitaschek/Voice/files/1272129/Voice-Original-adaptive.zip)

**Comment by 0rAX0** [comment]
Thanks @DreierF

**Comment by PaulWoitaschek** [comment]
Nice! And for the notification?

**Comment by 0rAX0** [comment]
@PaulWoitaschek shortly :)

**Comment by 0rAX0** [comment]
Test this: 
![voice-notification](https://user-images.githubusercontent.com/1044370/29995586-fde0c18e-8fe4-11e7-8c77-e358eaab1b2f.png)

**Comment by 0rAX0** [comment]
SVG: 

[voice-notification.svg.zip](https://github.com/PaulWoitaschek/Voice/files/1272167/voice-notification.svg.zip)

**Comment by PaulWoitaschek** [comment]
Thanks. I'm not sure how to handle the background properly. Now it's by default square. I can't seem to set it to circle and other launchers present it as square shape.

**Comment by DreierF** [comment]
At the moment only a few support setting it. Systemwide this setting is atm only available for Pixel phones.
https://www.reddit.com/r/nexus5x/comments/6vs92r/launchers_that_let_you_change_adaptive_icon_shape/

**Comment by 0rAX0** [comment]
Yes, Adaptive icons aren't yet supported widely. Not sure if you can have a fallback icon when they're not supported.

**Comment by DreierF** [comment]
You can have a fallback!

**Comment by 0rAX0** [comment]
Problem solved then?

**Comment by PaulWoitaschek** [comment]
Where did you read about the fallback?

Where did you see the parallax effect?

**Comment by DreierF** [comment]
The adaptive icon is placed in res/mipmap-anydpi/ic_launcher.xml
mipmap-anydpi is only triggered on API 26 and higher. For all other devices res/mipmap-xxxhdpi/ic_launcher.png and similar are used.

To see the parallax effect I used [Nick Butcher's Adaptive Icon Playground](https://github.com/nickbutcher/AdaptiveIconPlayground) as I said before 😉

**Comment by PaulWoitaschek** [comment]
Hmm I thought of a fallback as in unspecified. 

Actually the default on my Nexus is square. Can you make a modification of the icon where the wave has a higher amplitude?
Then we could use that one as the default and the original for circle shape.

**Comment by PaulWoitaschek** [comment]
So we'd need that as a vector.

**Comment by 0rAX0** [comment]
Test these: 

[Fallback.zip](https://github.com/PaulWoitaschek/Voice/files/1272959/Fallback.zip)

**Comment by PaulWoitaschek** [comment]
The icon is broken and I get several warnings:

<img width="272" alt="bildschirmfoto 2017-09-03 um 21 04 09" src="https://user-images.githubusercontent.com/743462/30005834-7a50def0-90eb-11e7-9157-3c6e8873bb18.png">


Warning #1: | found clip-path(s) attribute which is not fully supported yet (try enabling support for clip-path below)
-- | --
Warning #2: | transforms on path are not supported, use option Bake transforms into path

<img width="272" alt="bildschirmfoto 2017-09-03 um 21 04 09" src="https://user-images.githubusercontent.com/743462/30005833-74d900ba-90eb-11e7-9fa6-c4b885329b78.png">

**Comment by PaulWoitaschek** [comment]
Can you create that fallback adaptive too?

**Comment by 0rAX0** [comment]
The icon isn't broken, it's just using clip-path which isn't supported in whatever you're using, what happens when you "try enabling support for clip-path below"?

**Comment by PaulWoitaschek** [comment]
I'm not saying that your icon is broken but that the converted android icon is broken.

"try enabling support for clip-path below" produces the icon I posted. Without that it's just a white square.

**Comment by 0rAX0** [comment]
I see. I'll bake in the changes then and remove the masks.

**Comment by 0rAX0** [comment]
Hey, Test this SVG:

[Voice Icon (Fallback).svg.zip](https://github.com/PaulWoitaschek/Voice/files/1277726/Voice.Icon.Fallback.svg.zip)

**Comment by 0rAX0** [comment]
As soon as you confirm that it's working I'll do the Adaptive using it.

**Comment by PaulWoitaschek** [comment]
<img width="187" alt="bildschirmfoto 2017-09-05 um 16 34 14" src="https://user-images.githubusercontent.com/743462/30066430-2c2adf28-9258-11e7-9770-34d818906076.png">

Unfortunately not.

Btw, this is the tool that spits out the warnings:
https://inloop.github.io/svg2android/

**Comment by 0rAX0** [comment]
Haha, At least we have all the elements inside the circle :D 

Hmm, is it the only tool? 

<img width="489" alt="screen shot 2017-09-05 at 15 40 17" src="https://user-images.githubusercontent.com/1044370/30066715-97b82780-9250-11e7-8267-78d56bd27f10.png">

**Comment by 0rAX0** [comment]
I'll try an Inkscape plugin that claims to do the same thing and report back: https://inkscape.org/en/~owenfromcanada/%E2%98%85androidvector

**Comment by PaulWoitaschek** [comment]
Yeah, it's definately progress ;)

Android only supports a subset of svg as it's a huge standard and android is quite memory constraint.

**Comment by 0rAX0** [comment]
This is using the extension: 

[Voice Icon XML.xml.zip](https://github.com/PaulWoitaschek/Voice/files/1277793/Voice.Icon.XML.xml.zip)

**Comment by PaulWoitaschek** [comment]
That's just white. Also it just contains a single path and a few empty groups.

**Comment by 0rAX0** [comment]
So the extension is broken. :\

**Comment by PaulWoitaschek** [comment]
Then lets just skip the svg stuff and just use adaptive png icons instead.

**Comment by PaulWoitaschek** [comment]
Way too much pain :D

**Comment by 0rAX0** [comment]
haha, let me try this first: 

https://github.com/inloop/svg2android/issues/82

**Comment by DreierF** [comment]
Try this one:
[voice_icon__fallback_.xml.zip](https://github.com/PaulWoitaschek/Voice/files/1277870/voice_icon__fallback_.xml.zip)

**Comment by PaulWoitaschek** [comment]
That works! What did you do?

**Comment by 0rAX0** [comment]
@DreierF TELL US!!!

**Comment by DreierF** [comment]
I used Illustrator to bake the matrix transformations and clip paths into the svg. Inkscape unfortunately seems to excessively use non-standard or very advanced (not really sure) svg features even if it could be saved way easier. (Just have a look at the svg content 🙈).
And then converted it with [https://inloop.github.io/svg2android/](https://inloop.github.io/svg2android/) 😎

**Comment by 0rAX0** [comment]
Cool, Illustrator is the least software I'm comfortable working with. 😓 

Also, in Inkscape, there are two SVG types you can save to: an Inkscape SVG, and a "plain" SVG, you can toggle that just before you save in the "Save As" dialog. The plain version contains far less Inkscape mess.

**Comment by 0rAX0** [comment]
Oh, and @DreierF could you please do the same thing with an Adaptive version as well? :)

**Comment by DreierF** [comment]
Sure 🙂 
Just send me the files.

**Comment by 0rAX0** [comment]
Here, Both the background and the foreground are their own SVGs: 

[Adaptive - Fallback.zip](https://github.com/PaulWoitaschek/Voice/files/1278040/Adaptive.-.Fallback.zip)

**Comment by DreierF** [comment]
Here's the [foreground.xml](https://github.com/PaulWoitaschek/Voice/files/1278180/foreground.xml.zip). Hope it works, because the aspect ratio was wrong. Changed it back to 192x192, but please check if the y position is correct. The background can be set to the color value #003B7F just as a simple <color> entry in values.xml or similar.

**Comment by PaulWoitaschek** [comment]
So we're getting close. I only need the round icon non adaptive in a large png size. The one posted above has no transparency but is white.

**Comment by PaulWoitaschek** [comment]
And I'm not sure about the notification icon. It looks a little too thin to me.

![screenshot_20170905-205241](https://user-images.githubusercontent.com/743462/30077506-59231134-927c-11e7-900d-cc8f9300da87.png)

**Comment by 0rAX0** [comment]
Oops, I had the Artboard's bg turned on :P Here's a transparent @4x icon, if you need a specific size do tell me: 

![voice icon fallback 4x](https://user-images.githubusercontent.com/1044370/30081112-df0cca32-927d-11e7-9dbb-10626c0e1949.png)

And yeah, the notification icon does need tweaking. On it.

**Comment by 0rAX0** [comment]
Take a look at this: 

[Voice-notification-improved.zip](https://github.com/PaulWoitaschek/Voice/files/1282620/Voice-notification-improved.zip)

**Comment by DreierF** [comment]
Oh, yeah the artboard was not sized for adaptive icons. Here a repositioned version:
[foreground-improved.xml.zip](https://github.com/PaulWoitaschek/Voice/files/1286960/foreground-improved.xml.zip)

**Comment by PaulWoitaschek** [comment]
Can you upload the adaptive icon as a regular png in a large size?
With the latest vector drawable you can really see the pixels (ignore the false color). It's just really not worth all the trouble ;)

![screenshot_20170908-211129](https://user-images.githubusercontent.com/743462/30227557-671e6c92-94da-11e7-8c70-b80a23e490ff.png)

**Comment by PaulWoitaschek** [comment]
And the whole wave and shadow have to be way larger to make sure they exceed the borders.
Like in the screen the round icon has the waves exceeding the bounds but the shadow of the square one does not touch te bottom.

![bildschirmfoto vom 2017-09-08 21-31-43](https://user-images.githubusercontent.com/743462/30228107-99751a4a-94dc-11e7-970f-039a165dbb77.png)

**Comment by DreierF** [comment]
😲 OMG this looks really crappy. I'll take a look at it tomorrow and either fix it or create a PNG version. The problem is, I already tried to use PNG for adaptive icons on another project and had serious problems with half transparent background (for the wave shadow).

**Comment by DreierF** [comment]
I just used the svg provided by @0rAX0 😉

**Comment by DreierF** [comment]
This should finally work!
[voice-adaptive-icon.zip](https://github.com/PaulWoitaschek/Voice/files/1289975/voice-adaptive-icon.zip)
I also compiled and tested it on the device and I don't see any pixels.
![screenshot_20170909-194730](https://user-images.githubusercontent.com/5631865/30242518-2a69a4d8-9598-11e7-8294-ea50df35fca0.png)

**Comment by PaulWoitaschek** [comment]
And it works with all shapes?

**Comment by DreierF** [comment]
![all](https://user-images.githubusercontent.com/5631865/30242665-d74ed2fc-959a-11e7-83f2-f0ee5a2dc1c5.png)

**Comment by PaulWoitaschek** [comment]
Nice. The previous version had extremely long paths (2000 chars+). I think that caused the pixelation.

**Comment by DreierF** [comment]
May well be. I've completely redrawn the icon :wink:

**Comment by 0rAX0** [comment]
Great job!

(Note that the fallback version actually has short paths)

**Comment by PaulWoitaschek** [comment]
Thanks a lot for your help!

https://github.com/PaulWoitaschek/Voice/releases/tag/v3.5.0

**Comment by 0rAX0** [comment]
Yay! 👏👏

**Comment by PaulWoitaschek** [comment]
@0rAX0 Can you create a new promo image? That's the one on the top when opening the play store.

It has to be 1024x500. The current one is here: https://github.com/PaulWoitaschek/Voice/blob/master/Images/Promo%20Header/material%20player.png

But feel free to design something new.

**Comment by 0rAX0** [comment]
On it

**Comment by 0rAX0** [comment]
@PaulWoitaschek Is it OK to use audio books' covers? Or are they copyrighted?

**Comment by PaulWoitaschek** [comment]
Nope, we can't take copyrighted covers, the app will get suspended immediately.

The covers here are all CC:
https://github.com/PaulWoitaschek/Voice/tree/master/Images/Example%20Covers

You can search on flickr or sites alike for CC licensed pictures and use them. 
Also it was helpful to use "print" the page to a pdf and send that when the google license team comes for us again ;)

https://github.com/PaulWoitaschek/Voice/tree/master/Images/Example%20Covers/Dream%20in%20a%20boat

**Comment by 0rAX0** [comment]
Hmm, the CC ones from Google and Flickr suck. :\ :'(

**Comment by 0rAX0** [comment]
I guess that if we can't use good album art we might have to do without. 

![promo](https://user-images.githubusercontent.com/1044370/30491918-bcf2dd54-9a36-11e7-8214-f353e6cb672f.png)

**Comment by PaulWoitaschek** [comment]
I think the text should be aligned to the bottom third because else it will be cut in the play store page. (Just view the current one from your device.)

**Comment by 0rAX0** [comment]
This should work: 


![promo](https://user-images.githubusercontent.com/1044370/30499040-df6c08fa-9a50-11e7-96db-c5598af952c8.jpg)

**Comment by PaulWoitaschek** [comment]
Merci !

**Comment by PaulWoitaschek** [comment]
Ha, one last request: Can you change "An audiobook player" to "for audiobooks?
Also could you upload the source so we can put it in git?

**Comment by 0rAX0** [comment]
You're welcome :)

Here it is: 

Is it okay if the source was a .fig (Figma)? 

![promo](https://user-images.githubusercontent.com/1044370/30503483-5552a996-9a62-11e7-9e60-db82dd521781.jpg)

**Comment by PaulWoitaschek** [comment]
Thanks!
Is it possible to convert it to a non proprietary format?

**Comment by 0rAX0** [comment]
There are two possibilities: 

1- Share with you a link to the work, since Figma is also an online editor and anyone can collaborate there.
2- Send and SVG but either lose the edits or flatten the BG.

**Comment by 0rAX0** [comment]
@PaulWoitaschek Landscape mode: 

![screenshot_20170916-120325](https://user-images.githubusercontent.com/1044370/30516245-5aad45a2-9b31-11e7-806f-85b75e39aa1a.png)

**Comment by Flos** [comment]
It's now a bit late, but the name "Voice" does not work well with ok google for me. (German) 

If I say "OK, google starte voice" => my phone starts to call my "mailbox".
If I say "OK, google öffne voice" => my phone starts to call my "mailbox". 

I'm now unable to open the voice player with my "voice", it's somehow ironic :-(
