### ISSUE TITLE
[Feature request] Progress bar on grid view

### ISSUE THREAD

**Issue by philipobenito** [PaulWoitaschek/Voice#529]
The grid view is the most visually pleasing but I find myself using the listing instead so I can see the progress bar, how difficult would it be to add a progress bar to the bottom of each item in the grid? No need for any text or anything, just the bar.

**Comment by sandybeachit** [comment]
This would be useful but also it would make the design more consistent with the line by line view.

That is so that both views display the information, just one is line by line and the other grid based.

**Comment by PaulWoitaschek** [comment]
This is implemented in 5.x
