### ISSUE TITLE
Playback stops from time to time because of a Webbrowser Loading images

### ISSUE THREAD

**Issue by Flos** [PaulWoitaschek/Voice#541]
For me (Samsung Galaxy Note 3 with Stock Android 5.0.1)

The Audiobook Player stops from time to time. Its not crashing or so, it just stops the playback (Pause?). Today that happend within 20 Minutes 10x, I was listening to a Audiobook on a Bluetooth Speaker, while I used Firefox and Chrome to browse through some image galleries. It seems somehow related to the image loading in the Browser. Sometimes when a image loads, the playback stop. 

Any ideas?

**Comment by PaulWoitaschek** [comment]
Is that sitll happening with the latest version?
