### ISSUE TITLE
do some more to get priority among others

### ISSUE THREAD

**Issue by treakiandroid** [PaulWoitaschek/Voice#559]
first of all this is from all the bad unsatisfying ways to play audio books on android that one that works somehow. But the playback is still much to often broken down id if there is something i dont see.on the positive site at least it is always able to remember the position but it is anoying to. sometimes also when i want to scroll trough the bool using Bluetooth audio device buttons it results in a complete silence witch forces me to take out my phone ;(

so it would be very grate if you could do something to get more priority and test the app against all possible day situations like other apps running in background and so and do something about it. i guess running two services that check each other, and restart each other if one get killed while doing something to get priority (showing notification while that or so) like it is done with servers with tools with heartbeats (of cause here should it be done using some interrupts that the threads get when the outher thread is gone) couls help.

thanks a lot in advance

**Comment by PaulWoitaschek** [comment]
I assume that this is fixed in the latest versions as this issue is ancient.
