### ISSUE TITLE
translation wrong

### ISSUE THREAD

**Issue by treakiandroid** [PaulWoitaschek/Voice#560]
it lookes like if there is a translation problem in the german version. please for the future review everything at least once by a native (or very near to native) speaker before putting it live if you and let it confuse everyone. Also you don't have an per app setting for language so i had to change my whole system language to check...

so the term
Einschlaftimer
which is used by you, means
switch-on-timer

but the thing is doing the complete opposite so it schould be called

Ausschalttimer

wich would mean

switch-off-timer

even better maybe would be to call the function

Wiedergabe pausieren nach...

which means

pause playback after...

which would rule out any possible misunderstandings.

thanks for this fix in advance

**Comment by PaulWoitaschek** [comment]
I am a native german speaker. ;)

Einschlaftimer, is made out of two words: "Einschlafen", which means going to sleep, and Timer (english one.

You're `switch-on-timer` would translate to Ein**schalt**timer.

I guess the other points are outdated due to the change to the Einschlaftimer.
