### ISSUE TITLE
Certain characters in filenames make files unplayable

### ISSUE THREAD

**Issue by darrenboyd** [PaulWoitaschek/Voice#561]
After the latest update (3.1.0-RC4), several buttons are no longer working.

The _Previous Chapter_, _Skip Back_, _Play_ buttons don't do anything at all.

The _Skip Forward_ button does the same thing the as the _Next Chapter_ button.

All of the buttons appear to work (as in their animation is visible). The time slider works fine (or it appears to, as I can't actually get anything to play), and the select chapter drop down also appears to work fine.

**Comment by PaulWoitaschek** [comment]
Very weird. Which phone & Android Version are you using? Is this the case for all books?

**Comment by darrenboyd** [comment]
I am on a Nexus 5x, Android 7.1.2 (security patch level January 5, 2017).

I only have one book, but I'll track down another one and test it.

**Comment by darrenboyd** [comment]
Did some more debugging on this. I had a folder, with 5 folders in it, each of those contained many mp3s. I moved one of the folders to the top level, so that app saw it as it's own book. The mp3 files still wouldn't play. So, it doesn't appear to be an issue with the directory structure.

Here is some information about the actual files.


```
# This is one of the files that doesn't work
$ file Disc\ 1\ -\ 01\ -\ Introduction.mp3 
Disc 1 - 01 - Introduction.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1,  48 kbps, 44.1 kHz, JntStereo

# This is one of the files that *does* work
$ file ../Alice\ in\ Wonderland/aliceinwonderland_00_carroll_64kb.mp3 
../Alice in Wonderland/aliceinwonderland_00_carroll_64kb.mp3: Audio file with ID3 version 2.3.0, contains: MPEG ADTS, layer III, v2,  64 kbps, 22.05 kHz, Monaural
```

I tried re-encoding the file that doesn't work, as well as removing all filename characters that might be suspect, but it still will not play...

```
$ file disc1_introduction.mp3 
disc1_introduction.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1,  64 kbps, 44.1 kHz, Stereo
```

**Comment by darrenboyd** [comment]
Finally figured out what was causing the issue. Several of the directories in the book that had issues used the colon ":" character in their name. Once I removed the colon from the directory names, the files were playable again.

I also found that unicode quotes (I.e., the '“' and '”' characters ... hoping the web doesn't change them as I broadcast those characters around the world) stopped files from playing as well.

If these files really aren't playable, that's fine, but maybe they shouldn't show up in the list of files that are playable?

Thanks!

**Comment by PaulWoitaschek** [comment]
Can you describe the exact setup that does not work for you?
I created a sample file with dots and it works:

`/storage/emulated/0/Download/1.15.134.15/01.1.15.124.mp3`

**Comment by darrenboyd** [comment]
Ugh, so, I just _upgraded_ to the Android O beta, and USB connectivity is currently buggy on it, so I can't replicate it at the moment.

My best recollection is a path like `Book 1/Chapter 1/Book 1: Chapter 1: “chapter name”.mp3`

**Comment by rainerh-ffm** [comment]
I had similar problems with files with german umlauts in filename (and a hash ("#") too). After renaming (elimininated all non-7-bit-chars) the files could be played.

**Comment by PaulWoitaschek** [comment]
I belive this is fixed on 6.x
