### ISSUE TITLE
Overlapping Text in in Settings View when using German

### ISSUE THREAD

**Issue by ThaSiouL** [PaulWoitaschek/Voice#574]
As seen in the Screenshot the height of the Setting Items will not be changed when a translation needs more than one row of text. This lets the description overlap with the Item and makes both very hard to read.

 
![screenshot_20170415-111829](https://cloud.githubusercontent.com/assets/7595965/25062511/9ee1512e-21cd-11e7-8b04-f707172364d6.png)

**Comment by PaulWoitaschek** [comment]
Which version of the app are you using? Which phone are you using? Which Android Version are you using?

**Comment by ThaSiouL** [comment]
Sorry: This is today's beta version (but i have seen it on the previous version as well) on a OP3T, latest available 7.1.1 update (and 480 dpi on a 1080p screen)

**Comment by PaulWoitaschek** [comment]
Thanks. I reported the issue [upstream](https://issuetracker.google.com/issues/37399580). It's quite rare that his happens but I could reproduce it.

**Comment by artem-p** [comment]
Same thing with Russian

![screenshot_20170522-163308](https://cloud.githubusercontent.com/assets/1714477/26311314/921c85a6-3f0c-11e7-8143-8161c6bbbd45.png)

**Comment by PaulWoitaschek** [comment]
This will be fixed with the upcoming version. Thanks for reporting :)
