### ISSUE TITLE
Starts playback on phone reboot and loses playback position

### ISSUE THREAD

**Issue by wvaughan** [PaulWoitaschek/Voice#575]
Whenever I reboot my device, the app launches in the background and starts playing. It seems to skip around, however, so that when I resume the app after restart my playback position is lost.

**Comment by PaulWoitaschek** [comment]
Please include some details:
* App version
* Phone
* Android version

**Comment by wvaughan** [comment]
App Version: 3.2.0
Phone: Google Pixel
Android version: 7.1.2

**Comment by PaulWoitaschek** [comment]
That's almost impossible. Are you using any custom firmware? Do you use a widget?

**Comment by wvaughan** [comment]
No custom firmware and the only widget I have is for weather timeline.

I noticed a play store review that mentioned the same issue.

**Comment by nioncode** [comment]
The same thing happened to me multiple times in the past. I don't know about the seeking, but my phone started to play my audio books on speakers a couple of times when I ran out of battery.

**Comment by PaulWoitaschek** [comment]
Wait do you mean while powering off or after boot?

**Comment by nioncode** [comment]
For me it regularly happened when the phone battery was so low that it shut
down automatically.
As soon as the 'powering down' window of the OS got displayed, Material
Player started to play on speakers.

So it happened during shutdown, not after boot.

>

**Comment by PaulWoitaschek** [comment]
And was it in the notification area at that time?

**Comment by nioncode** [comment]
Can't remember, sorry.

**Comment by wvaughan** [comment]
Same behavior for me although I'm also not sure if the notification was active. I had the issue happen on both forced-restart as well as manual restart.

**Comment by PaulWoitaschek** [comment]
And is it reproducible? What is the difference between these reboot modes? How do you trigger them? Do you have headsets connected? And is it just that second while powering off?

**Comment by wvaughan** [comment]
- And is it reproducible? Yes

- What is the difference between these reboot modes? The phone automatically shuts off with low battery. Otherwise you can hold the power button and press "reboot".

- Do you have headsets connected? No

- And is it just that second while powering off? As nioncode described - 

> As soon as the 'powering down' window of the OS got displayed, Material
Player started to play on speakers.

**Comment by PaulWoitaschek** [comment]
This should be fixed in 5.x
