### ISSUE TITLE
Not finding all books in nested folders

### ISSUE THREAD

**Issue by jameswmills** [PaulWoitaschek/Voice#613]
App-Version: 3.3.6.2
Phone Name: Nexus 6
Android Version: 7.1.2

Beautiful app, thanks very much!  Having a small problem with locating nested books.  My Audiobooks folder structure looks like this:

Audiobooks
  - Author
    - book
  - Author
    - book
  - Author
    - book
    - book
    - book

When I add the "Audiobooks" folder in Material Player, I only see a single book per author, instead of 1 book for two authors and three books for the third author.

Any help is appreciated, and thanks again!
~james

**Comment by PaulWoitaschek** [comment]
#809
