### ISSUE TITLE
Use "auto rewind" setting when book audio is interrupted by other apps

### ISSUE THREAD

**Issue by wberrier** [PaulWoitaschek/Voice#618]
App-Version: 3.3.6.2
Phone Name: RW 1st Gen Moto X
Android Version: 5.1

Use case: listening to audiobook in car with bluetooth while google maps is giving directions

The book will pause while google maps gives directions, but sometimes it pauses in the middle of a word, making it easy to miss what was said once audio continues.

It would be great to be able to apply that same "auto rewind" setting for that case.

**Comment by PaulWoitaschek** [comment]
I can set this to a fixed amount of 1s in a future version. The default auto rewind setting is not suited for this because it might be 20seconds and if there are a few notifications coming after each other, the playback would be set way too far back.

**Comment by wberrier** [comment]
That sounds great.
