### ISSUE TITLE
Notification audio control data of current chapter going on is out of sync

### ISSUE THREAD

**Issue by deepmehtait** [PaulWoitaschek/Voice#628]
![screenshot_20170721-200108](https://user-images.githubusercontent.com/8682058/28487889-db2fa912-6e50-11e7-9b78-865b4129ab1c.png)

As show in above screenshot currently audio book is on chapter 85 (6-10) but in notification audio control it shows its in chapter 67 (5-07) the time I resumed the audio book from cold start.
App-Version: 3.3.6.3
Phone Name: HTC One M8
Android Version: Android 6.0

**Comment by mseroczynski** [comment]
@PaulWoitaschek It is due to the fact that setting updated metadata onto MediaSessionCompat object does not affect MediaStyle Notification. A simple solution without big changes would be to call pause then play in MediaPlayer every time you change playlist item.

**Comment by PaulWoitaschek** [comment]
Thanks for your report! Fixed as of 3dca99425fd0de047c8a67796ee57e243d77110f
