### ISSUE TITLE
Some audiobooks stops after each file

### ISSUE THREAD

**Issue by StephanFink** [PaulWoitaschek/Voice#629]
Please include the following details in your bug report:

App-Version: 3.4.0
Phone Name: OnePlus One
Android Version: Notrogen OS 7.1.2 (2017/06/25)

Since some months I sometimes have the problem with an mp3 audiobook (that worked a year before), that the player stops after each file. The only way I found to fix the problem is to reconvert them to new mp3 files. I mostly use LAME and didn't change the quality.

At the moment I am using an alternative player but this one is still the best, but with that bad problem...

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
