### ISSUE TITLE
Can the app access files on an OTG-cabled flash drive?

### ISSUE THREAD

**Issue by STallyHo** [PaulWoitaschek/Voice#634]
Phone Name: Nexus 5x
Android Version: 7.1.2

Due to limited storage on the phone, my audiobooks (MP3s) are on a 32 gig flash drive, which I can connect to the phone with a OTG cable/adapter.

When the drive is connected to the phone, File Manager + sees the MP3s and will play them, but it uses the Google player with only the progress bar and pause button, lacking any capacity to bookmark.

I've tried 2 MP3 players so far and neither of them access the MP3s on the flash drive. For example, Mortplayer Audiobooks doesn't appear to look for files beyond internal storage on the phone.

I have decided to not install any more apps unless I have some assurance beforehand that the app has a bookmarking feature AND the app can play books on an OTG-cabled flash drive. It"d be nice if the app also has a playback speed adjustment and sound good enough to occasionally play some music.

I'm hoping you will indicate that  your app will meet my needs.

**Comment by PaulWoitaschek** [comment]
Where is the directory mounted?

**Comment by STallyHo** [comment]
Thx for the quick response! I'm an older guy who is technically challenged when using the phone. The MP3 files are stored in folders on the flash drive, each book with its own folder. When I plug it into the phone with an OTG cable, File Manager + sees the drive and it's contents immediately. Not sure how to otherwise answer your question.

**Comment by STallyHo** [comment]
Here is the File Manager + app that immediately sees the folders and MP3 files on the  OTG-cabled flash drive and will play the MP3s using the bare bones GooglePlayMusic player:
https://play.google.com/store/apps/details?id=com.alphainventor.filemanager&hl=en

The flash drive is formatted as FAT32.

**Comment by zarmhast** [comment]
@STallyHo, în order to find out the mount path you can do the following:

- open File Manager+
- go to the audio book on your flash drive
- long tap any chapter until it gets selected
- at this point you should see some new buttons at the bottom of the screen
- tap the button that says "More" and has 3 dots
- tap on "Properties"
- tell us what path will it show. It can be long and span a few lines on your screen.

That will give is at least a hint how to help you.

**Comment by PaulWoitaschek** [comment]
This should be possible using the regular picker in the latest versions.
