### ISSUE TITLE
Playback resets to beginning after pause on FLAC files

### ISSUE THREAD

**Issue by dbolton** [PaulWoitaschek/Voice#635]
Please include the following details in your bug report:

App-Version: 3.4.0
Phone Name: LG G5
Android Version: 7.0

If I pause a FLAC file, it jumps back to beginning of the track instead of remembering the current payback position. 

If I convert the FLAC file to MP3 or ACC, it pauses correctly in Material Player.

**Comment by PaulWoitaschek** [comment]
This is most likely due to corrupt meta data.

**Comment by dbolton** [comment]
Does anyone have a sample FLAC file that _does_ work?

**Comment by PaulWoitaschek** [comment]
Please post a file that reproduces this issue.

**Comment by dbolton** [comment]
I created a file with no copyright (just a recording of me snapping) and exported from Audacity. Here's a temporary link: https://cofchristihq-my.sharepoint.com/personal/dbolton_cofchrist_org/_layouts/15/guestaccess.aspx?docid=00969bafade4b4a75841337064a6a20b8&authkey=ATySFiJvYEUf02xBj98NAyY (Github won't let me attach that file time directly).

**Comment by deoren** [comment]
@PaulWoitaschek 

I ran into this last night with an audiobook I purchased from Graphic Audio in FLAC format. I've not tried to modify the metadata yet to see if that helps, but will try to give that a try later tonight. Do you happen to know if there is a good Android app for that? I'll fall back to using Ex Falso on my PC otherwise.

FWIW, I'm able to play it using VLC for Android.

Is there a command that I can run (Windows or Linux) to copy just the portion of the file that contains the metadata? I suspect that Graphic Audio would be fine with me sharing that portion of the file for debugging purposes.

**Comment by deoren** [comment]
> @PaulWoitaschek
> 
> I ran into this last night with an audiobook I purchased from Graphic Audio in FLAC format. I've not tried to modify the metadata yet to see if that helps, but will try to give that a try later tonight. Do you happen to know if there is a good Android app for that? I'll fall back to using Ex Falso on my PC otherwise.
> 
> FWIW, I'm able to play it using VLC for Android.
> 
> Is there a command that I can run (Windows or Linux) to copy just the portion of the file that contains the metadata? I suspect that Graphic Audio would be fine with me sharing that portion of the file for debugging purposes.

I forgot to say, I'm using Voice 3.6.3 from Google Play on Android 7 (LG V20).

**Comment by deoren** [comment]
Incomplete feedback (more testing to do):

I tested some FLAC files created from Audiobook CDs (using Asunder + Metadata editing via Ex Falso) and those played fine. One notable difference between the files that failed to work properly and those that did was the file size/length of audio.

The files created from CDs are limited in length and size (97 files around 25-30 MB each) and do not have an embedded album cover, whereas the larger files purchased from Graphic Audio are significantly larger (7 files, about 350 MB to 400 MB each).

**Comment by deoren** [comment]
> EDIT:
> 
> I should also note that I use the option to jump back X seconds upon resuming playback as a means of reminding myself where I left off. I'll try with and without that option enabled.

With the option to rewind disabled, I can pause and unpause without issue, but attempting to skip (apparently in *any* direction) causes the track to reset to the beginning.

**Comment by halcyonseeker** [comment]
I'm having a similar problem with .flac files ripped from Audible's .aax with `ffmpeg`. They play just fine, but there are two issues:

1. When I tried to pause them, they jumped back to the beginning. I was able to fix this issue by setting Auto Rewind to 0 seconds. 

2. When I try to move through the audiobooks with the slider, forward/back buttons, or Jump To feature, they always reset to the beginning.

I have previously used Voice to listen to .mp3 audiobooks (also converted from .aax files) with no difficulties.

**Comment by PaulWoitaschek** [comment]
If this is still happening in 5.x please open a new issue and attach a file that demonstrates the issue.

**Comment by dbolton** [comment]
I would like to test in 5.x. When I download app-proprietary-release.apk from the releases page and try to install, it says "App not installed." Any tips? Samsung Galaxy S10, Android version 10.

Here's a copy of a test file: https://davidbolton.info/files/test.flac (but really it has been any flac file I've encountered).

**Comment by PaulWoitaschek** [comment]
It's a different signature, you'd need to uninstall the old app first.
However if you're on the google play track it should already have the latest version.

**Comment by PaulWoitaschek** [comment]
The file works fine on my pixel 4. However there is an auto rewind of 2 seconds after each pause so this is very noticeable on this 4 second long file.

**Comment by dbolton** [comment]
Perfect! And thank you for the tip about uninstalling first. I can confirm that 5.0 do longer has this problem.
