### ISSUE TITLE
Large m4b recognized but no playback

### ISSUE THREAD

**Issue by ss000kk** [PaulWoitaschek/Voice#636]
Hi.. I created a single m4b file 742mb in size and 25 hours long. While the file is recognized by MAP it won't play it back.  Other apps will play it but I would like to be able to listen to it in MAP. I hope this will be fixed in a future release.   Thanks a lot for the great work with MAP! 

App-Version: 3.4.0
Phone Name: BLU Vivo XL
Android Version: 5.1 lollipop

**Comment by hjst** [comment]
I'm getting the same problem in 3.4.2.2 with one of my books: the new Audible Stephen Fry reading of Sherlock Holmes, which is a single 72h (!) m4b file.

Is there any hope for this, or should I find a way to split the file by chapter?

**Comment by hjst** [comment]
Ugh, can't edit on mobile: meant to add that I'm on Android 6.0.1, and the visible symptoms of this issue are when you press play (in any chapter) the button graphic changes to the pause icon — but the timestamp doesn't advance — then a few seconds later the button reverts to the play icon (i.e. it doesn't crash the app).

**Comment by PaulWoitaschek** [comment]
Can you upload the file so I can look into it?

**Comment by foosinn** [comment]
I have the same issue. If you want i can send you an ebook link via email. 

App-Version 3.6.1
LineageOS 7.1.2

**Comment by PaulWoitaschek** [comment]
Yes that would be great @foosinn

**Comment by foosinn** [comment]
Should be in your inbox @PaulWoitaschek

**Comment by PaulWoitaschek** [comment]
https://github.com/google/ExoPlayer/issues/3670

**Comment by os97673** [comment]
It looks like ExoPlayer's bug has been fixed Jan 19, 2019.  Time to close this one?

**Comment by PaulWoitaschek** [comment]
Yep. Thanks :)
