### ISSUE TITLE
Only one subdirectory found in audiobook with several subdirectories

### ISSUE THREAD

**Issue by jeriba** [PaulWoitaschek/Voice#637]
Material Player finds only one subdirectory if an audiobook has several subdirectories like:
```
+-- audiobook/
      +-- part_1/           /* only this part is shown in the book list */
            + lots of mp3s here
      +-- part_2/
            + lots of mp3s here
      +-- part_3/
            + lots of mp3s here
```
Another possible configuration would be several books per author in several subdirectories:
```
+-- author/
      +-- audiobook_1/           /* only this book is shown in the book list */
            + lots of mp3s here
      +-- audiobook_2/
            + lots of mp3s here
      +-- audiobook_3/
            + lots of mp3s here
```
It seems to be impossible to add audiobook directories from the same hierarchy. 

A workaround is: cut out subdirs and bring them to "top level" in the audiobook directory. 

App-Version: 3.4.0
Phone Name: Motorola Moto G 2nd Gen
Android Version: 6.0

**Comment by PaulWoitaschek** [comment]
#809
