### ISSUE TITLE
Can't get chapters to load (.m4b) both homemade chapters and commercial ones

### ISSUE THREAD

**Issue by Icy13** [PaulWoitaschek/Voice#638]
App-Version:  3.4.0
Phone Name: Samsung Galaxy Note 4
Android Version: 6.0.1

Super excited to hear that chapters are now supported and finally got a chance to play with them.

Unfortunately, I cannot get the chapter dropdown to show up for any of my books, even though I know they have chapters.

I've tried uninstalling/reinstalling.  Adding/removing folders, and clearing cache.  Also tried re-copying the files from my computer.

At the link below, please find a test file which is NOT working.  As far as I can tell, it is a properly formatted m4b but it will not show the chapters.  Playback works fine.

​
[ MaterialPlayerTestFile.zip](https://drive.google.com/file/d/0B0XrXddEpUjbeEtaQlRTMXZYQlU/view?usp=drive_web)
​
Please let me know if I am missing something silly.  Given the beautiful simply interface, I've considered literally every menu option in the app and none seems like it will affect this issue.

**Comment by thw0rted** [comment]
If you're still watching this issue, does it still happen? I just started using Voice about a month ago, when I figured out how to make a folder of MP3 tracks into a single m4b with chapters, using fre:ac.  These files show chapters just fine.

**Comment by ovidiub13** [comment]
I'm also not seeing chapters on a `.m4b` file on which VLC sees the chapters.

```
App-Version: 4.3.2
Phone Name: OnePlus One
Android Version: 6.0.1
```

**Comment by os97673** [comment]
It looks like the problem has been fixed.  Hope someone can close it ;)

**Comment by PaulWoitaschek** [comment]
Fixed in 5.x!
