### ISSUE TITLE
Add a podcast mode?

### ISSUE THREAD

**Issue by zayuim** [PaulWoitaschek/Voice#643]
Sometimes on my PC I want to download a Podcast using gPodder and copy it to my phone. I've found that the best player is Material Player. Sadly it is optimized towards audio books. I was wondering if you could have a podcast mode which would just show episodes rather than sorting under "albums" (the current behavior) 

Podcast and Audiobook directories should also be separate.

**Comment by CharString** [comment]
Have you given AntennaPod a try? It's geared towards podcasts.

**Comment by PaulWoitaschek** [comment]
+1 for AntennaPod. It's also open source and a great tool which is really specialized on podcasts :)
