### ISSUE TITLE
Player gets stuck after finishing playing a book when connected to android auto

### ISSUE THREAD

**Issue by tssk** [PaulWoitaschek/Voice#645]
Please include the following details in your bug report:

App-Version: 3.4.0
Phone Name: Sony Xperia Z 3 Compact - D5803
Android Version: 6.0.1 Sony Concept Rom
Android Auto version: 2.5.728603-release

Player stops responding when you play a book until end when connected to android auto.

To unstuck you need to unplug from android auto, change to different book and start playing. After reconnecting to android auto it works normally.

Workaround: Do not let the book get to the end.

I will be happy to test or provide more information if needed.

Thanks,

Tomas

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
