### ISSUE TITLE
Feature Request: Audiobook Title Option

### ISSUE THREAD

**Issue by carsten-engelke** [PaulWoitaschek/Voice#646]
Please add an option to specify name of the books. Right now distinguishing books from one series ( and therefore same album) is hard. Maybe use metatags like %title%, %album% and %filename% etc. Looking forward to it.

**Comment by PaulWoitaschek** [comment]
The player tries its best to find the correct title of a book. Therefore I looks in the meta data of the files.
You can press on the edit icon of a book and change the title manually.
