### ISSUE TITLE
Skip Chapter - jumps to some random place

### ISSUE THREAD

**Issue by GGGunrunner** [PaulWoitaschek/Voice#647]
I really loved this player from the first sight, but there's some annoying issue:

When skipping a chapter (fwd/back), it jumps to some random place somewhere in the middle.
Can anybody confirm? Thanks guys!

App-Version: 3.4.2.2
Phone Name: Samsung Note 4
Android Version: 6.0.1

**Comment by PaulWoitaschek** [comment]
Thanks for your report. I assume this is only  with very specific files? And that after you change the book and change it back again, the position is also wrong? Also seeking through the bar does not work reliable?

This is most likely through an issue in the files you use. If you send me one I can have a look, but most likely just converting them to mp3 should fix the issue.

**Comment by miguelfc** [comment]
Hi, This is happening to me too. If I rewind, sometimes (not always) it will just jump randomly back. In my case I am using a single 20h mp3, so no chapters are involved.

(Aside from it, the app is awesome!)

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
