### ISSUE TITLE
Feed rss

### ISSUE THREAD

**Issue by vikkio88** [PaulWoitaschek/Voice#648]
Hi, mine is not a bug report, I have more like an idea for a feature.
As you can imagine from the subject of this issue, I think it would be nice to add an rss feed parser. I have a working one in php that you can see working in here https://scootalite.surge.sh
Would be nice to add a dynamic podcast list that can be updated from a webservice like that

**Comment by PaulWoitaschek** [comment]
For this I recommend dedicated podcast players like AntennaPod :)

**Comment by treestryder** [comment]
I would LOVE this feature, for listening to LibreVox audio books. Which are offered as RSS feeds for simple download.
https://librivox.org/
