### ISSUE TITLE
Autobookmark

### ISSUE THREAD

**Issue by natrius** [PaulWoitaschek/Voice#649]
Could there be something like an autosave function for bookmarks? So you can set or deactivate it in your settings?
If you are listening a book, for example every 5 to 10 minutes a bookmark with an history of 2 or maximum 3.
That way if my phone crashes or i exit the player unexpected or misclick something i still don't have to search it completely. It happened to me while driving and while i don't mind listening another 5 minutes again, i do mind to search again where i was while driving or having to stop and search where my point was.

If you need further explaination, just ask.

(+ i don't like to set a name for the bookmarks. I got now 3 in one audiobook just to have them and they are like "1", "2" and "3". Autonaming would be amazing and it would be possible to access all bookmarcs centralized via overview maybe. But i don't think thats really necessary)

Greetings and thanks for that app :)

**Comment by PaulWoitaschek** [comment]
In the next version you can long-press on the bookmark icon to quickly add a boomark. I hope this is enough for you. I want to keep the player simple so I prefer not to add this additional feature.
