### ISSUE TITLE
Feature request: Include a trim/remove silence feature.

### ISSUE THREAD

**Issue by nicochunger** [PaulWoitaschek/Voice#650]
Especially for audiobooks, a trim silence feature is really useful. Some narrators take really long pauses between sentences, and cutting them out decreases total listening time without having to speed up the whole audio.
I use it with podcasts in the PocketCasts app and it works really good.

**Comment by nicochunger** [comment]
Something that would make this even better is if you can choose how much of the silence you want to remove. That means you don´t cut the whole silence, just say 50% or 70% of it. That way you mantain the relative duration of all the silences but shortening them significantly.

**Comment by PaulWoitaschek** [comment]
#489
