### ISSUE TITLE
notification bar icon confusing

### ISSUE THREAD

**Issue by cukabeka** [PaulWoitaschek/Voice#652]
In general, the voice icon is much too thin and doesn't blend well with the overall material look, IMHO. 
But when it comes to the icon in the notification bar, I find the choice there downright confusing. As I look for anything that looks like a playback icon, I'd suggest to have a playback mini icon there, regardless of the new logo which looks a bit more like to small leafs. 
Maybe you want to make it a preference or revert it to the MP version that I found really helpful when using my phone.

App-Version: 3.5.0.1

**Comment by PaulWoitaschek** [comment]
Should be fixed in the later releases:
https://play.google.com/apps/testing/de.ph1b.audiobook
