### ISSUE TITLE
When returning to Voice file starts from beginning

### ISSUE THREAD

**Issue by KNejad** [PaulWoitaschek/Voice#653]
When the phone is locked and I unlock it with an audiobook playing it sometimes (usually when it has been inactive for a period of time) goes to the beginning of the file. This also happens when I am on another app for some time with the audiobook playing in the background and I return to Voice.

App-Version: 3.5.0.1
Phone Name: Moto G4
Android Version: LineageOS  14.1 (Android 7.1.2)

**Comment by MagTun** [comment]
Same thing here. 

App version:3.6.3  
Phone Samsung S3
Android version : CyanogenMod 13 (Android Marshmallow 6)

**Comment by PaulWoitaschek** [comment]
I assume this is fixed with the latest versions.
