### ISSUE TITLE
Feature Requests: Jump to + Bookmarks

### ISSUE THREAD

**Issue by ss000kk** [PaulWoitaschek/Voice#655]
Thank you for your great work!  A couple of suggestions though:

- Add seconds increment to 'Jump to' command. It would be great for finding specific words in audiobooks.

- Add 'Edit bookmark time' command with H:M:S increments (just like in Jump to.) . It would make bookmarking more accurate.

Thank you!

**Comment by PaulWoitaschek** [comment]
I prefer the way it works right now as it's simpler. Thanks for your suggestion!
