### ISSUE TITLE
How do you create mkv with opus inside??

### ISSUE THREAD

**Issue by gabriellluz** [PaulWoitaschek/Voice#657]
Please include the following details in your bug report:

App-Version: Stable
Phone Name: LGK4
Android Version: 5.1

Hi, I'd like to know how to convert my audiobooks into Matroska files with OPUS inside to use with your app. I heard some people are using it (or maybe I'm wrong). I've tried adding opus to mkvtoolnix but it doesn't work. Also, I've tried finding a tool that makes it possible to mux opus into mkv but no success.
Any tips???

**Comment by PaulWoitaschek** [comment]
Voila :)

https://askubuntu.com/questions/211054/how-to-convert-a-sound-file-to-opus
