### ISSUE TITLE
Double tapping the play/pause button skips forward by skip amount

### ISSUE THREAD

**Issue by jhenninger** [PaulWoitaschek/Voice#658]
Tapping the play/pause button twice in quick succession skips forward by whatever skip amount is set to. It does not matter whether the player is currently playing or paused.

App-Version: 3.5.01
Phone Name: Xiaomi Mi 5
Android Version: 7.1.2

**Comment by gwarser** [comment]
On-screen button? I have this behavior when clicking button on my headphones.
Will be good feature, but for skipping back.

Android 4.4.2

**Comment by jhenninger** [comment]
Yeah, the on-screen button. It happens on the now-playing and library screen.
