### ISSUE TITLE
We seem to have issues with Android auto again

### ISSUE THREAD

**Issue by Eifelschaf** [PaulWoitaschek/Voice#659]
Please include the following details in your bug report:

App-Version: 3.5.0.1
Phone Name: HTC 10
Android Version: 7.0

Hi,
There seem to be some issues with the Android auto integration right now. It seems that the app has problems recognizing that auto is connected and does neither show the current book nor the skip chapter actions. Is this intended or a bug? In case of a bug I'll happily look into this.

Best regards,
Matthias

**Comment by PaulWoitaschek** [comment]
No, bugs are not intended :) It'd e great if you could look into this!

**Comment by Eifelschaf** [comment]
It looks like the receiver is just not registerd at the right time. Right now the AndroidAutoConnection is only registered when a media session is created. Unfotunately the broadcast will only be sent if the app is connected to android auto and this is *before* a media session is set up.

@PaulWoitaschek Do you think it would be problematic to register this directly after launching the application?

**Comment by PaulWoitaschek** [comment]
Nhhnnnn((>????99<(<00

Am 14. Oktober 2017 14:00:25 MESZ schrieb Matthias Kutscheid <notifications@github.com>:
>It looks like the receiver is just not registerd at the right time.
>Right now the AndroidAutoConnection is only registered when a media
>session is created. Unfotunately the broadcast will only be sent if the
>app is connected to android auto and this is *before* a media session
>is set up.
>
>@PaulWoitaschek Do you think it would be problematic to register this
>directly after launching the application?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulWoitaschek/Voice/issues/659#issuecomment-336630464

-- 
Mit freundlichen Grüßen
Paul Woitaschek
Software Entwicklung
www.paul-woitaschek.de

**Comment by PaulWoitaschek** [comment]
No, you can try that :)

**Comment by Eifelschaf** [comment]
I'll do that and also try to implement support for playlists (with the
chapters). This will be better than skipping.

Paul Woitaschek <notifications@github.com> schrieb am So., 15. Okt. 2017,
10:25:

**Comment by Eifelschaf** [comment]
@PaulWoitaschek I wanted to initialize the broadcast receiver in the Application class because I wanted to register it as early as possible (plus I don't know if the main activity is called if the application is started form Android auto) but the dependencies could not be met.

Now I think it's perhaps best to just start the playback service after the app is launched. Do you think this is a good idea (perhaps there are sidee ffects)? If you agree to do it like that: where is the service currently started? I am still a bit lost in teh structure of the project :)

**Comment by PaulWoitaschek** [comment]
Nope, that is not possible due to the android O background  service constraints.

I just rearranged the dependencies, would be great if you could test the change!

**Comment by Eifelschaf** [comment]
I'll have a look. I also noticed some flickering of the initial book listing on my car this morning.

**Comment by PaulWoitaschek** [comment]
Any findings? I want to make a release :)

**Comment by Eifelschaf** [comment]
Maybe I'll find some time to look into it tonight

Paul Woitaschek <notifications@github.com> schrieb am Di., 17. Okt. 2017,
16:22:

**Comment by PaulWoitaschek** [comment]
Great! Ill do a 2% release tonight to slowly test the other changes. Let me know when you tested, so I can go higher 😀

**Comment by Eifelschaf** [comment]
I still see a very weird issue. As soon as I enable the "skip to queue item" action on the PlaybackStateBuilder the root listing of books in android auto starts flickering and showing empty results. I'll have to look into this the next few evenings. I guess I'll just disable the whole queue stuff for this release.

**Comment by Eifelschaf** [comment]
the flickering is fixed and I tested the listing on my car. Apparently the DHU is bugged there. The listing works perfectly fine in a real device.

Please include https://github.com/PaulWoitaschek/Voice/pull/664 for the fix
