### ISSUE TITLE
Internet/network access?

### ISSUE THREAD

**Issue by dardoor** [PaulWoitaschek/Voice#660]
I have the latest version from the Play Store.
I use a firewall and I noticed a lot of connection attempts from Voice. I looked around the app settings and app description and I didn't see anything related to internet access.

After a search here, I found a mention of auto downloading covers. Is this it? Because I never saw it download any covers, even when I let the app online...
Anyway, if that's it, it should probably say so somewhere and/or let the user decide if he agrees.

**Comment by PaulWoitaschek** [comment]
You can press on the edit menu on a book and select an image from the internet.
Else the only thing that requires internet is crashlytics.
