### ISSUE TITLE
chapterreader licensing question

### ISSUE THREAD

**Issue by Hackmodford** [PaulWoitaschek/Voice#666]
If I wanted to include just the chapterreader in a commercial app I'm developing, what are the license requirements? I took a look at the license of the project, but am finding it hard to understand.

**Comment by PaulWoitaschek** [comment]
https://www.gnu.org/licenses/gpl-faq.html#GPLCommercially

> If I use a piece of software that has been obtained under the GNU GPL, am I allowed to modify the original code into a new program, then distribute and sell that new program commercially? (#GPLCommercially)
You are allowed to sell copies of the modified program commercially, but only under the terms of the GNU GPL. Thus, for instance, you must make the source code available to the users of the program as described in the GPL, and they must be allowed to redistribute and modify it as described in the GPL.

If this does not answer your question, feel free to ask further :)

**Comment by Hackmodford** [comment]
Thanks for the quick response Paul.

So basically, if I use that piece of code, I should just link to this repository? Or must I open source my entire app?

**Comment by PaulWoitaschek** [comment]
You must license your app under the same GnuGpl license.

**Comment by Hackmodford** [comment]
This article makes it look like if I use the chapter reader without modifications, I just have to link to the source code for the chapter reader component. Not my entire applications?

https://blog.codecentric.de/en/2012/05/using-gpl-licensed-components-in-proprietary-projects/

**Comment by PaulWoitaschek** [comment]
> Have you ever considered releasing just the chapter reader as a separate library under something like the Apache or MIT license?

Sure I can do that if it helps!

@p2004a would you agree re-licensing your chapter reader changes under the MIT license?

**Comment by p2004a** [comment]
Yes, I agree to re-license it to MIT or Apache.

The way I understand GPL is: You can use this code but if you make any changes (bug fixes, improvements) and you publish binaries containing these changes you also have to publish code of those changes. I think it's quite fair. It's your call ;).

**Comment by Hackmodford** [comment]
Don't you think it would benefit more people if we separated the chapter reader out into a separate library? There's only 1 other open source alternative I could find.

**Comment by PaulWoitaschek** [comment]
Sure, that's what I was offering. How urgent is that request?

**Comment by PaulWoitaschek** [comment]
Here you go:
https://github.com/PaulWoitaschek/ChapterReader

I'll leave this open for feedback. Currently this is in a pre-release and I'd put a try-catch around it.

**Comment by PaulWoitaschek** [comment]
Don't mind, just open an issue in the new library :)

**Comment by Hackmodford** [comment]
Just wanted to say thank you and so far so good!
