### ISSUE TITLE
Android 8.0 (Oreo) aduiobook library issues SD card

### ISSUE THREAD

**Issue by berger0** [PaulWoitaschek/Voice#672]
Please include the following details in your bug report:

Once I updated to Android 8.0 Voice no longer remembers where my audio book library is on my external SD card. Voice loses the directory info on every phone restart. 
I don't know if I am correct to say Voice loses the audio book directory, or if it is Android 8.0 renaming the external SD card path on every restart. 
Let me know how I can help you fix this issue. 

App-Version: 3.6.1
Phone Name: Samsung Galaxy S8 
Android Version: 8.0 Oreo

**Comment by PaulWoitaschek** [comment]
Thanks for the report! This should be fixed in the latest beta versions :)
