### ISSUE TITLE
Can't build project on android studio 3.0 (Mac)

### ISSUE THREAD

**Issue by AraBadalyan** [PaulWoitaschek/Voice#674]
Please include the following details in your bug report:

App-Version:
Phone Name:
Android Version:

Can't build project on android studio 3.0
Operation system Mac Sierra

This is error

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:kapt'.
   > A problem occurred configuring project ':exoplayer-flac'.
      > executing external native build for ndkBuild Voice-master/exoplayer-flac/src/main/jni/Android.mk

I try to copy flac-1.3.2 to  exoplayer-flac/src/main/jni but not helped.

**Comment by PaulWoitaschek** [comment]
Try to run it with --stacktrace. You have the ndk installed?

**Comment by PaulWoitaschek** [comment]
I created a separate library that builds the extensions so no need no more for that :)

**Comment by AraBadalyan** [comment]
Thank you, now project run without problem 👍
