### ISSUE TITLE
Feature request: Recognize files in library with .opus extension as ogg

### ISSUE THREAD

**Issue by automorphism88** [PaulWoitaschek/Voice#679]
Currently, files in a library folder with .opus extensions do not appear to be recognized as audiobooks by Voice. These files will play in Voice if renamed to .ogg, but the [format maintainers recommend](https://wiki.xiph.org/MIME_Types_and_File_Extensions) that the .ogg extension should only be used with vorbis-encoded audio, while the .opus extension should be used for opus-encoded audio. Where applicable, the other extensions on the linked wiki page (e.g. .spx for speex) should also be recognized.

**Comment by gabriellluz** [comment]
I second that. It happens to me, too.

**Comment by gwarser** [comment]
This works for me on current stable version, but does not work in 6.0.0-beta03.

**Comment by PaulWoitaschek** [comment]
Can you mail me such a file?

**Comment by PaulWoitaschek** [comment]
Which Android version are you using?
The file your sent me plays fine on my (Android 12) device

**Comment by gwarser** [comment]
7.1.2, LineageOS 14.1

**Comment by PaulWoitaschek** [comment]
With newer Android Versions this is the default (to not show the artwork) so I'm closing this for now.
