### ISSUE TITLE
No Cover/player controls on Lockscreen

### ISSUE THREAD

**Issue by YahyaAlameddine** [PaulWoitaschek/Voice#682]
Please include the following details in your bug report:

App-Version: 3.3.3
Phone Name: Samsung S7
Android Version: 7.0

Hello, i was wondering why i don't see the cover/the player control on the lockscreen?!

**Comment by PaulWoitaschek** [comment]
Weird. Please use the most recent version of the app (3.6.3).
Maybe you accidentally blocked the notification of the app?

**Comment by YahyaAlameddine** [comment]
i unblocked the notifications, the controls are showed on the lockscreen, but NOT the Album cover!

**Comment by gsarpy** [comment]
@YahyaAlameddine @PaulWoitaschek I also don't get cover art on the lock screen also Samsung S7 and Android 7.0 Voice Version 3.6.3

**Comment by PaulWoitaschek** [comment]
That is depending on the Android Version, not depending on Voice.
