### ISSUE TITLE
Voice and Oreo. 

### ISSUE THREAD

**Issue by Hillmanae** [PaulWoitaschek/Voice#683]
Please include the following details in your bug report:
Playback starts and stops and is generally unstable when either screen off or when other applications are in the foreground. I think there is a problem with the new background data management of oreo. Changing "data optimization" settings has no effect. 
App-Version:3.6.1
Phone Name: oneplus 3
Android Version: 8.0.0

**Comment by PaulWoitaschek** [comment]
This should be fixed in 5.x
