### ISSUE TITLE
Disc Number in notification and lock screen but not app?

### ISSUE THREAD

**Issue by aphirst** [PaulWoitaschek/Voice#685]
App-Version: 3.6.1
Phone Name: Samsung Galaxy S5 Duos
Android Version: 7.1.2

On my phone I have a couple of multi-disc audiobook rips. In the drop-down notification and the lock screen I can see the Disc Number, which means that this information is a) either explicitly tagged or is obvious from context, and b) that Voice is aware of this.

However, when actually in the application itself, I am only able to see Track Names (which for my rips are all just Track N), not the Disc Number.

Is this just an oversight of some kind? It'd be nice to be able to see this info AND to be able to select a specific track from a disc without having to count how many times the Track Number resets in the list.

![photo_2017-12-16_17-43-18](https://user-images.githubusercontent.com/1735556/34072986-a2a231c6-e288-11e7-8148-44e139542100.jpg)
![photo_2017-12-16_17-43-15](https://user-images.githubusercontent.com/1735556/34072987-a2bd1d92-e288-11e7-90c3-f991fd46ca17.jpg)
![photo_2017-12-16_17-43-11](https://user-images.githubusercontent.com/1735556/34072988-a2d5c19e-e288-11e7-9e7a-c38334fea07d.jpg)
![photo_2017-12-16_17-43-06](https://user-images.githubusercontent.com/1735556/34072989-a2ebdd58-e288-11e7-93d5-64fb9946a660.jpg)
![photo_2017-12-16_17-42-58](https://user-images.githubusercontent.com/1735556/34072990-a303152c-e288-11e7-83f4-b6ad356c542c.jpg)

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
