### ISSUE TITLE
Playback controls are too close together, easy to hit wrong button

### ISSUE THREAD

**Issue by ghost** [PaulWoitaschek/Voice#687]
Right now, the playback UI is a bit too small. It's very simple to hit the forward and rewind buttons instead of the play/pause button. 

Can we have an option to make the forward and rewind buttons farther apart? 

Or an option to make the cover the play/pause button?

Or make the play/pause button bigger? 

The only thing about Voice that i feel needs work is the fact that the 3 playback buttons are tiny and grouped too close to one another. This needs some refinement, especially as phones get bigger every year. 

I'd like to point to "Audiobook Player" as a source of inspiration. It doesn't have to be exactly like this, but Voice should have a modern, Android 7+ UI more like this instead of the very small, cramped, Android 5.0 UI it has now. 

![unnamed](https://user-images.githubusercontent.com/11284950/34328168-0ec05b9a-e88c-11e7-9413-574839fa025d.png)

**Comment by 0rAX0** [comment]
This is not how Voice looks like on my device!

**Comment by Cormak** [comment]
@0rAX0 This is not Voice. This is another player I am posting for inspiration. Read my original post more closely..

**Comment by gsarpy** [comment]
@Cormak I agree. There's plenty of space on the outer sides of the buttons to move them out a little bit.

**Comment by Riotous** [comment]
@gsarpy What this app needs is a designer to rework the player.

**Comment by Riotous** [comment]
@innesst I think @PaulWoitaschek will have to wait for somebody to come up with a PR that he likes before anybody can make any dramatic changes to the player. I do however think it is necessary to redo the player a little bit since the current design is way too basic and cramped together.

**Comment by PaulWoitaschek** [comment]
> @gsarpy What this app needs is a designer to rework the player.

This app has one!
@0rAX0 
Feel free to come up with a proposal :+1:

**Comment by 0rAX0** [comment]
The app's homescreen is already going through a redesign ( #689 ) other parts would most definitely follow, especially if you help with bug reports and specific issues.
