### ISSUE TITLE
update broke compatibility with android 4.2

### ISSUE THREAD

**Issue by noxtras** [PaulWoitaschek/Voice#688]
Never mind, found an older version of F-droid. Thanks again for the GREAT app!

Hi,
Great app, the best audio book player I've tried, thank you for writing it. I updated it from the app store, and it broke compatibility with my phone.
Could you please direct me to a virus free version that still works on 4.2, or maybe change something small in the code to make it compatible with 4.2 again? It worked perfectly before the update.

Thanks.

App-Version: latest from app store
Phone Name: X1 Soul
Android Version: 4.2.1

**Comment by PaulWoitaschek** [comment]
Great :)
You can always find all releases on the github release page:
https://github.com/PaulWoitaschek/Voice/releases
