### ISSUE TITLE
Issues with Chapters

### ISSUE THREAD

**Issue by mumi** [PaulWoitaschek/Voice#690]
Please include the following details in your bug report:

App-Version: 3.6.1
Phone Name: Oneplus One
Android Version: 8

Hello, I have my Audibooks ripped with Ffmpeg (FDK_AAC codec) i can see the Chapters in VLC and at the beginning where I used the app, they were there also. It was a really nice feature. But now there are no Chapters anymore. I tried it also with the old audibooks.

**Comment by PaulWoitaschek** [comment]
Thanks! Can you send me a file which should have chapters by mail?

**Comment by gsarpy** [comment]
@PaulWoitaschek any update on the chapters? If I recall correctly .cue files were supported, right? I checked my cue files and they all seem correct but I don't get chapters on any books with them.

**Comment by mumi** [comment]
Issue still there

**Comment by wberrier** [comment]
I'm also seeing this for several .m4b files. 

.ogg files show chapters just fine.

Here's a link to some test files: https://drive.google.com/open?id=0B5DxbhZHghuGMnRkY1VpakI2TjA

Some background: I got a new phone, and (forgot which order) installed the app and copied over my audiobook files.

**Comment by mumi** [comment]
> Thanks! Can you send me a file which should have chapters by mail?

Push. Still not working

**Comment by PaulWoitaschek** [comment]
Fixed in 5.x!
