### ISSUE TITLE
Restart sleep timer: App hangs with Android 4.4.2

### ISSUE THREAD

**Issue by MartinCorteza** [PaulWoitaschek/Voice#691]
App-Version: Most recent
Phone Name: Samsung SM-T230 Tab 4 
Android Version: 4.4.2

If I restart the sleep timer several times (>2), the apps responsiveness become sluggish. For me, it seems like a loop is dragging on cpu/system resources.

**Comment by PaulWoitaschek** [comment]
Closing this as Android 4.x is no longer supported.
