### ISSUE TITLE
Voice list title and voice menu not visible/readable in night mode

### ISSUE THREAD

**Issue by TheJackTenor** [PaulWoitaschek/Voice#694]
If night mode theme is activated, voice list title and title menu will be not visible. It caused by title color and menu color become white while background still in white instead black

Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Xiaomi Mi4
Android Version: 6.0.1 Marshmellow

**Comment by PaulWoitaschek** [comment]
Can you post a screenshot?

**Comment by TheJackTenor** [comment]
![screenshot_2018-01-19-11-42-15-584_de ph1b audiobook](https://user-images.githubusercontent.com/32075564/35135186-1b2d9046-fd0e-11e7-920f-126d42c0e8f2.png)

**Comment by PaulWoitaschek** [comment]
Where do you have that version from? That's no release version, that's an in-the-middle-of-development version.

**Comment by TheJackTenor** [comment]
i got this from master branch. I think master branch contain the final version. is that right ?

**Comment by PaulWoitaschek** [comment]
Nope, the master branch is just the main branch. If you want a release version you have to checkout a tag.

**Comment by PaulWoitaschek** [comment]
However feel free to fix that if you like ;)

**Comment by TheJackTenor** [comment]
Yeah, actually I already make some changes to fix that issue. This is the result.

**Comment by TheJackTenor** [comment]
![screenshot_2018-01-19-15-12-59-736_de ph1b audiobook](https://user-images.githubusercontent.com/32075564/35145082-1d32647c-fd39-11e7-9410-b8739cc59155.png)
