### ISSUE TITLE
Randomly Starts Playing Audio

### ISSUE THREAD

**Issue by Sitruk** [PaulWoitaschek/Voice#695]
This issue just started happening today. The Voice app is not running at all but while I am watching Plex on my phone via a bluetooth earbud, Voice will launch and start playing the last book I was listening to. I stop and close Voice completely and it just occurs again at random. 

Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Pixel XL
Android Version: 8.1.0

**Comment by PaulWoitaschek** [comment]
If this still occurs in the latest versions, please open a new issue.
