### ISSUE TITLE
Update the F-Droid version

### ISSUE THREAD

**Issue by e00E** [PaulWoitaschek/Voice#697]
[F-Droid](https://f-droid.org/packages/de.ph1b.audiobook/) is serving version `3.6.1` while the current release here (and  in the Google Play Store I believe) is `3.6.3`.
It would be nice to have the newest release on F-Droid.

**Comment by leafcutterant** [comment]
What happened to Voice on F-Droid? I've not seen a new version pushed there for over a year while commits and releases are coming out on Github.

@PaulWoitaschek, could you chime in?

**Comment by PaulWoitaschek** [comment]
They don't build 3.6.3 and there is no stable version after that.
Once 4.0.0 hits stable I'll get in touch in case fdroid still doesn't build.

**Comment by leafcutterant** [comment]
What happened to Voice on F-Droid? I've not seen a new version pushed there for over a year while commits and releases are coming out on Github.

@PaulWoitaschek, could you chime in?

**Comment by leafcutterant** [comment]
Thank you!

**Comment by PaulWoitaschek** [comment]
I opened an issue so this gets built again:
https://gitlab.com/fdroid/fdroiddata/issues/1481

**Comment by 4ut0-M-4t** [comment]
@PaulWoitaschek, could you reopen this issue, please, till it gets successfully resolved? Otherwise inevitable frustrated F-Droid users will keep on nagging you further, creating more duplicate issues.

**Comment by PaulWoitaschek** [comment]
It's resolved from my side. I don't think that people who don't search for "F-Droid" first before creating an issue would find the issue if it was open.

This is what it looks like when I create an issue containing f-droid:
![image](https://user-images.githubusercontent.com/743462/51704157-999cba00-2018-11e9-8598-107d908587a7.png)

**Comment by 4ut0-M-4t** [comment]
Well, your screenshot shows only **closed** issues, meanwhile there's still no new build in F-Droid repo. You therefore end up getting more duplicate issues.
People treat Bug Tracker as some sort of a social network these days.

**Comment by trymeouteh** [comment]
Great app! Please keep this app on F-Driod.

**Comment by PaulWoitaschek** [comment]
@trymeouteh Read the linked issue; it's up to fdroid, not voice.

**Comment by geoderix** [comment]
I don’t think that F-Droid allows you to distribute a program with an integrated tracker - Google CrashLytics for Voice Audiobook Player. Maybe the lack of a fresh version of the program on the F-Droid can be explained by the fact that the author has built this tracker into the program. But does not publicly report it, on the contrary, claiming that the program does not monitor users?
It seems to me that the latest version of the program will not appear on the F-Droid until the author decides to remove the tracker from the program.

**Comment by PaulWoitaschek** [comment]
No, it's because of technical issues on the fdroid side. Read the linked issue. 
There is a build flavor where the crash reporting to crashlytics is not included.

**Comment by geoderix** [comment]
All new versions are spying on users, I think that’s why you don’t want to make a version of the F-Droid clean from trackers. You blame the f-droid on this. What does the f-droid have to do with your desire to spy on users. On google play, you claim that there are no trackers, however they are. It doesn’t look good.

**Comment by PaulWoitaschek** [comment]
Thats nonsense. Just read the linked issue above: https://gitlab.com/fdroid/fdroiddata/issues/1481

**Comment by macearl** [comment]
Seems like Kotlin Support arrived in F-Droid and a new Version was pushed to the F-Droid Repo, I'm assuming once Version 5 leaves RC Status it will also show up on F-Droid

Everyone involved in this app and the distribution keep up the good work :+1:
