### ISSUE TITLE
Can't get past welcome screen

### ISSUE THREAD

**Issue by davidsgrogan** [PaulWoitaschek/Voice#699]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Pixel XL
Android Version: 8.1.0

When I open the app, I get a welcome screen that says "Welcome! Let's get started by adding your first audio book."

I tapped the button, added a folder with an audiobook. But when I tap X or back button I get the welcome screen again where it appears all functionality is blocked except adding an audiobook folder.

Maybe the folder I added isn't recognized somehow? But when I go back to the Audiobook folders screen, the directory is still there.

**Comment by davidsgrogan** [comment]
This was mostly user error. The .mp3 extensions got dropped from my files somewhere along the way. But this can turn into two feature requests: (1) better messaging when no audio files are found in the requested directory and (2) check file headers instead of the extensions when looking for audio files.

**Comment by tgp1994** [comment]
The welcome screen was bothering me too in how persistent it was - I don't have any media yet, but I'd still like to access things such as the app settings. Could the welcome system be made dismiss-able, perhaps replaceable with little reminders to add media if it appears that there is nothing available?

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
