### ISSUE TITLE
Previous and next buttons on playback screen

### ISSUE THREAD

**Issue by mdquerng** [PaulWoitaschek/Voice#700]
Hi

Thanks for your great app. It is now not only my main app for listening to books on my device but also music and podcasts.

Perhaps I'm missing something but I see fast forward and rewind buttons on the playback screen but no previous/next track or book buttons. This would really be nice as it would keep one from needing to move out of the playback screen to go to the next track/chapter/book. These buttons could be right next to the existing fast forward/rewind buttons.

Let me know if perhaps this functionality is already in the app and I somehow have missed it. Thanks in advance.

Best
Mark

**Comment by spidgorny** [comment]
![image](https://user-images.githubusercontent.com/1579235/48694274-32a7f280-ebdc-11e8-80cd-ff2dc112c163.png)

The problem seems to be either fixed or not existing. Close this ticket.
