### ISSUE TITLE
Audiobook Folders active / inactive

### ISSUE THREAD

**Issue by thofrey** [PaulWoitaschek/Voice#701]
Feature Request: Add checkbox to activate / inactivate (hide) the audiobook folders.

Why? As I have many audiobooks (and folders for other categories like music, podcast and more) I would like to reduce the listed books - but I do not want to delete the folders I have setup or move the files with a file manager. 

Best regards and many thanks for this great app!

Thorsten
--
App-Version: 3.6.3
Phone Name: - 
Android Version: -

**Comment by eMarchOnward** [comment]
The various "Audiobook Folder" names could server as a top level category perhaps? The app would start up and list these folders, then you could select one and see all the "books" inside of it. I wouldn't mind something like this either as I use this app for podcasts and audiobooks. I have so many podcasts it's a bit of a mess.

**Comment by PaulWoitaschek** [comment]
Fixed with the new category view.
