### ISSUE TITLE
use cover metadata in opus files

### ISSUE THREAD

**Issue by cvpt** [PaulWoitaschek/Voice#702]
Some opus files have cover metadata. I would like the player to be able to recognize it and use the appropriate thumbnail, just like it happens already for mp3 files.

Attached you can find a zip file with the appropriate files as example.

[opus.zip](https://github.com/PaulWoitaschek/Voice/files/1753395/opus.zip)

More information can be found by reading

`opusenc --help-picture`

[Or the opusfile documentation](http://opus-codec.org/docs/opusfile_api-0.7/structOpusPictureTag.html)

App-Version:3.6.1
Phone Name: -
Android Version: 6.0.1

**Comment by wberrier** [comment]
Note, it appears that cover art is supported correctly for ogg files.

**Comment by PaulWoitaschek** [comment]
Fixed in 5.x!
