### ISSUE TITLE
Pause/play button on Bluetooth headset can't start or stop play

### ISSUE THREAD

**Issue by l0b0** [PaulWoitaschek/Voice#707]
How to reproduce:

1. Pair Bose QC35-II with phone
1. Start Voice
1. Start playing an audiobook (or pause it)
1. Press the button marked "…" on the headset

Expected behaviour: Voice should toggle between pausing and unpausing.

Actual behaviour: Nothing happens.

Additional information:

- When double-clicking the button during playback nothing happens either.
- When *triple-clicking* the button during playback Voice rewinds by 20 seconds, so there absolutely is a connection to the app.
- F-Droid says the current version was added on 2017-10-27. I bought the phone well after that, so I believe I've only ever had the last version installed. The strangest thing is *it used to work.*

App-Version: 3.6.1
Phone Name: Nokia 6 TA-1033
Android Version: 7.1.2

**Comment by holocronweaver** [comment]
Is it possible an Android update or a new app you installed caused this change?

**Comment by l0b0** [comment]
The former certainly not, because I have not installed an update in the meantime. Obviously an app could be causing this, but how could I possibly know without completely resetting the system?

Today I discovered that the functionality is not *always* broken, annoyingly. I was able to pause and unpause a few times, but a few minutes or an hour later the functionality was gone and has not come back since. I've been using no other audio related apps all day.

**Comment by l0b0** [comment]
While running Voice `adb logcat | rg -i bluetooth` prints

> vol.Events: writeEvent level_changed STREAM_BLUETOOTH_SCO 11

when pressing volume down, but doesn't print anything when pressing (or double-pressing) the middle button. `adb logcat` prints a *lot* of stuff, but not all the time, and nothing (at least immediately, while the log is a bit quiet for a second) when pressing (or double-pressing) the middle button. So I guess either it's not sent at all or it's somehow intercepted silently or with a massive (1+ second) delay.

**Comment by fpar63** [comment]
Having the same issue with a pair of soundpeats QC30's. The voice player does not react to the play pause button. This issue is not present of any other apps and it doesn't seem to matter whether any other audio apps are running. I will post a logcat when I get home. Thanks.

**Comment by 4ut0-M-4t** [comment]
**Device info**
Device: Samsung GN4
Android version: 6.0.1
Voice version: 3.6.1 (F-droid)
Headphones: Sennheiser M2 AEBT

Pause button works just fine. 
Might be Bose QC incompatibility problem.

**Comment by fpar63** [comment]
Apologies forgot to report back but I managed to completely fix the issue by deactivating battery optimisation for the app. It doesn't drain battery in the background anyway.

**Comment by holocronweaver** [comment]
Thanks for the report!

@l0b0 Can you check if this fixes the issue for you?

**Comment by l0b0** [comment]
This issue seems to have fixed itself sometime since my last comment. I'll report back if it happens again. Thanks all for the help!
