### ISSUE TITLE
Android auto-closes app, breaking automatic playback resume

### ISSUE THREAD

**Issue by holocronweaver** [PaulWoitaschek/Voice#709]
Problem: Android 7 and up aggressively close apps within an hour or so of going idle, which prevents automatic playback resumption when you connect an audio device (wired, bluetooth, etc.). 

Workaround: You can manually disable Android power management for Voice and this solves the problem for me, but I imagine most users won't be bothered to do this as it is somewhat hidden and not obvious to non-technical users. 

Proposed Solution: We should probably make persistence default in Settings and allow users to turn it off if they want.

App-Version: 3.6.3
Phone Name: Pixel 2 XL
Android Version: 8.1

**Comment by PaulWoitaschek** [comment]
No need for a setting, we can make the notification persistent as default. Up for grabs!

**Comment by abguymon** [comment]
#839 #868 Are duplicates of this issue

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
