### ISSUE TITLE
[Feature Request] Change order in which books are played

### ISSUE THREAD

**Issue by MarksGitHubAccount** [PaulWoitaschek/Voice#713]
App-Version: 3.6.3
Phone Name: Samsung Galaxy J5 (2017)
Android Version: 7.0

As an alternative to playlists, would it be possible to change the order in which books appear and are played, please?  I've tried adding books in a specific order, but they seem to appear in alphabetical order, regardless.  I tend to add a bunch of books in one go, and like to order them, saving the best until last :)

Thanks,
Mark

**Comment by PaulWoitaschek** [comment]
Obsolete with the new category view.
