### ISSUE TITLE
opus/ogg chapter parsing too strict

### ISSUE THREAD

**Issue by wberrier** [PaulWoitaschek/Voice#715]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Republic Wireless Moto X
Android Version: 5.1

If opus/ogg have chapter comments with only one preceeding zero, the chapters fail to be recognized.

Now, the chapter extension says the chapters should go between 1-999, so I guess technically 1-99 is out of spec.

For reference, VLC supports chapters when they only have one preceeding zero.

Thoughts?

**Comment by PaulWoitaschek** [comment]
Fixed in 5.x
