### ISSUE TITLE
Title not displayed for opus files

### ISSUE THREAD

**Issue by wberrier** [PaulWoitaschek/Voice#716]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Republic Wireless Moto X
Android Version: 5.1

The title of the book is in a "TITLE" comment, but it is not displayed in the main screen that shows the list of books.  Instead, the filename is displayed.

Note, this works for .ogg files, which uses a similar comment.

**Comment by monreal** [comment]
I just ran into the same thing. Converted some audiobook to Opus, MP3 and AAC. The Opus version is the only one showing the incorrect title. Funny enough, it is also the only one showing the correct amount of chapters. However, just hitting play does not work for Opus while that works fine for MP3 and AAC. Opus plays after I manually seek using the slider. Playback stops after the chapter, though.

**Comment by PaulWoitaschek** [comment]
This is fixed in 5.x
