### ISSUE TITLE
Ability to play faster than 2.5x

### ISSUE THREAD

**Issue by Natenom** [PaulWoitaschek/Voice#717]
Can you please enable the app to play faster than 2.5x?

I am used to listen to audio books very fast and there are many audio books where speakers speak very very slow. So 2.5x is not fast enough for me.

Maybe up to 4x?

Thank you.

App-Version: 3.6.1 from F-Droid

**Comment by CercaTrova** [comment]
Use this fork: https://github.com/BrandonOCasey/Voice/releases

**Comment by eMarchOnward** [comment]
I'm curious what sort of audiobooks people listen to at 6x. I tend to listen to nonfiction books, popular science and psychology, e.g., and there is no way I could ever listen to any of them even at 2x, except for maybe 3 minutes at a time.          

Not criticizing, just curious. Perhaps my brain just doesn't work that fast. Perhaps if I was listening to more light hearted fiction I could do it.

**Comment by CercaTrova** [comment]
I also started at like 1.3x and gradually, over a few months, moved up to 4x. Now everything else sounds so slow. It's all a matter of time getting used to it, not necessarily an innate thing.

**Comment by PaulWoitaschek** [comment]
#482

**Comment by simonhull** [comment]
So, would we be able to get these changes applied in the core version?  I don't mind using a fork, but I would love to be able to get upgrades easier through the app store and it seems like it's a fairly common request.  It just seems a bit unnecessary to have to use a community maintained version when there's just the one line of code changed.  I'd be happy to open a PR if that's easier.

**Comment by satvikpendem** [comment]
@brandonocasey would you mind updating the fork?
