### ISSUE TITLE
Disable accessing internet on startup

### ISSUE THREAD

**Issue by wberrier** [PaulWoitaschek/Voice#721]
App-Version: 3.6.3
Phone Name: Republic Wireless Moto X
Android Version: 5.1

I have limited data on my phone so I disable data for most apps.

Voice tries to access something on startup (not sure why it would need to do that?  Usage stats?) generating a "data disabled" pop-up.  This often happens in the car, making it one more thing to avoid when starting up the app.

Any way to disable this?  Ideas?

**Comment by wberrier** [comment]
Looks like it's POSTing to this url:

https://e.crashlytics.com/spi/v2/events

Not sure what to suggest about this one.  I see the value in crash reporting, but some of us are mobile data sensitive.

**Comment by PaulWoitaschek** [comment]
That's crashlytics. If you don't like that you can use the version from fdroid!

I actually tried to disable everything but the crash report feature, but apparently it's sending more events than just upon crash:
https://github.com/PaulWoitaschek/Voice/blob/v3.6.3/app/src/proprietary/java/de/ph1b/audiobook/features/crashlytics/CrashlyticsProxy.kt#L24
