### ISSUE TITLE
[Feature Request] Voice navigation

### ISSUE THREAD

**Issue by cloudbopper** [PaulWoitaschek/Voice#723]
Thanks for the great audiobook player. I often listen to audiobooks while biking/doing chores with my hands and felt a need to be able to rewind or pause the book using voice navigation, without having to unlock my phone and press the appropriate button. I couldn't find any audiobook players with this feature, so I thought I might hack a good open source player to add it, which is how I found Voice. I'm curious whether other folks would be interested in this feature?

I'm a CS researcher and interested in developing the feature myself, though I haven't programmed for Android in several years. I'd be happy to collaborate with anyone else interested in working on it. Based on a cursory survey of freely available speech recognition APIs, I was thinking of using Snowboy Hotword Detection (https://snowboy.kitt.ai/) to trigger listening followed by Android's SpeechRecognizer API, or else using Snowboy Hotword Detection for the whole thing (since only a few commands would be needed in practice).

**Comment by PaulWoitaschek** [comment]
You can use Android Auto's voice navigation.
