### ISSUE TITLE
Possible fork being sold on Play Store

### ISSUE THREAD

**Issue by laurentlbm** [PaulWoitaschek/Voice#726]
Yesterday, someone posted about their app on Reddit and offered promocodes. It is nearly identical to Voice in both looks and features. Voice is not credited though and the source had not been released as required by the GPL.

I don't know if you want to do something about it, but I thought you ought to know.

App: https://play.google.com/store/apps/details?id=com.audiobook.player
Reddit thread: https://www.reddit.com/r/androidapps/comments/8ghppf/_/

**Comment by laurentlbm** [comment]
The author has posted that he will release the code on his GitHub: https://www.reddit.com/r/androidapps/comments/8ghppf/_/dyfch92

**Comment by PaulWoitaschek** [comment]
Thank you for bringing this up!
