### ISSUE TITLE
Track resets to start on app open

### ISSUE THREAD

**Issue by test2a** [PaulWoitaschek/Voice#732]
Suppose an audiobook has multiple tracks and you are on track 1. You go on listening with the screen off and track switches to 2 or 3. Now, whenever you open the phone from the lockscreen, it resets to the start of the track. Always.
I am on track 1, I turn the screen off and reach middle of track 2. If I open the app from the lockscreen, it goes back to start of track 2 and then I have to find my way to the middle manually.
This happens on android, f droid version at least

**Comment by PaulWoitaschek** [comment]
If this is still present in the latest version, please open a new ticket.
