### ISSUE TITLE
Voice app restarts

### ISSUE THREAD

**Issue by Steffen3000** [PaulWoitaschek/Voice#735]
Voice Audiobook Player is a great app for playing my downloaded podcasts.

It works fine on Samsung Galaxy S7 - Android 8, connected to Android Auto, but on my older phone that I often use for podcasting it close down and restart after app.2 minuts, running Android 5.0 on HTC One connected to Android Auto. 

App-Version: 3.6.3
Phone Name: HTC One (M7)
Android Version: 5.0.1

**Comment by PaulWoitaschek** [comment]
If this is still present in the latest version, please comment and I'll re-open.
