### ISSUE TITLE
[Feature Request] Play over Transient Notification

### ISSUE THREAD

**Issue by abhikush** [PaulWoitaschek/Voice#737]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Galaxy S9+
Android Version:8.0.0

The app pauses whenever I get transient notifications from other apps. It would be nice to have the ability to continue playing over those notifications. Most of the audiobook/podcast players have this ability.

**Comment by PaulWoitaschek** [comment]
For simplicity reasons, the playback always pauses. Opposite to Music, Speech should usually be paused instead of spoken over.
