### ISSUE TITLE
.mp3 book won't play

### ISSUE THREAD

**Issue by francois90** [PaulWoitaschek/Voice#739]
When i try to play a book in .mp3 format it doesn't work. The book appears in the list, but when i select it and press play, the play button transforms into a pause button for a few seconds and then switches back to a play button but nothing else happens. 

App-Version: 3.6.1
Phone Name: Moto G4 Plus
Android Version: 7.1.2

Thanks

**Comment by spidgorny** [comment]
Should I upload an example MP3 with this issue?

**Comment by francois90** [comment]
I have since figured out that the problem is due to the size of the file that i was trying to play. I split it in two and it fixed the problem. Still it would be nice if the app could handle  very large files because some books are quite long.

**Comment by Riotous** [comment]
@francois90 How big was the file? What do you think the maximum filesize is? Perhaps you should change the name of this issue to "Voice can't play mp3 files over X mb"

**Comment by PaulWoitaschek** [comment]
If this is still present in the latest version, please mail me a file to the email address in my github profile.
