### ISSUE TITLE
The problem of displaying in the notification line

### ISSUE THREAD

**Issue by gegemon2012** [PaulWoitaschek/Voice#740]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: readmi 3s
Android Version: 6

Can I add the ability to change the color of the control buttons in the notification line?

**Comment by gegemon2012** [comment]
![screenshot_2018-07-15-14-31-00-935_de ph1b audiobook](https://user-images.githubusercontent.com/15074580/42733121-287534ba-883d-11e8-89b4-918cf919eac2.png)

**Comment by PaulWoitaschek** [comment]
This is a problem of the custom rom overwriting the default colors. The colors the app chooses work.
