### ISSUE TITLE
Voice causes Android Auto to become unresponsive

### ISSUE THREAD

**Issue by rejhgadellaa** [PaulWoitaschek/Voice#748]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Pixel 2016
Android Version: Android 8.1 (and probably 9)

I'm having some issues with Voice's Android Auto player. If I play an audio book in Android Auto, the entire Auto app slows down to a crawl over time (5~15m) and eventually closes. Google Play Music and Pocket Casts work fine so it seems to be an issue with Voice.

My audio books are mp3 files, each chapter a separate file.

The slowdown affects not just the Voice player, everything within Auto becomes unresponsive; Maps, the (Android Auto) navigation buttons, everything. Haven't checked if the entire device is slow because I'm driving in those cases ;)

**Comment by PaulWoitaschek** [comment]
Should be fixed with the upcoming version!

**Comment by rejhgadellaa** [comment]
Hi it's been a while and I was wondering when we can expect this new version because without this fix I simply can't play audio books when driving (I can't run Voice and Android Auto without Auto becoming unresponsive)?

Thanks!
