### ISSUE TITLE
Fix signing config

### ISSUE THREAD

**Issue by RomanZhilich** [PaulWoitaschek/Voice#753]
Current signing logic fails without `signing.properties`, it also seem to be the reason for failing Circle CI builds.

I think it would make sense to add conditional logic and use debug keystore if `signing.properties` file doesn't exist. It would look something like:
```
def propsFile = rootProject.file('signing.properties')
if(propsFile.exists()) {
      props.load(new FileInputStream((propsFile)))
      storeFile = rootProject.file(props['STORE_FILE'])
      storePassword = props['STORE_PASSWORD']
      keyAlias = props['KEY_ALIAS']
      keyPassword = props['KEY_PASSWORD']
} else {
      storeFile = file("${System.getProperty("user.home")}/.android/debug.keystore")
      storePassword = "android"
      keyAlias = "androiddebugkey"
      keyPassword = "android"
}
```
Alternatively dummy keystore might be added to repository itself or generated via Gradle plugin.

**Comment by PaulWoitaschek** [comment]
Thanks for reporting!
Fixed by a9d817f9437b3ed27fdcd8cf06f3d68f40581954
