### ISSUE TITLE
Files without ID3-tags could not be played

### ISSUE THREAD

**Issue by rainerh-ffm** [PaulWoitaschek/Voice#754]
App-Version: 3.6.3
Phone Name: Samsung S4 GT-I9515
Android Version: 5.0.1

I had a few mp3-files (audiobook purchased on data-CD) without any ID3-tags. These could not be played by Voice. After adding a few ID3-tags (title, artist) problem was gone. Maybe it would be helpful at least to verbosely report an error to the user instead of simply doing nothing.

**Comment by PaulWoitaschek** [comment]
Can you send me such a file that does not play?

**Comment by rainerh-ffm** [comment]
Sorry for the delay ...

Paul Woitaschek <notifications@github.com> schrieb am Sa 08 Sep 2018  
09:56:57 UTC:

> Can you send me such a file that does not play?

Not exactly (not for the moment, I'm trying to remember), but I have a  
similar issue with  
http://alternativlos.cdn.as250.net/alternativlos-42.mp3 - it didn't  
play unless I removed the Germanistik "Umlaut" from ID3-Tags.

**Comment by PaulWoitaschek** [comment]
Hmm on my pixel it just plays m
