### ISSUE TITLE
Paused playback resumes AFTER the paused audio

### ISSUE THREAD

**Issue by jakubklos77** [PaulWoitaschek/Voice#760]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Huawei P20 Pro
Android Version: 8.1

Hello,
I have the following issue:

When I keep listening to a book and Pause, the time position jumps backwards (this is normal behavior). However, when I resume the playback the actual audio that I hear comes AFTER the position I paused the book at. This means I am missing a few seconds (10-20 secs) of audio.

So each time I continue listening I must manually skip a few jumps backwards to hear where I left of.

I guess the reported/displayed position is different than the actual audio file itself (MP3 in my case).

I can reproduce this 100%.

In case I did not express myself properly before:

1. I listen to this text "TEXTA TEXTB TEXTC"
2. I pause at TEXTB and the time displayed is 5:30:30 (after skiping those 20 seconds backwards)
3. I continue playing and what I hear is not TEXTB but something later (like TEXTC or event later)

Please, let me know. I can help debug the issue any way

Thank you
Jakub

**Comment by PaulWoitaschek** [comment]
This is probably due to bad media.
However maybe the latest version of Exoplayer has fixed this issue already.
