### ISSUE TITLE
[Design] Switch Pink buttoncolor in Darkmode

### ISSUE THREAD

**Issue by newhinton** [PaulWoitaschek/Voice#761]
The Darkmode could be improved by changing the accentcolor from the default pink to a more fitting orange. It wouldn't stand out that much and would look great!

**Comment by PaulWoitaschek** [comment]
Upstream the pink is gone and it's a pure red. What do yout ink?

![image](https://user-images.githubusercontent.com/743462/46870221-4b2f2b00-ce2e-11e8-8c93-ab75de376e60.png)

**Comment by PaulWoitaschek** [comment]
@0rAX0 cc

**Comment by 0rAX0** [comment]
@PaulWoitaschek Would it be possible/worth it to make the buttons and text colors dynamic as seen in the dark mode I proposed? I'm sure someone else would find a problem with Red. 😸

**Comment by newhinton** [comment]
@PaulWoitaschek I pulled the repo and build the app, and yes, this is better! 

If you want to hear them, i have some ideas you could use to further improve the ui, but i guess i should make them in #689

**Comment by newhinton** [comment]
I guess this is closed now since it already is upstream ;)
