### ISSUE TITLE
Replace the getbase FAB with the material one

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/Voice#763]
And roll a custom solution for the floating action menu.

This is necessary because for whatever reason it crashes for the Android Auto review team.

https://github.com/PaulWoitaschek/Voice/blob/fe127998987cbf6d0852116b314a075bd81bff5e/app/src/main/res/layout/folder_overview.xml#L36-L70

**Comment by PaulWoitaschek** [comment]
@Plastix 
Still looking for a way to contribute?

**Comment by Plastix** [comment]
@PaulWoitaschek I'll look into it. I'm working on a PR which ads sorting options to the main list view.

**Comment by PaulWoitaschek** [comment]
Working on this!

**Comment by Plastix** [comment]
@PaulWoitaschek Another option which might be a little easier to implement is to morph the fab into a menu: https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions

**Comment by PaulWoitaschek** [comment]
Stopped working on this, too much work currently.
Up for grabs :)
+1 for the morphing idea!

**Comment by PaulWoitaschek** [comment]
Works like it is when disabling app bundle oO
