### ISSUE TITLE
Change text size (List layout or both)

### ISSUE THREAD

**Issue by dapgo** [PaulWoitaschek/Voice#766]
I use Voice in 2 phones; big screen+Android 6 and small screen+Android 4

As I use voice at night,my sight is quite restricted, and specifically if I have been sleeping for a  while and then  I try to play or move back in an audio.

In the big screen I can see with less effort and especially if title is written in caps. But if I were able to select a bigger font it would help a lot.
Regarding the cons/title length, I realized that most of  my audiobooks have quite short title.

App-Version: 3.5.0.1
Android Version: Android 6 and Android 4

**Comment by PaulWoitaschek** [comment]
It's already larger in the upcoming redesigned version.
