### ISSUE TITLE
Changes to sorting

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/Voice#772]
- [x]  Don't sort from within the `BookRepository`
- [x]  Apply the sorting in the `MediaBrowserHelper`
- [x] Unit test the `BookComparators`
- [x] Move the `BY_NAME` comparator to the top so the default in the dialog appears first
- [x] Don't let Book implement comparable.

**Comment by PaulWoitaschek** [comment]
I'm rethinking if this feature is actually useful.

Once we implement the collapsing this feature will rather be confusing:

![image](https://user-images.githubusercontent.com/743462/47046581-c9286480-d195-11e8-8d9e-ceec6650b440.png)

For the `Current` books we want the last played books on top.
For the `Not started` books we probably want the last added to appear on top.
For the `Completed` books, we want the last played books on top.

What do you think about making these 3 cases the default and removing the setting?
Then we could open a fullscreen dialog upon `Show more` click and add a filter icon to the top where you can sort them by name / last played / date added.

@Plastix @0rAX0
Thoughts?

**Comment by Plastix** [comment]
Sounds good to me!

**Comment by PaulWoitaschek** [comment]
Removed the setting, tracking the fullscreen dialog in #773
