### ISSUE TITLE
Won't Start via Bluetooth 

### ISSUE THREAD

**Issue by innesst** [PaulWoitaschek/Voice#778]
Please include the following details in your bug report:

App-Version: 3.6.3
Phone Name: Pixel 2
Android Version: 9

Trying to control with Bluetooth button in car. Can stop and skip using the button, but cannot start again. Works fine with version 2.4.2

**Comment by nioncode** [comment]
For me it's the other way around, I can only start, but not stop the playback over bluetooth. This worked fine without issues in previous versions, don't know since when it has been broken.

**Comment by innesst** [comment]
Trying 4.0 rc8 . Problem is now as nioncode describes... Can start but not stop via Bluetooth. Stops and starts by itself for navigation directions.

**Comment by innesst** [comment]
A bit of a clarification... Bluetooth is able to stop the very first time after a force stop. I can send debug info with a bit of guidance.

**Comment by innesst** [comment]
Continues with version 4.1.1

More testing shows that Bluetooth to pause will always work correctly the first time after I manually stop and swipe away the notification. Subsequent pause requests do not work. It doesn't matter if the app is open and on the now playing screen or if in background. In fact, you can swipe away the notification will the app is open and it will revert to correct behavior for 1 stop.

Other apps (podcast addict, Google music) stop every time with Bluetooth.

**Comment by innesst** [comment]
Turning off the notification entirely in the system makes it so it won't stop even the first time after a force stop.

**Comment by PaulWoitaschek** [comment]
Is stop the same to you as pause?

**Comment by innesst** [comment]
Yes. I just have 3 buttons: skip fwd, pause and skip back.

On Jan 4, 2019 1:40 AM, "Paul Woitaschek" <notifications@github.com> wrote:

Is stop the same to you as pause?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PaulWoitaschek/Voice/issues/778#issuecomment-451364154>,
or mute the thread

**Comment by PaulWoitaschek** [comment]
It's weird.
I have a cheap bluetooth headset and it correctly sends play / pause events.
I also have a JBL speaker and it constantly fails to send the correct event. So while playing it sometimes sends "play" events.

I fixed this by treating play and pause as a "playPause".
