### ISSUE TITLE
Playback hangs after the end of a file

### ISSUE THREAD

**Issue by knochenhans** [PaulWoitaschek/Voice#779]
App-Version: 3.6.3
Phone Name: Motorola Moto G (Falcon)
Android Version: 9

Hi, I just switched to Android 9 and ran into a bug: Playback hangs after the end of every audiobook file. When I press the play button, I see it turning into the pause button shortly until it turns back to the play symbol again. Switching to a different track doesn’t help. I can only kill and restart the app then, after playback is normal until the then current file ends.

**Comment by versavius** [comment]
I have had this issue happen part way through playing a book and I had to restart the phone to fix it, I thought it was just me, but I am on 8.0.0

**Comment by thedbexp** [comment]
This also happens for me. If I hit the end of an audiobook, the app gets stuck and I cant start another book until I force kill the app or restart the phone. Last time I found it also works to rewind to some earlier part of the book and start playing from there. It's like it goes into limbo on the end of the audio

**Comment by PaulWoitaschek** [comment]
Is this fixed in the latest rc? https://github.com/PaulWoitaschek/Voice/releases/tag/4.0.0-rc8

**Comment by thedbexp** [comment]
ya, seems to work for me on this release. tested before and after from fresh boot. the difference appears to be that it pauses playback at the end of the track now rather than staying in play mode, but that might just be a visual difference.

**Comment by versavius** [comment]
> ya, seems to work for me on this release. tested before and after from fresh boot. the difference appears to be that it pauses playback at the end of the track now rather than staying in play mode, but that might just be a visual difference.

I have encountered this actually, where i'll get to the end of a track and it pauses and the only way i have found to fix it is to reboot my phone.

**Comment by thedbexp** [comment]
did you try 4.0rc8 at the above link? it fixes the issue on my phone.

**Comment by PaulWoitaschek** [comment]
If this is still present in the latest version, please comment.
