### ISSUE TITLE
Feature request: Google Maps media integration

### ISSUE THREAD

**Issue by hudcap** [PaulWoitaschek/Voice#780]
Are there any plans to integrate this awesome app with Google Maps's new media integration?

**Comment by adriancampos** [comment]
Any idea if Google's exposed an API for this yet? I don't see anything in the docs. Is it using Slices? Or something Maps-specific?

I'd be interested in trying to implement this, but I can't find anything online about it besides the fact that Spotify and Google Play Music support it.

**Comment by test2a** [comment]
about that, where are we on the android auto front? i am unable to find any information about that, granted i dont have access to any car that supports the android auto but still,

**Comment by rejhgadellaa** [comment]
@test2a: Android Auto should work. I use it on my phone (Android Auto standalone app, my car doesn't have AA).

4.x fixed the issue where AA would become unresponsive when playing a book in Voice so everythings perfect now 👍

**Comment by adriancampos** [comment]
@PaulWoitaschek I don't believe this issue's fixed yet. @hudcap and I are referring to the integration in the Google Maps phone app during navigation, not specifically Android Auto integration.

If "Snow media playback controls" in Navigation Settings is checked, a music app's icon shows up during navigation.
![image](https://user-images.githubusercontent.com/6026391/50731772-b6348900-1121-11e9-8835-016bb0272767.png)

Clicking it brings embeds a mini player into the bottom tray, which can be expanded to a basic browser not unlike Android Auto's new browse design.
![image](https://user-images.githubusercontent.com/6026391/50731770-b03ea800-1121-11e9-98ce-0efa9a943aac.png)

I've only seen Google Play Music and Spotify support it, so it may not be available to third party apps yet.

**Comment by PaulWoitaschek** [comment]
Please comment if you hear about an API for that.

**Comment by keradus** [comment]
I was willing to open a ticket for this feature, yet I have found this instead. As the feature is not there yet, can we reopen this ticket, or shall I make a new one ?

**Comment by PaulWoitaschek** [comment]
@keradus If you have found an API yet or any news that this can be somehow integrated for 3rd party apps, you can open a new ticket.

**Comment by PaulWoitaschek** [comment]
From a Dev perspective I don't want to keep tickets open that are impossible to implement.

I expect users to search for a ticket, find it and read it.

It looks like there is simply no public API and it's rather a commercial feature for the big players.
