### ISSUE TITLE
[Beta] Voice keeps crashing

### ISSUE THREAD

**Issue by 0rAX0** [PaulWoitaschek/Voice#786]
Since the last beta update I can no longer launch Voice, and it keep crashing throughout the day and displaying the Android banner "Voice has stopped"

I tried clearing out the cache but it didn't do anything, I didn't clear the data because I would lose the progress. Also, I sent feedback/reports through the Android feedback mechanism but I'm not sure if it reaches you. So tell me if you want adb logs or something.

App-Version: 4.0.0-rc4
Phone Name: Xperia X
Android Version: 8.0

**Comment by PaulWoitaschek** [comment]
Unfortunatelly that's the think with beta, I did not care too much about data migration so there might be  no way around a reset.
Sorry!
