### ISSUE TITLE
[Feature Request]: Tiered Interface for Nested Subfolders

### ISSUE THREAD

**Issue by chyron8472** [PaulWoitaschek/Voice#794]
I would like the ability to have the interface support nested folders, so that I can place Author folders at the top level, and when tapped it shows the Books' folders within. 

This is the one sticking point that keeps my wife from using Voice, and I admit I only put a small handful of books at a time on my device because they can not be nested by author (or series or whatever). To implement support for a tiered folder structure would clean up the folder list when a large number of books are added.

**Comment by PaulWoitaschek** [comment]
#809
