### ISSUE TITLE
Feature Request: More Themes and Custom Day/Night choices

### ISSUE THREAD

**Issue by Riotous** [PaulWoitaschek/Voice#795]
After trying out the 4.0.0 RC, I can definitely say that I like where Voice is going, but there's a lack of theme support that is keeping Voice back from being really customizable.

Right now you guys have a Day and Night theme and I think that's fine as a start but there needs to be more variety in the choice of themes. The Day theme is a very stark white, and the Night theme is a dusky blue. I think you guys should also add the following kinds of themes to make Voice more fun. 

- AMOLED, for those who use that screen.

- COFFEE, for a nice brown, earthy tone. 

- SOLARIZED LIGHT, for bright with a splash of color. 

- SOLARIZED DARK, for a readable dark green theme with color. 

- INDUSTRIAL, grey shades and black for those who like it dark. 

- SPRING, maybe some pastel light shades for people with bright personalities. No white!

- FOG, for those who want a grey theme that isn't too dark but still readable. No black!

- FALL, lots of red, orange, and yellow to evoke the season. 

- OCEAN, a variety of blues to make a not too dark, not too light, calming and readable experience.

Just my suggestions. Anybody can add to these! And finally, a way to choose which one of these themes will be your day and which one will be your night theme if you choose the day/night option.

@0rAX0 does this sound like something you'd be willing to add to Voice?

**Comment by PaulWoitaschek** [comment]
I don't want voice to be really customizable. I want to provide good defaults and don't distract the user.

**Comment by PaulWoitaschek** [comment]
I'm all in for creating an AMOLED theme and using it as the night theme on AMOLED devices.

**Comment by Riotous** [comment]
@PaulWoitaschek "too customizable" would be the ability to move things around, skin support to change the UI, remove and add buttons, etc. This is just about changing the color of the UI to suit more than a few tastes. @0rAX0 had some really nice multicolored themes in another issue that could still be used. 

I think a few more themes would be just enough to satisfy most users, and I figured since you have a designer, he could make a few more themes. But hey, it's your project.
