### ISSUE TITLE
Support Translation page gives 404 Page not found

### ISSUE THREAD

**Issue by ninad458** [PaulWoitaschek/Voice#797]
Please include the following details in your bug report:

Preferences->Support>Translations

**Comment by ninad458** [comment]
I would like to fix it and create a Pull request.

**Comment by PaulWoitaschek** [comment]
Please open a PR :+1:

**Comment by PaulWoitaschek** [comment]
Apparently it's already fixed upstream:
https://github.com/PaulWoitaschek/Voice/commit/9b189f0c8c01ad550836ee63e2ef5d3fe26ac2a7
