### ISSUE TITLE
[Project Setup] Android Studio complains about unsupported modules

### ISSUE THREAD

**Issue by Plastix** [PaulWoitaschek/Voice#799]
I'm trying to setup this project on a new laptop. For some reason Android Studio complains and won't let me compile the project:
<img width="385" alt="screen shot 2018-12-15 at 9 05 15 am" src="https://user-images.githubusercontent.com/1526881/50045576-f2f0f100-0049-11e9-894d-f0006759f87d.png">

How am I supposed to import this project into Android studio?

cc @PaulWoitaschek

**Comment by PaulWoitaschek** [comment]
Can you try AS 3.3 or 3.4? I assume it can't handle kts gradle files without checked in iml files.

**Comment by Plastix** [comment]
Looks like I need to be on AS 3.3 because the AGP is 3.3. I'm running 3.3-RC2 now and everything is good. Sorry for the confusion.
