### ISSUE TITLE
Suggestion: Move Play Button in Main Interface

### ISSUE THREAD

**Issue by innesst** [PaulWoitaschek/Voice#804]
Please include the following details in your bug report:

App-Version: 4.0 rc8
Phone Name: Pixel 2
Android Version: 9

The play button in the main Interface is on the bottom right. But that's exactly where the picture in picture map window is when using Google Maps navigation. If the play was moved to the center (or left), it could be used without having to first move the PIP window. My primary use for this app is in car and very frequently with navigation, so this is often an issue.

**Comment by 0rAX0** [comment]
You could move the PIP window (that's why they made it moveable and didn't make the button so) or you could use Android Auto on your phone which handles both quite nicely. At least that's what I do.

**Comment by PaulWoitaschek** [comment]
Sounds like a good solution to me :+1:
