### ISSUE TITLE
Color-code skipped content

### ISSUE THREAD

**Issue by mallove** [PaulWoitaschek/Voice#807]
Display content that has been skipped.  In the below [photo edited] screenshot, the user has skipped ahead, which is shown by the color of the shuttle slider:

![voice-screenshot-showing-wishlist-item--skipped-section-screenshot_20181220-123942-50-percent](https://user-images.githubusercontent.com/17302884/50302046-ed831480-0456-11e9-9fe6-108ef0f843c7.png)

**Comment by PaulWoitaschek** [comment]
It would confuse me as it looks like a buffered state.

**Comment by mallove** [comment]
> It would confuse me as it looks like a buffered state.

Ah, I see.  That's no good then.  What about using a different color than the buffered-state? E.g.,

![bthird-color--not-buffered--but-skipped--50302046-ed831480-0456-11e9-9fe6-108ef0f843c7](https://user-images.githubusercontent.com/17302884/51396616-67b5c000-1b0d-11e9-9635-5f94221063b6.png)
