### ISSUE TITLE
[Feature request] book grid view

### ISSUE THREAD

**Issue by droidberg** [PaulWoitaschek/Voice#808]
the latest update to voice is amazing but it seems to have taken away the grid view. any chance it could be brought back? maybe add the ability to change the grid from 2 to maybe 4 or 5? it would be great for bigger devices and i love the look.

**Comment by PaulWoitaschek** [comment]
@0rAX0 Any design suggestions for a grid mode?

**Comment by 0rAX0** [comment]
> @0rAX0 Any design suggestions for a grid mode?

On it. :)

**Comment by 0rAX0** [comment]
First we need to move that book-adding icon to a 3-dots menu (after actually having a 3-dot menu 😄 ) then either an implementation like Castbox 3-dots menu > layout > Small Grid (4x4) | Large Grid (3x4) | List OR a single toggle either in the 3-dots menu on in the toolbar but we won't have a choice in grid size.

**Comment by 0rAX0** [comment]
![screenshot_20181227-122625](https://user-images.githubusercontent.com/1044370/50478774-59272d80-09d3-11e9-8a35-c30d56ecd5d9.png)
![screenshot_20181227-122636](https://user-images.githubusercontent.com/1044370/50478778-5f1d0e80-09d3-11e9-9dcb-1d9248116938.png)

**Comment by PaulWoitaschek** [comment]
It's gonna be a single toggle between list and grid.
Based on the screen dimensions I'll decide how many columns there will be.

What I'd like you to design is the actual grid view - how do the books look in a card.

**Comment by 0rAX0** [comment]
@PaulWoitaschek I was under the impression that a grid view is a grid of square photos like every player out there, but yeah, it could have some extra Voice features. I'll be back.

**Comment by PaulWoitaschek** [comment]
I don't find it that trivial. We have the following elements currently the list for each book:

* Author (optional)
* Book Name
* Cover
* Progressbar
* Time left
* Playing indicator (optional)

Now the question is: Do we display all these elements in the grid and how do we display them.

**Comment by 0rAX0** [comment]
How about this: 
![voice home grid -dark](https://user-images.githubusercontent.com/1044370/50487481-dd42da80-09fe-11e9-86e6-566875af9953.jpg)

It uses the same components with different dimensions, and displays pretty much everything without looking weird (I hope). 

Open to suggestions.

**Comment by satvikpendem** [comment]
I like that, it looks good.

**Comment by droidberg** [comment]
whoa! im really happy this picked up! my issue is with the limited option regarding the amount of books viewed per row. in phonograph the user is given the option to choose how many they want.

![screenshot_phonograph_20181229-144821](https://user-images.githubusercontent.com/16459442/50550708-23c84d00-0c2a-11e9-8b17-59b220412240.png)


it would be nice to be able to choose from 2 to maybe 4 or 5 books. this would make voice amazing on not only phones but tablets.

![screenshot_phonograph_20181229-144831](https://user-images.githubusercontent.com/16459442/50550717-2fb40f00-0c2a-11e9-968d-334e51a4c185.png)

**Comment by PaulWoitaschek** [comment]
@0rAX0 
Could you design something with less optimistic data?
It can't be really implemented like this because

* The author might not be present
* The title might not fit on a single line.

The grid items must have equal size else it looks really cluttered. If I just remove the author, it's really asymetrical or it has huge spaces between.
Also the black cover fallback doesn't harmony with the black cards on the black background.

**Comment by droidberg** [comment]
@PaulWoitaschek 

any chance you can have the text scroll? i have many audiobooks with long names and they never fully show. this is really not a problem for audiobooks but i also use your amazing app for podcasts. many of those have various seasons such as "the no sleep podcast". i have seen a few audio players that do this but i cant recall their names.

**Comment by PaulWoitaschek** [comment]
Implemented. In the grid, the name has now a maximum of 2 lines.
