### ISSUE TITLE
Library not updating

### ISSUE THREAD

**Issue by shaunmclean** [PaulWoitaschek/Voice#814]
Please include the following details in your bug report:

App-Version: 4.0.2
Phone Name: Galaxy Tab A
Android Version: 7.1.1

All new audiobook folders or files added to the Audiobook folders on the device storage are no longer being added to the Voice Library. Behaviour only started when app updated.

UPDATE: Confirm this functionality *does* work for my Pixel 1 Phone (Android 9). Wondering if the update broke Library updating for Android versions before 8?

**Comment by PaulWoitaschek** [comment]
Can you check if re installing the app solves the issue?

**Comment by PaulWoitaschek** [comment]
Fixed by 2f79c722c8435dc6b58a39b6322e56c226a4da75

**Comment by PaulWoitaschek** [comment]
Did you use the 4.1.0 version? You can find the APK in the GitHub releases.

**Comment by gwarser** [comment]
Maybe it's just slow? In my phone this is like 15s / book (30 files).
