### ISSUE TITLE
[bug?] update causes media rescan

### ISSUE THREAD

**Issue by droidberg** [PaulWoitaschek/Voice#816]
Please include the following details in your bug report:

App-Version: 4.1.0
Phone Name: Nexus 5, Pixel 2 XL
Android Version: Oreo, Pie

the last 2 updates have caused media re-scans which when you have around 300 folders can get pretty annoying. is this a bug? anyway this can be avoided?

**Comment by gwarser** [comment]
Probably https://github.com/PaulWoitaschek/Voice/issues/814

**Comment by PaulWoitaschek** [comment]
What is a media rescan for you?
How do you notice it?
