### ISSUE TITLE
[Feature request] Remove from started list

### ISSUE THREAD

**Issue by jony0008** [PaulWoitaschek/Voice#818]
In the latest release, the new Book Overview was added with a view of the books that is being listened to. I would like to be able to remove books from the new Book Overview, e.g. if I finished listening to it. 
Great work on the new design!

**Comment by PaulWoitaschek** [comment]
If you finished listening it, it will automatically move to the "Finished" list.

**Comment by jony0008** [comment]
@PaulWoitaschek I would still like to be able to remove it from the list, e.g. if I don't want too listen too it till the end

**Comment by PaulWoitaschek** [comment]
Currently only the 4 most recently listened books are shown in the overview.
All other will go to a "Show All" menu that will only be shown if there are more than 4 started books.

I think having a manual button here will lead to too much confusion.

**Comment by PaulWoitaschek** [comment]
Also if you really want it to go to the "Finished" list, you can just manually seek to the very end of the book.

**Comment by jony0008** [comment]
@PaulWoitaschek Good solution, I didn't know that only the 4 recently listened books were shown. Wil it be possible to bookmark books in the future? I want to bookmark books that I am most interested in listening too.

**Comment by PaulWoitaschek** [comment]
Interesting idea.
I think currently not as I want to keep the UX as simple as possible.
