### ISSUE TITLE
Add book more than 4, previous book only visible via show all

### ISSUE THREAD

**Issue by sfstag** [PaulWoitaschek/Voice#824]
Updated to VOICE version 4.1.2 from version 3 for Android Version 7.1.1

I have four books in the folder for my audio books.  When I add a fifth, one of the others disappears. Voice seems only able to display four books.  If I select show all, the fifth is displayed, one can play it, but cannot rename, do covers or do a bookmark.  This looks like a bug.  Could you please fix it soon.

BTW: The new UI took a little getting used to, but I finally learned to rename, etc.  The name keypad also took a little getting used to.

We have enjoyed this product for a long time, thanks for your help.

Phone Name: N/A (no phone capabilities)

**Comment by PaulWoitaschek** [comment]
Fixed by 1c4115259333459f6ae3c829d147d8dd68983ee8
