### ISSUE TITLE
Please make "show all" in the book list the default behavior or make it an option 

### ISSUE THREAD

**Issue by Riotous** [PaulWoitaschek/Voice#826]
The default behavior for Voice used to be "show all" by default but for some reason, the default behavior is to hide files and keep them behind a "show all" button. I don't know why this behavior was changed but it's kind of a pain for somebody who has many files. I just want to see all my files at once whenever I open Voice. 

Please consider making "show all' the default behavior when opening Voice or make hiding files optional in the settings.

**Comment by PaulWoitaschek** [comment]
This was implemented for a more focused experience. 
The bad experience with larger collections will be compensated by a search functionally and filter options in future updates.

**Comment by Riotous** [comment]
@PaulWoitaschek Why not compensate the "bad experience" with a toggle switch in the options? I can see a lot of people complaining about this in the new 4.2 version that just came out. I came here as soon as I realized it was doing this. Search and filter options can't possibly replace being able to see everything at once, especially if you're not sure what to search for or filter for.
