### ISSUE TITLE
Completed Books stay in in current

### ISSUE THREAD

**Issue by quizzmaster** [PaulWoitaschek/Voice#830]
As I saw the new sorting, I was happy, because it is easier to get an overview, what I already heard. After a few tries getting some completed books to be sorted like that I now open this issue. None of my books get marked as beeing completed, even if there are several ones at maximum duration.

I tried listening to the last 30s of some books, but they still show up in current.

App-Version: 4.2.0
Phone Name: OnePlus 6T (A6013)
Android Version: 9.0 (Pie)

**Comment by droidberg** [comment]
i too have this issue. several books and podcasts are completed/up to date and still displayed in the current tab.

**Comment by sliddrip** [comment]
Hello,

I am a big fan of the app, I too am having this issue

**Comment by PaulWoitaschek** [comment]
Should be fixed by 87bc009b1621aa212920e171459b7cee80bfb6c2
