### ISSUE TITLE
Thank you for creating, driving, and maintaining a wonderful tool 💯

### ISSUE THREAD

**Issue by chowdhurian** [PaulWoitaschek/Voice#832]
~Please include the following details in your bug report:~

~App-Version:~
~Phone Name:~
~Android Version:~

I wanted to thank you for creating, driving, and actively maintaining an app that I and many others find super useful! Open source projects take time and effort; I want to call that out and say I really appreciate it.

I have no feature requests. I use it for both music and audiobooks.  I find it easy to use and intuitive. I listen to music in entirely in albums, so this player is perfect as it sees a directory and marks it as a "book".

You're awesome 💯

(Feel free to close the issue at any point lol)

**Comment by PaulWoitaschek** [comment]
Thank you! :heart:
