### ISSUE TITLE
Add a Circular Seekbar

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/Voice#833]
Create a custom view which can be dragged in a circle for increasing numbers.
Use this view for the Volume dialog

**Comment by egvimo** [comment]
Will it also be possible with this view to set more granular values?

For me e.g. the speed of 1,1 is to slow and 1,2 is to fast. I'd like to have the speed set to 1,15.

When this Feature will be implemented? It was planed for 4.4, but the version is already on 5.

**Comment by PaulWoitaschek** [comment]
No this won't be implemented at all. 

> For me e.g. the speed of 1,1 is to slow and 1,2 is to fast. I'd like to have the speed set to 1,15.

You can just set a more granular value, there is no limitation. The number that's shown is just rounded but voice uses the exact value you have set.

**Comment by egvimo** [comment]
How can I do that? How can I set the value? I only can use the slider to change it. Is there a way to do that manually?

**Comment by PaulWoitaschek** [comment]
No there is not. But the slider is way more accurate than the progress bar, I could pick a minute on a 14 hour audiobook.

**Comment by egvimo** [comment]
Would you show the second decimal place, so that the accuracy is visible? Without it there could be a deviation by 10 %.
