### ISSUE TITLE
[Enhancement request] Add percentage of book covered

### ISSUE THREAD

**Issue by JoelAbees** [PaulWoitaschek/Voice#834]
Please include the following details in your bug report:

App-Version:
Phone Name:
Android Version:

Hi paul. First of thanks for this amazing app. While I appreciate the fact that it is a free app, I have a suggestion to improve it just a tiny bit. 

You can display percentage of the book covered so far. 

Thank you,
Joel

**Comment by jaqjacek** [comment]
+1 for this sugestion

**Comment by GitBugit** [comment]
I would not only prefer to have a percentage indicator but also one that shows exactly how much time I listened already and how much I have left

**Comment by pedrojvaz** [comment]
Hopefully, this can be added soon

**Comment by PaulWoitaschek** [comment]
I try to follow a minimal design principle and therefore don't want another element in the UI.
There is already the progress bar so you can estimate the percentage.

**Comment by ronilaukkarinen** [comment]
This is a bummer. Percentage is a must-have.
