### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by PumpkinEscobar305** [PaulWoitaschek/Voice#835]
Please include the following details in your bug report:

App-Version: 4.2.1
Phone Name: OnePlus 3T
Android Version: 8.0

1. I would like to see the play button being bigger to avoid mis-hits on skip or next. 

2. If you swipe up on the chapter bar while in the play screen, it'll swipe up and immediately select a chapter rather than just swipe up. 

3. AMOLED black theme. 

4. Remember where you were in each chapter to help with mis-hits on next, so you can press previous button and go back to where you were.

5.  Google Drive or some other way of streaming. 

6.Combine with the guy who created the Lithium eReader app and become the best Audio/eBook app there is. 

Cheers, 
Ryan

**Comment by jtagcat** [comment]
Please brake up your points, one issue per problem. Also check for duplicates. You are the 4th person to create an issue with 5. in it.

Number 6: You can't 'just combine stuff'. It's not PPAP.

**Comment by PaulWoitaschek** [comment]
> Number 6: You can't 'just combine stuff'. It's not PPAP.

😄 Made my day! Please open separate issues :)
