### ISSUE TITLE
Lose audio focus after notification

### ISSUE THREAD

**Issue by peterandreasrothe** [PaulWoitaschek/Voice#837]
Hi! 

In having some problems with Jaybird headphones and Voice. If I receive a notification the app pauses volume to play the notification but afterwards there's no sound even though voice is still playing. If I activate and close Google assistant the audio comes back. It doesn't happen in other apps like audible and Google podcast. 

Peter

Please include the following details in your bug report:

App-Version: 4.3.0
Phone Name: Pixel 2
Android Version: 9

**Comment by PaulWoitaschek** [comment]
Can you check if it's still not working on the latest version?

**Comment by peterandreasrothe** [comment]
It seems to be working now, thank you :-)
