### ISSUE TITLE
Main play/pause button stuck in wrong state

### ISSUE THREAD

**Issue by gwarser** [PaulWoitaschek/Voice#838]
After finishing book in minimized Voice, play/pause button stuck in playing state (pause icon visible)

My STR:

- start playback at the end of last chapter
- minimize Voice
- switch to other _desktop_ if you have Voice widget on current one
- first book finishes
- open Voice
- "pause" icon visible on button

Button stays in this state even after navigating to second book. 

App-Version: 4.2.1 and 4.3.0
Phone Name: L65
Android Version: LineageOS 14.1

**Comment by gwarser** [comment]
Seems to happen only when playback speed is other than 1.0x

**Comment by PaulWoitaschek** [comment]
I assume this is working in the latest version now.
