### ISSUE TITLE
Suggestion: finished books should start on first chapter, not last

### ISSUE THREAD

**Issue by thw0rted** [PaulWoitaschek/Voice#840]
App-Version: latest
Phone Name: Moto Z
Android Version: 8.0

When I finish a book, then later open it again, the last chapter of the book is selected. If I played it all the way through, and come back to it, it's because I intend to start it over from the beginning. So, I think it makes more sense to select the first chapter automatically, in that case.

**Comment by PaulWoitaschek** [comment]
Well the book is finished and therefore it is shown as finished. If you start playing a finished book, Voice will automatically select the very first chapter of the book.

**Comment by thw0rted** [comment]
I didn't notice that it was at the end of the last chapter, and didn't try playing it again. Works fine like it is - thanks for the tip!
