### ISSUE TITLE
Provide more information via bluetooth

### ISSUE THREAD

**Issue by egvimo** [PaulWoitaschek/Voice#841]
App-Version: 4.3.0
Phone Name: Google Pixel 2
Android Version: 9

When I listen to a book via bluetooth in the car, I only see the current chapter. See photo:
![img_20190203_150714](https://user-images.githubusercontent.com/5247100/52198633-c1cfb880-2863-11e9-93e6-8c15574587f1.jpg)

There is no information about the playback time or the author.

As comparison here a photo of the playback via AntennaPod:
![img_20190203_150626](https://user-images.githubusercontent.com/5247100/52198650-cd22e400-2863-11e9-815b-f1d4d3e03e88.jpg)

PS: Maybe it has something to do with it. Voice don't always update the information about the playback. Sometimes the chapter information does not jumps to the next chapters.

**Comment by egvimo** [comment]
I tried it again today and it seems to be working now. All information is displayed properly.

I can't tell what it was, but it seems to be a problem with the OS. Because other users have exactly the same problem, but in other apps (see e.g.: https://github.com/AntennaPod/AntennaPod/issues/2498).

The Android March update had included a Bluetooth improvement for the Pixel devices. Maybe that solved the problem.

**Comment by egvimo** [comment]
But I still have the problem that the info is not updated and just keep displaying the same track.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
