### ISSUE TITLE
Errors in displaying the book duration.

### ISSUE THREAD

**Issue by LeonidRosin** [PaulWoitaschek/Voice#847]
The chapter of the book is played for 2 seconds more than the actual duration. See attached files.

App-Version: 4.3.2
Phone Name: Samsung A7 2017
Android Version: 8.0.0

![screenshot_20190219-172337_voice](https://user-images.githubusercontent.com/17572756/53027474-a5d83380-346d-11e9-83f3-9c19e65859c3.jpg)
![screenshot_20190219-172329_voice](https://user-images.githubusercontent.com/17572756/53027475-a670ca00-346d-11e9-89e0-02d6965bfc31.jpg)

**Comment by sengsational** [comment]
I made note of this in #870

**Comment by PaulWoitaschek** [comment]
I assume this is fixed in the latest betas.
