### ISSUE TITLE
App sees files and book cover but will not play mp4

### ISSUE THREAD

**Issue by voxdayhey** [PaulWoitaschek/Voice#849]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: LG G5
Android Version: 8.0.0

I followed the instructions for Android and added the audio files into Voice Audio Book Player but the play button will not work.  The MP4 files appear to have been added okay. I see the book cover/file in the player but when I click play nothing happens.

**Comment by Mickali** [comment]
I to have the same issue. Same phone and Android version is 8.1.0

**Comment by voxdayhey** [comment]
Get the app Smart Audiobook. Works flawlessly

**Comment by test2a** [comment]
@voxdayhey do one thing. Force quit the app and restart it. It will work

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
