### ISSUE TITLE
Application crashes when the screen goes off

### ISSUE THREAD

**Issue by clemthi** [PaulWoitaschek/Voice#852]
Hi,
I've noticed the application keeps crashing on my phone when the screen turns off. I've tried basic stuff (such as rebooting phone, clearing the data, reinstalling the app), but the problem remains.
Is there some king of error log I could provide?

App-Version: 4.3.2
Phone Name: Samsung Galaxy S7 (SM-G930F)
Android Version: 8.0.0

**Comment by PaulWoitaschek** [comment]
I assume this is fixed in the latest betas.
