### ISSUE TITLE
Equalizer disables after pause

### ISSUE THREAD

**Issue by revelous** [PaulWoitaschek/Voice#853]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: Google Pixel 3
Android Version: 9 (March 2019 Security patch)

Sometimes, after pausing the an audiobook, the equalizer setting is disabled. To re-enable, one must jump into the equalizer settings and then it takes effect again.

**Comment by PaulWoitaschek** [comment]
Thanks for your report! As the equalizer is no longer part of Voice, this issue is obsolete.
