### ISSUE TITLE
Night Theme: Edit and Remove bookmark not readable

### ISSUE THREAD

**Issue by ntan234** [PaulWoitaschek/Voice#854]
Please include the following details in your bug report:
Night Theme: Edit and Remove bookmark options text should be in white
![bookmark](https://user-images.githubusercontent.com/5238025/53862755-a820bd00-402b-11e9-8fa1-2a189eb51198.jpg)

App-Version: 4.3.2
Phone Name: Samsung Galaxy S8 SF-G950
Android Version: 8.0

**Comment by Takslak** [comment]
Experiencing the same issue, although mine is a bit more readable. 
![Screenshot_20190309-005838](https://user-images.githubusercontent.com/7125398/54060729-7e6fbd80-4206-11e9-9efc-6de93a8f6bd1.jpg)

App-Version: 4.3.2
Phone Name: OnePlus 5T A5010
Android Version: 9

**Comment by PaulWoitaschek** [comment]
This is fixed in Voice 6+.
