### ISSUE TITLE
[Enhancement] Remove letter-spacing

### ISSUE THREAD

**Issue by SixFingeredAmish** [PaulWoitaschek/Voice#856]
Hi there,

First of all, love the app. It is nice and minimal and straightforward to use.

However, most of the text in the app has letter-spacing/character-spacing which makes it look bad. Generally, letter-spacing should only be used for uppercase letters.

If this isn't intentional, I think it should be removed. If it is intentional, I think there should be an option to turn it off.

Thank you.

![image](https://user-images.githubusercontent.com/2727095/54161946-1640f780-4411-11e9-85b5-12ae4c6a3b82.png)
![image](https://user-images.githubusercontent.com/2727095/54161951-1a6d1500-4411-11e9-9990-24fb67538087.png)
![image](https://user-images.githubusercontent.com/2727095/54161955-1d680580-4411-11e9-8572-7f26eb5891fb.png)

**Comment by PaulWoitaschek** [comment]
If I'm not completely misunderstanding, each font style has letter spacing in material design:
https://material.io/design/typography/the-type-system.html#type-scale

**Comment by SixFingeredAmish** [comment]
Yes! But letter spacing for anything other than BUTTON and OVERLINE are so small that they are barely perceptible.
