### ISSUE TITLE
[Bug] Player not resuming where I left off

### ISSUE THREAD

**Issue by yutsoku** [PaulWoitaschek/Voice#857]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: Pixel 3 XL
Android Version: 9

When I stop listening it feels like the longer I listen and then resume the playback will be 1-10 minutes ahead of where I left off or behind where I left off  I suspect this may have something to do with me listening on 1.4x speed and the math of where I'm leaving off is not matching the math for the playback speed.

This started after the app was updated to the new UI and has been happening for multiple books and it's getting quite frustrating figuring out where I left off as I spend almost half the time skipping around finding where I left off in comparison to listening.

**Comment by test2a** [comment]
Yep. Same thing. This happens to me more with sleep timer and set bookmark. It never does and I have to scrub a lot to find the last position. Sigh

**Comment by Coehill** [comment]
I'm having the same issue too.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
