### ISSUE TITLE
global playback speed

### ISSUE THREAD

**Issue by test2a** [PaulWoitaschek/Voice#860]
a quality of life improvement but there is no global playback speed setting if you have to listen in any speed other than 1x.

**Comment by PaulWoitaschek** [comment]
I understand that this is a need of some people but I also think that the vast majority people just plays at 1.0 speed so I don't want another setting.

**Comment by CreamyCookie** [comment]
> vast majority people just plays at 1.0 speed

Also, without statistics I wouldn't be so sure that the vast majority listen at 1.0 speed. If 30% listen at 1.5 speed, would that be enough for you to warrant that simple addition?

> I don't want another setting.

I understand that there's some small maintenance cost associated with each new option but, in my opinion, Voice has far too few options. When I open the settings menu, there are 4 entries. 

I think these would absolutely make sense:

- default playback speed
- a slider for setting the new fade out time (I personally dislike fade out in general.)
- a toggle for whether or not you want the timer to always start (given that it's not already running) when you press play

I wouldn't even mind having to edit a text config file for these.

Anyway, thanks for creating and maintaining Voice. It's an awesome audiobook player! =)

**Comment by CreamyCookie** [comment]
> vast majority people just plays at 1.0 speed

Without statistics I wouldn't be so sure that the vast majority listen at 1.0 speed. If 30% listen at 1.5 speed, would that be enough for to warrant the addition?

> I don't want another setting.

I understand that there's some small maintenance cost associated with each new option but, in my opinion, Voice has far too few options. When I open the settings menu, there are only 4 entries. 

I think these would absolutely make sense:

- default playback speed
- a toggle for whether or not you want the timer to always start (given that it's not already running) when you press play
- a slider for setting the new fade out time (I personally dislike fade out in general.)

I wouldn't even mind having to edit a text config file for these.

Anyway, thanks for creating and maintaining Voice. It's an awesome audiobook player! =)

**Comment by PaulWoitaschek** [comment]
It's mostly not about the maintenance cost. I'ts about providing good defaults and having a simple ui. I'd accept a PR that reads from a settings file.
As of android Q I don't know any place for an external config file to go.

**Comment by egvimo** [comment]
I would also appreciate a global setting for playback speed. Maybe it could be included in some 'Advanced Settings' like discussed in #859, or like Android is doing in the settings:

![Android-O-display-settings](https://user-images.githubusercontent.com/5247100/78470750-f838ea00-772b-11ea-8bdd-164448141c73.jpg)

**Comment by CreamyCookie** [comment]
> As of android Q I don't know any place for an external config file to go.

Is this about the "Scoped storage" change? Wow, seems like it's a really and breaking drastic change. There's apparently an issue with a lot of discussion: https://issuetracker.google.com/issues/128591846

I really hope they reconsider. (On the other hand it totally makes sense that users have to agree to which top-level folders apps can write.)
