### ISSUE TITLE
[EVOLUTION] Bluetooth mod

### ISSUE THREAD

**Issue by flamme-demon** [PaulWoitaschek/Voice#861]
Hello and thank you for this beautiful project. How do I donate to the team?

I would also like to submit a request for evolution to take into account the broadcast of audio in Bluetooth.
I don't know about you, but when I commute home work I would love to be able to listen to my books in the car. But this is unfortunately impossible at the moment.

Can you think about this improvement?

**Comment by markusd112** [comment]
Why is it impossible? I am using Voice in my car, where the smartphone is connected via bluetooth to my radio/hands free kit and the audio stream of my smartphone is sent via bluetooth to my radio and the sound is played over the car speakers. That work's great.

**Comment by 0rAX0** [comment]
Maybe you're talking about a different project?! Because the name of the project is Voice and it works over bluetooth as well as every other player out there. Marking this as invalid, unless you have something to add.
