### ISSUE TITLE
Day theme does not show chapter change icon

### ISSUE THREAD

**Issue by test2a** [PaulWoitaschek/Voice#862]
https://ibb.co/1Rct19D

 Currently the night theme shows the chapter change caret correctly but day theme does not.

Beyond this, I am suggesting to moving the chapter change position to the top button or sidebar because we do not need to have interaction with chapters "usually". As I have already said on other issues, audiobooks are linear and we listen to one from start to finish in one way. In case we have to get back to a position,  then we should be able to get to some chapter. Current implementation is too error prone and many times one instead of hitting the pause play button, we select the chapter list and selects some chapter.

**Comment by test2a** [comment]
https://ibb.co/gwwfpt8

Same with the theme selection

**Comment by PaulWoitaschek** [comment]
Fixed in 5.x?
