### ISSUE TITLE
app loses position 

### ISSUE THREAD

**Issue by test2a** [PaulWoitaschek/Voice#863]
i am listening to  a book and i am say on chapter 3 after starting from chapter 1. the phone screen is off and "when" i turn the screen on, i loose the position on chapter 3 and the app starts from chapter 3 again. No warning, no nothing. the app is going correctly but if i open the screen, it resets to current chapter.
Now, if i open it once, it will not happen again for some time.

**Comment by markusd112** [comment]
I have the same problem. Voice is playing a file in background. When opening Voice, the played file starts again from beginning

**Comment by CreamyCookie** [comment]
I'm having the same problem. At first it was me accidentally touching the position slider, but it has happened so often that I'm sure it's actually the app that's just resetting the position for some reason when the screen is turned on.

**Comment by PaulWoitaschek** [comment]
Should be fixed in 5.0.0

**Comment by CreamyCookie** [comment]
Haven't tested yet, but thanks @PaulWoitaschek
