### ISSUE TITLE
Playback stops after a certain time, when screen is off

### ISSUE THREAD

**Issue by sojusnik** [PaulWoitaschek/Voice#865]
The playback regularly stops normally after about 30 minutes, when the screen is turned off.

The sleep timer is deactivated and so is the battery optimization (as mentioned [here](https://github.com/PaulWoitaschek/Voice/issues/815)).

Tried with different sleep timer intervals (30, 60, 90 minutes), the sleep timer was deactivated though, but the playback still stopped after around 30 minutes.

Could be connected to [this issue](https://github.com/PaulWoitaschek/Voice/issues/651), but in my case the app always pauses after more or less 30 minutes and not randomly.

App-Version: 4.3.2
Phone Name: OnePlus X
Android Version: 8.1.0 (LineageOS 15.1)

**Comment by Trevis42** [comment]
I've had the same issue when the screen times out on my phone. It will play as long as the screen is on, but once off it stops after about 30 seconds. It's probably some activity code that was implemented incorrectly not allowing the app to stay active in the background/while device is sleeping. 

Hopefully this will get fixed soon. I have hour long drives that would be great for finishing my books but I can't do that when the apps dies after my screen sleeps. 

Phone: Samsung s8
Android: 9

**Comment by jtagcat** [comment]
It's battery optimization. See https://dontkillmyapp.com

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
