### ISSUE TITLE
cover image wrong selection 

### ISSUE THREAD

**Issue by test2a** [PaulWoitaschek/Voice#869]
as you can see from the following screenshots, i have a folder with TWO cover images. 
1. normal cover.jpg and 
2. cover_thumb.jpg

voice ALWAYS accepts the thumbs version and as a result, the images appear blurred because technically it is stretching a thumbnail image on the full screen.

![Screenshot_2019-04-18-17-21-28-0243192348](https://user-images.githubusercontent.com/39449563/56400449-96a91280-6271-11e9-86c3-5792c861a234.png)
![Screenshot_2019-04-18-17-20-29-0565444356](https://user-images.githubusercontent.com/39449563/56400450-96a91280-6271-11e9-8beb-3fd979223c67.png)
![Screenshot_2019-04-18-17-20-42-0541351378](https://user-images.githubusercontent.com/39449563/56400452-96a91280-6271-11e9-8650-ec80dadf9245.png)
![Screenshot_2019-04-18-17-20-48-0370485027](https://user-images.githubusercontent.com/39449563/56400453-9741a900-6271-11e9-8886-3ca83c7a98db.png)

**Comment by PaulWoitaschek** [comment]
As a hotfix it should work to rename them so the thumb does not appear before the actual cover.  
In the future we might select the one with the largest resolution.

**Comment by test2a** [comment]
thats fine. i dont mind the choice of cover image because i hardly look at it. Been using the app daily for the past 2 years and almost all of it was spent while the screen was off. ;-)
What i am asking is, that the app *should* either choose the highest size jpg in the folder or one that is **not** thumb. that's it because most of the major audiobooks contain multiple images and they are set for specific use.

**Comment by PaulWoitaschek** [comment]
This is fixed in 6.x
