### ISSUE TITLE
App opens TCP connections to AWS servers with no means of disabling them

### ISSUE THREAD

**Issue by arcanemachine** [PaulWoitaschek/Voice#872]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: Xiaomi Redmi Note 5 Pro
Android Version: 9.0 (Pie, Havoc OS ROM)

This app opens TCP connections to various Amazon Web Services EC2 instances when it is running (This can be viewed in the Net Monitor app on F-Droid). There is no way to disable these connections without manually disabling the "Internet" and "View Network Connections" permission in the APK itself* (thankfully, this does not cause the app to crash).

*Even with wifi/mobile data usage disabled in the app settings, these connections are still opened. I am not sure if this is due to a bug in my ROM (or Pie itself) or if the apps have a means of circumventing the data blockage even with the data usage toggles disabled.

Thank you.

**Comment by PaulWoitaschek** [comment]
Where did you get the apk from? Can you monitor these requests? Voice uses only Fabric, maybe it's that?

**Comment by arcanemachine** [comment]
The APK is from GitHub, I am having trouble exporting a list of the connections, but they are all Amazon AWS servers.

Here are a few IPs (copied by hand):

50.19.219.28
184.72.223.78
54.235.151.114

These Amazon instances are located in Eastern USA so they may not be the same if someone is logging connections outside the USA.

As mentioned previously, these connections are made even with wifi and mobile data usage disabled for the app in the App Settings menu. AFWall is no help on Pie either.

I have tested it on another device running Android Pie (Galaxy S5 klte on recent Lineage OS nightly build) and the same thing happens (s5 isn't rooted though, so no AFWall).

...

I just tested it on my 2013 Nexus 7 tablet (WiFi only) running Nougat, and it's not making any connections whatsoever. Strange. Dunno if it's because it's running Nougat... Also has a tablet layout and is WiFi only, though I doubt that has anything to do with it.

...

At any rate, if anyone who cares is affected by this, my current workaround is to download the APK Permission Remover app from APKPure (The Play Store version got pulled) and use it to manually disable the "Full Network Access" and "Check Network Connections" permissions, save the apk, then install it (This breaks some apps, but does not affect Voice <3 ).

Well, that's my info dump. I hope there's some helpful information in here for you to work with.

Great app btw. Thanks again.

**Comment by PaulWoitaschek** [comment]
I create the apk's for github myself. 

Can you inspect the actual traffic with something like mitmproxy?

Also I attached the version that gets built for fdroid to the latest release. That one doesn't contain fabric. Can you check if that one still opens connections?

**Comment by arcanemachine** [comment]
I'm not sure what mitmproxy is but can look into it if needed (I am also unexperienced with packet sniffing programs in general, Net Monitor is a pretty out-of-the-box solution).

At any rate, the open source release you linked doesn't show any connections on Net Monitor.
