### ISSUE TITLE
New playstore icon

### ISSUE THREAD

**Issue by PaulWoitaschek** [PaulWoitaschek/Voice#873]
With the new play store icon format, we need a new asset

https://developer.android.com/google-play/resources/icon-design-specifications

So it's basically this one but on a plain background https://github.com/PaulWoitaschek/Voice/blob/master/Images/logo.png

@0rAX0

**Comment by 0rAX0** [comment]
Hey @PaulWoitaschek it's been a while :) 

Does this work?

<img width="512" alt="Voice Icon (Play Store)@512" src="https://user-images.githubusercontent.com/1044370/57144114-3ad5a200-6db8-11e9-9af6-b979df50d589.png">

**Comment by PaulWoitaschek** [comment]
Thanks :) Really busy currently so work on voice is kinda paused.
Can you send me the source of the image so I can attach it to the project for future modifications?

**Comment by 0rAX0** [comment]
No worries, best of luck, mate :)

Do you mean the editable source or a link to the actual file? I have created a Figma project and invited you a long time ago, you just have to accept it and access everything. :)
