### ISSUE TITLE
Empty Voice entry always visible in status bar

### ISSUE THREAD

**Issue by markusd112** [PaulWoitaschek/Voice#875]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: Motorola Moto G6plus
Android Version: 9

Voice seems to be active all the time in background after exiting the app. In the vertical status bar (swipe from top down) an empty entry "voice" is displayed where you normally can find the controls for playing an audiobook, see screenshot
![Screenshot_20190503-075437](https://user-images.githubusercontent.com/14372683/57121710-8452cc80-6d79-11e9-8d8f-9c229b124bf8.png)

**Comment by PaulWoitaschek** [comment]
This should no longer happen with version 7.x
