### ISSUE TITLE
Android Auto keeps disabling the app.

### ISSUE THREAD

**Issue by michaerl1953** [PaulWoitaschek/Voice#878]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: Samsung Galaxy 9+
Android Version: 9

**Comment by PaulWoitaschek** [comment]
What does that mean "keeps disabling the app"?

**Comment by michaerl1953** [comment]
When I have my phone connected to my car's infotainment system and running
Android Auto, Voice is not a choice under the music icon.  When I open
Android Auto on the phone and fine the Voice app, it is listed as disabled.
What is strange it was working fine until the May 24th update of Android
Auto.

Thanks,

Michael Reaves

**Comment by nlwclark** [comment]
I'm having the same issue. Just installed the app today, so I don't have experience with it working in the past.

Pixel 3a
Android version: 9
Voice Audiobook Player version: 4.3.2

Android Auto version: 4.3.5

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
