### ISSUE TITLE
excessive background app usage

### ISSUE THREAD

**Issue by test2a** [PaulWoitaschek/Voice#880]
recently, my android 7 lenovo z2 plus started showing excessive battery usage from voice. never have had this before. this was on 4.3.2 and i just updated to the latest version so dont know if this will still happen
![Screenshot_2019-06-01-11-24-40-0654245029](https://user-images.githubusercontent.com/39449563/58901458-db541480-871e-11e9-8593-76d95d68178c.png)

**Comment by thw0rted** [comment]
My LG G7 says the same thing but I believe it's miscalculated, just showing how much battery was drained while the app was active -- the actual power consumed could have been used for cellular network or screen-on time, but the algorithm is blaming Voice.  I could be wrong, though.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
