### ISSUE TITLE
Random files stop playing one second before the end and don't get classified as complete

### ISSUE THREAD

**Issue by Schafmuffin** [PaulWoitaschek/Voice#882]
Some storys will just stop playing exactly one second before the end. It behaves like a finished story in the way that it restarts the whole thing when I press play again but the one missing second causes it no not be classified as completed. It's not a big thing but it does clutter my "current" and is kind of annoying.
![20190609_180205](https://user-images.githubusercontent.com/51535544/59161279-efae5d80-8ae0-11e9-8591-536b40be88a0.jpg)

Not all storys do this. I don't know why some do and some don't and I also haven't found a way to reliably 
make them play the last second. Rewinding a bit and letting it play ends in the stop a second too early and pressing play when it is one second before the end causes it to reset. After it has resetted jumping to a bit before the end and letting it play sometimes fixes it. But other times it still ends in the premature stop.

App-Version: 4.3.2 (I think)
Phone Name: Samsung Galaxy A5 (2017)
Android Version: 8.0.0

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
