### ISSUE TITLE
Add option to hide previous / next chapter buttons

### ISSUE THREAD

**Issue by CreamyCookie** [PaulWoitaschek/Voice#883]
Love the app, but in all the time I have used it, I probably have pressed the previous chapter button 2 times intentionally and `<insert big number here>` times by accident. Of course, then I have to go back and find where I was.

I almost never skip chapters, and if I do so, I use the dropdown menu. An option for hiding these buttons would make using the app a lot easier, at least for me. =)

**Comment by CreamyCookie** [comment]
(Title changes really shouldn't be logged in the first 5 minutes.)

**Comment by test2a** [comment]
Add to this, an option to hide the chapter list from main listen page

**Comment by 0rAX0** [comment]
The listening experience does indeed need a major overhaul.

**Comment by PaulWoitaschek** [comment]
This is fixed in 5.x by moving the next / previous buttons and making the play button larger :)

**Comment by CreamyCookie** [comment]
Very cool. Thanks! :)

Is there a screenshot to see how it looks? Do you know when the F-Droid version will be updated? (I thought it happens automatically but maybe not.)

**Comment by PaulWoitaschek** [comment]
![Screenshot_20200406-225739](https://user-images.githubusercontent.com/743462/78604386-0ab14180-785a-11ea-8714-1f507a97ef51.png)
![Uploading Scre
![Screenshot_20200406-225758](https://user-images.githubusercontent.com/743462/78604525-359b9580-785a-11ea-97d5-98f0a9b793e8.png)
enshot_20200406-225758.png…]()

**Comment by PaulWoitaschek** [comment]
![Screenshot_20200406-225758](https://user-images.githubusercontent.com/743462/78604577-4fd57380-785a-11ea-94c6-a1d3b7fc9578.png)

**Comment by CreamyCookie** [comment]
Nice, that seems much better. =D

Thanks again the work you put into this!
