### ISSUE TITLE
Three timing bugs in one?

### ISSUE THREAD

**Issue by l0b0** [PaulWoitaschek/Voice#887]
I have observed three bugs while playing audio books lately; I assume they are related in some way.

1. The time slider does not accurately reflect the length of tracks. Just now it says the current file has played for 26:38, but the track length is displayed as just 26:33.
1. Every single time the player reaches the end of a file it stops playing, and I have to manually forward to the next file.
1. The auto rewind length is much longer than the configured one. It's set to 2 seconds, but it's more like a whole minute.

App-Version: 4.3.2
Phone Name: Nokia N6
Android Version: 9

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
