### ISSUE TITLE
Upload the app to the amazon app store

### ISSUE THREAD

**Issue by marius** [PaulWoitaschek/Voice#895]
Hi,

I would like to use this app on an Amazon Kindle Fire for Kids using the kids account.
That means the app needs to be available in the Amazon app store, side loaded apps
or apps installed via a side loaded Google play store can't be enabled for the kids
account. I'm willing to work on this myself and upload the app, but I wanted to check
here first if somebody else (Paul?) want to do this instead.

Thanks you
Marius

**Comment by PaulWoitaschek** [comment]
Feel free to fork it and upload it to amazon. I don't have the time to support move app stores.
