### ISSUE TITLE
Overlook in Auto

### ISSUE THREAD

**Issue by mseroczynski** [PaulWoitaschek/Voice#896]
Please include the following details in your bug report:
Current implementation seem to be broken from the Android Auto perspective - when there is no playback initialized (no mp3's imported) it will never load a result with empty list in Auto. Must be an overlook but Auto review will catch this one up.

App-Version: 4.3.1
Phone Name: Any
Android Version: Any

**Comment by mseroczynski** [comment]
You may be interested in this solution, hopefully I've saved you some time ;)

`  override fun onBind(intent: Intent?): IBinder {
    i { "onBind [intent: $intent]" }
    if (SERVICE_INTERFACE == intent?.action) {
      return super.onBind(intent)!!
    }
    return binder
  }`

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
