### ISSUE TITLE
Notification Reappears Randomly

### ISSUE THREAD

**Issue by camdecoster** [PaulWoitaschek/Voice#899]
I'm not sure why, but the notification with the play controls will reappear randomly after I've already dismissed it. This happens even if I haven't opened the app in a long time. Has anyone else had this issue?

App-Version: 4.3.2
Phone Name: Sony Xperia XZ1 Compact
Android Version: 8.0.0

**Comment by camdecoster** [comment]
Here's what I found in the logcat:
08-07 13:42:53.017  1585  7393 I ActivityManager: Start proc 31358:com.android.chrome:sandboxed_process0/u0i727 for webview_service de.ph1b.audiobook/org.chromium.content.app.SandboxedProcessService0
--------- beginning of main
08-07 13:42:53.068 11613  2082 I qtaguid : Untagging socket 189 failed errno=-22
08-07 13:42:53.068 11613  2082 W NetworkManagementSocketTagger: untagSocket(189) failed with errno -22
(these last two lines repeat for a while)

08-07 13:42:53.884 19454 19454 D Avrcp   : BrowsablePlayerListBuilder: de.ph1b.audiobook OK
08-07 13:42:53.884 19454 19454 V Avrcp   : getMediaPlayerInfo: Found de.ph1b.audiobook
08-07 13:42:53.884 19454 19454 V Avrcp   : isBrowseSupported for de.ph1b.audiobook: true
08-07 13:42:53.885 19454 19454 D Avrcp   : update #9:MediaPlayerInfo de.ph1b.audiobook (as 'Voice') Type = 1, SubType = 0, Status = 0 Feature Bits [40 41 42 44 45 47 48 58 59 62 65 67] Controller: null

**Comment by innesst** [comment]
I have the notification appear after a reboot or if I have airplane mode turned on. Perhaps something to do with network connection?

**Comment by PaulWoitaschek** [comment]
Should be fixed in 5.0.0-rc1. You can test the latest version on the github releases page.

**Comment by camdecoster** [comment]
I installed it. I'll let you know if it pops up again.
