### ISSUE TITLE
Technique to reduce time it takes to build

### ISSUE THREAD

**Issue by sengsational** [PaulWoitaschek/Voice#900]
Using Android Studio 3.4, it takes a really long time to build:

    BUILD SUCCESSFUL in 5m 51s
    200 actionable tasks: 26 executed, 174 up-to-date

Are there anything techniques I can use to decrease the time to build?

> Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 9, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by PaulWoitaschek** [comment]
Try the latest version or upgrade your machine :)
