### ISSUE TITLE
Chapters with cyrillic symbols are not displayed

### ISSUE THREAD

**Issue by highandmighty** [PaulWoitaschek/Voice#903]
It seems that chapters menu is not shown if .m4b-file has Cyrillic symbols in chapter names. I hope this is a bug.

I've attached two screenshots. First: Voice app with the same book with Cyrillic and Latin version of chapters:

![comparison](https://user-images.githubusercontent.com/25966313/62840781-98776580-bca8-11e9-99ee-ba850cec9bcc.png)

Second: same files in desktop app.

![cyrillic-vs-latin-chapters](https://user-images.githubusercontent.com/25966313/62840821-b1801680-bca8-11e9-9b7b-b4c13e418470.png)

App-Version: 4.3.2
Phone Name: Sony Xperia X Compact
Android Version: 8.0.0

**Comment by PaulWoitaschek** [comment]
This should be finally fixed in 5.x!
