### ISSUE TITLE
Feature Request: Google Home capability

### ISSUE THREAD

**Issue by ErikLentz** [PaulWoitaschek/Voice#904]
Feature Request: Sometimes I will want to finish an audiobook I was listening to in the car on my Google Home, but I can't seem to stream from Voice to the Google Home.

App-Version: 4.3.2
Phone Name: LG G7 ThinQ G710ULM
Android Version: 8.0

**Comment by NULLx76** [comment]
As a workaround you can "cast screen to device" but native support would nicer.

**Comment by jtagcat** [comment]
I would be careful with privacy.

**Comment by jtagcat** [comment]
Duplicate of #76

**Comment by PaulWoitaschek** [comment]
Thx
