### ISSUE TITLE
Add Build Instructions to docs

### ISSUE THREAD

**Issue by weiluntong** [PaulWoitaschek/Voice#905]
How is everyone building this project? I'm starting from a fresh clone, and opened it in Android Studio via `Open Android Studio` > `Open an existing Android Studio project` > `build...` which worked well enough. I had to update Kotlin via: https://stackoverflow.com/questions/56607089/new-gradle-sync-is-not-supported-due-to-containing-kotlin-modules-using-an-unsup, but after that it seems to work fine as I'm getting:
```
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.                            
Use '--warning-mode all' to show the individual deprecation warnings.                                                  
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 52s                                                                                              191 actionable tasks: 8 executed, 183 up-to-date 
```
To run the android app on my emulator, I open 'app' in a different project and run that. Does this reflect what everyone else's setup is?

**Comment by weiluntong** [comment]
actually this is similar to #803. Though I can't follow along with that thread... I'd still like to verify with other contributers willing to participate that their initial setup is the same as mine, and possibly update the contributing section with a "how to build" subsection.

**Comment by PaulWoitaschek** [comment]
BUILD SUCCESSFUL in 1m 52s

So the build is not failing? Please report if this still happens with the latest version of android studio & the latest kotlin plugin.
