### ISSUE TITLE
[Feature Request] Start with complete list

### ISSUE THREAD

**Issue by RalfKo** [PaulWoitaschek/Voice#906]
Hi,

I use the player for my kids audiobooks. the startup screen with "new" and "more" is confusig to them (and me). please introduce an option to always use a complete list of all books as the start-up screen, with only the very last played book in a separated box at the top.

Thank you

**Comment by Russe** [comment]
Would like this behavior as well.

**Comment by PaulWoitaschek** [comment]
That's the current behavior now in 6.x+

**Comment by Russe** [comment]
Thanks a lot for this feature :-)

**Comment by PaulWoitaschek** [comment]
You're welcome!

Yours sincerely, Twoflower 🌷 🌷

**Comment by RalfKo** [comment]
I can't find the version number in the app or in the play store. is 6.x the beta ?

**Comment by PaulWoitaschek** [comment]
It's on fdroid, GitHub released and on staged play release a t 10%

**Comment by RalfKo** [comment]
my fdroid shows me 5.0.1. I guess I just have to wait.

**Comment by PaulWoitaschek** [comment]
The fdroid version is definitely released. Maybe reinstall?

**Comment by RalfKo** [comment]
strange, updates on other apps work. when looking at the listing in Fdroid catalogue it shows 5.0.1 as latest version. and the link "changes" brings me to https://github.com/PaulWoitaschek/Voice/blob/HEAD/CHANGELOG.md which shows 5.0.2 as latest. strange indeed

**Comment by RalfKo** [comment]
but when I deinstalled the fdroid catalogue shows me 6.0.7 as latest. ok, works for me.

**Comment by PaulWoitaschek** [comment]
That's still outdated, my fdroid lists 6.0.9
https://f-droid.org/packages/de.ph1b.audiobook/
