### ISSUE TITLE
[Feature request] Disable Android Bluetooth autoplay

### ISSUE THREAD

**Issue by MartinCorteza** [PaulWoitaschek/Voice#915]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: Galaxy S9
Android Version: 9.1

When I connect my phone to my cars bluetooth speakers, Voice apparently reacts to the KeyEvent sent by the speakers and starts playing, even if not running in background. Could you add an option so that Voice ignores that event and starts playing only when triggered manually?

**Comment by PaulWoitaschek** [comment]
Which keyevent does your speaker send?

**Comment by MartinCorteza** [comment]
I really don't know. The issue is with my cars builtin multimedia system. Every time I connect my S9 to it via bluetooth, it starts Voice and plays the audio book. I did some research on that matter and found that there is a bluetooth auto play feature that sents an event that is similar to pressing the 'play' button on a headset. I think my car manufacturer has implemented that feature into the multimedia system, so the only way to stop Voice auto playing an audio book would be an option to ignore that event.

**Comment by innesst** [comment]
Have you tried to switch off the "Resume Payback" option in the settings menu?

**Comment by MartinCorteza** [comment]
Yes, I did but to no avail. I've asked the maker of my car about that auto play feature but they seem to be clueless - I think they get the multimedia/navigation system from a supplier and don't really understand how it is working.
I can give you one more hint: The autoplay event is not only triggered when I connect my phone via bluetooth but even when I set a destination for navigation. That means the systems computer voice echos the destination and then switches to playback via Voice, even if I havn't been using Voice before.
Is there a bluetooth monitor app that I could use to find out more?

**Comment by PaulWoitaschek** [comment]
You could check which keyevents it sends upon connection

https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay

**Comment by MartinCorteza** [comment]
This tool doesn't work with my Android version (version is too new). It shows warnings and doesn't record any events when I connect the phone. Any other suggestions?

**Comment by MartinCorteza** [comment]
@PaulWoitaschek 

I managed to start the Keyevent app on my old phone which shows the same behavior wih Voice and my cars MM system.
I get the reading below:

KeyDown:      action=0 code=126 repeat=0 meta=0 scancode=200 mFlags=8 label='' chars='null' number='' 
KeyUp:        action=1 code=126 repeat=0 meta=0 scancode=200 mFlags=8 label='' chars='null' number='' 

Does that make any sense to you?

**Comment by PaulWoitaschek** [comment]
Your car actually sends the play command:
https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_MEDIA_PLAY

I'll come back to this when I find time - for now I found this: https://android.stackexchange.com/questions/179294/prevent-music-players-from-auto-play-on-bluetooth-connect

**Comment by MartinCorteza** [comment]
Thanks for the info. I think running 'tasker' just to intercept the 'Play' command would be some sort of overkill. So I'll wait until you find some time to address the issue in 'Voice'. Thanks in advance!

**Comment by MartinCorteza** [comment]
Paul,
 I don't know if you have worked on this issue specifically, but with version 5.0 of 'Voice' my problems are gone. Thanks a lot!

**Comment by PaulWoitaschek** [comment]
Ha, nice! That's rather a side effect on a larger rework (which also prevents the notification from occasionally popping up).

**Comment by MartinCorteza** [comment]
Paul,
my info on this issue was premature. Actually, Voice v. 5.0 still starts playing when I connect my phone to my car via bluetooth. I did'nt check the updated versions of Voice. Was there an other version shortly before 5.0 came out? Please reopen this feature request and if you find time, have a look at it.
