### ISSUE TITLE
[Bug] Umlauts in tags

### ISSUE THREAD

**Issue by glopsblink** [PaulWoitaschek/Voice#916]
App-Version: 4.3.2
Phone Name: Pocophone F1
Android Version: LineageOS 16.0 (~Android 9)

Hi Paul,

I noticed a strangely erratic behaviour concerning German umlauts.

Settings: My audiobooks (AAC) are tagged using mp3tag. I found out that the %artist% and %title% tag are read by Voice, so I use them to specify the author and the title.

Unfortunately, tags containing umlauts are not handled correctly in some cases. Example: An audiobook with a %title% tag of "Brunetti 18 - Schöner Schein" (format for sorting purposes) is displayed as "Brunetti 18 - SchÃ¶ner Schein". As far as the title is concerned, this is a minor problem (the titel can be altered within Voice), but for the author there is no such possibility (if I'm not mistaken).

I noticed that not all tags with umlauts are affected. Therefore I started fiddling around with the above example: When I changed the %title% tag to "Schöner Schein", it showed up correctly in Voice, as did the challenging (if meaningless) tag of "ÄÖÜ äöü".

I have been unable to spot a pattern behind this behaviour. Any idea?

Regards & keep up the great work
Dirk

**Comment by PaulWoitaschek** [comment]
@glopsblink Can you send me such a problematic file to the email in my github profile?

**Comment by PaulWoitaschek** [comment]
This should be fixed as of 5.0.0

**Comment by glopsblink** [comment]
@PaulWoitaschek I can confirm that all tags are now read correctly after I re-imported the audiobooks.
Thank you for fixing!
