### ISSUE TITLE
[Bug] Random skipping in MP3 files, and playing beyond length

### ISSUE THREAD

**Issue by Luzhin99** [PaulWoitaschek/Voice#917]
Please include the following details in your bug report:

App-Version: 4.3.2
Phone Name: OnePlus 5
Android Version: Oxygen 9.0.8

Hello,

I'm listening to an audiobook in an MP3 format. When ever I pause it it goes to a position before or after where I actually paused. It is 10s or 15s +- from the location I paused at. This has never happened before. This is a 5hr long MP3 file.

 Something remotely close to this which happened with another set of MP3 files was that every chapter (file) actually ended 10-15 second after the detected maximum run time of the file. So if it would be a 45:03 long chapter, the bar would reach 45:03, show 0 seconds as remaining but the playback would still be on. When I finished the audibook in the completed section it actually shows 00:-19. In another book (which was a single, large MP3 file) it says 00:-40 at completion. 

![Screenshot_20190826-172349__01](https://user-images.githubusercontent.com/54536677/63689094-a7245780-c826-11e9-9bf0-38265c1b71e6.jpg)

These two issues might be unrelated since I didn't face the skipping issue with the two completed books. However I am mentioning them together since they are the only 3 MP3 files out of rest of audiobooks.

**Comment by 0rAX0** [comment]
Hey @Luzhin99 

The first issue is intended, you can disable it in the Settings(Cog menu) > Auto rewind. 

The second issue, might require you to attach the offending MP3 files so that @PaulWoitaschek can test them.

**Comment by Luzhin99** [comment]
Hey @0rAX0 ,

Thanks for your reply. I'm afraid that's not it. My Auto Rewind is set to 2 sec. This file jumps forwards and backwards by 10-12 seconds very randomly. Today it was jumping merrily forward by 30-35 seconds. It is very strange and frustrating. Thankfully, I have almost finished the book because I could not reliably pause it :)

The files I'm referring to are large (~250mb), should I attach them? The photo attachment I added above, is that normal? The 0:-19 and 0:-40? NOT an issue usage wise at all this one, but a bug.

**Comment by 0rAX0** [comment]
I suspect it to be a corrupt file. You can try and convert it using ffmpeg and see the log file. But you might need to upload it somewhere and attach the link (not sure how legal that would be though)

**Comment by Luzhin99** [comment]
I wouldn't understand it as a lay person, but could it be the variable bit rate? I'm yet to check the file on my PC if it IS a VBR file, but an answer on a slightly similar topic on the web suspected that VBR could have something to do with seek issues. The file plays properly on other audiobook apps so I am not sure if it is the file being corrupt. I'll try deleting the file and adding it back to my phone again and see if it helps anything. If @PaulWoitaschek wants, I'll upload the file to a hosting service and link it privately if that's fine. Before that I'll experiment a little by deleting 
 and adding the file again or changing the format or something. Thanks for reply @0rAX0

**Comment by 0rAX0** [comment]
Good luck!

**Comment by radusalagean** [comment]
I've also had similar issues today with a podcast in mp3 format today. (this is the file in cause: https://media.simplecast.com/episodes/audio/307649/Debugging.mp3 )

I took a look at the code and couldn't find any issues, the seeking command is sent correctly to the ExoPlayer instance. Afterwards, I converted that mp3 file to ogg format and the issues were gone. 

Doing some digging, I found out something new about how the mp3 format works. This is a known limitation of the format itself. Here is more info: https://stackoverflow.com/a/53747530/11631823

It was also discussed on the ExoPlayer issues forum: https://github.com/google/ExoPlayer/issues/4676

**Comment by breezem08** [comment]
hey i m facing-some issues while running the code on my Android studio
what should i do 
i cant build my gradles

**Comment by mlvanbie** [comment]
Starting several weeks ago, I've had a worse version of this problem.  Almost every audiobook I listen to shifts position by several minutes (forwards or backwards, and not in a consistent direction) when I resume after pausing.  The forward and back buttons also don't adjust a consistent amount of time, which is particularly noticeable when I move back and then forward as I try to find where I left off.  Listening to an audiobook for a few seconds can still result in a multiple minute jump.

The VBR bug theory seems plausible.  I looked a several files using VLC's realtime statistics.  The only audiobook that has worked properly recently kept the input and output bit rates in sync (although both varied).  For the other ones that I looked at two of them had variable input bit rates and constant output rates while one varied both the input and output rates somewhat independently (Voice ended up confused about its timestamp in that file and data ended when it thought there were another 30 minutes left).

**Comment by kimsey0** [comment]
It looks like the [2.12.0 release](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2120-2020-09-11) of ExoPlayer (Voice currently uses 2.11.4; 2.12.0 was released in September 2020) added a new [`FLAG_ENABLE_INDEX_SEEKING` flag](https://github.com/google/ExoPlayer/issues/6787), which allows for accurate but slower seeking in variable bitrate MP3 files. Enabling that may fix this problem.

**Comment by mlvanbie** [comment]
Definitely still an active problem.  In addition to the bugs mentioned above I've noticed that chapter marks on audiobooks weren't matching up with the audio (both when the chapter updated and if I was trying to use them to seek).

Looking forward to FLAG_ENABLE_INDEX_SEEKING being enabled for VBR files, even if this means a delay for long MP3 files (the ones that tend to get the most out of sync; I'd rather the software dealt with the issue slowly than spending several minutes trying to seek to the right position).
