### ISSUE TITLE
Pause on lound noise.

### ISSUE THREAD

**Issue by erluxman** [PaulWoitaschek/Voice#918]
So I have this very specific use case while using this app.

While I am running I listen to audiobooks but time and again lound noise of big trucks or bus while they pass by me disturbs my listening. So can we implement a special feature which pauses the audiobook and plays from 10s behind after a loud noise passes by?

Is there anything that is laid out in the codebase? I would love to contribute to this part. 

App-Version: Any
Phone Name:Any
Android Version:Any

**Comment by PaulWoitaschek** [comment]
This would require the app to constantly listen to voice input and increase the power consumption.
