### ISSUE TITLE
LockScreen Playback Controls

### ISSUE THREAD

**Issue by JStyle21** [PaulWoitaschek/Voice#920]
Hi,

Is it possible to add some playback controls to the lockscreen while the app is running? a simple X secs forward and back should be great.

**Comment by PaulWoitaschek** [comment]
There are already controls on the lockscreen. Maybe you disabled your notifications?

**Comment by JStyle21** [comment]
I think i just took it as something else (*facepalm*), is there a way to configure the amount of time it skips or some indication of the current playing time?
