### ISSUE TITLE
Add a possibility to turn off the grouping by Current and Completed

### ISSUE THREAD

**Issue by cergmin** [PaulWoitaschek/Voice#927]
Please, add a possibility to turn off the grouping by Current and Completed.
I want to have a single list of audiobooks.

App-Version: 4.3.2

**Comment by CreamyCookie** [comment]
There should also be a group for "Started" (podcasts you have listened to at least once)

**Comment by test2a** [comment]
while we are at it, would asking for custom groups be too much?

**Comment by PaulWoitaschek** [comment]
Single list of audioboks is back :)
