### ISSUE TITLE
[Bug] Volume is very low on Android with Airpods, making it impossible to use

### ISSUE THREAD

**Issue by roxdanila** [PaulWoitaschek/Voice#928]
App-Version: 4.3.2
Phone Name: Google Pixel 3
Android Version: 10

Seems to be a more general issue that appeared after the latest android update + airpods firmware update that mainly affects media (i.e. calls, whatsapp, etc work just fine)

P.S. I love the app! Thanks for doing this :)

**Comment by PaulWoitaschek** [comment]
This doesn't look something that needs fixing on voices side.
