### ISSUE TITLE
[enhancement request] disable shake-reset after inactivity

### ISSUE THREAD

**Issue by metbic** [PaulWoitaschek/Voice#936]
The shake-to-reset is really nice when going to sleep, but in the next morning, it has the obscure side-effect of turning the audiobook back on. This happens when you pick up the phone first time after waking up. Sometimes passively moving the phone on the bed is enough. 

It would be nice if shake-reset or maybe even the whole app would stop after more than a few hours of inactivity. 

App 3.6.1  Sony xz1  Android 9

**Comment by PaulWoitaschek** [comment]
It already stops after a minute.
Use a recent version of the app, your version is from Oct 22, 2017.
