### ISSUE TITLE
[Bug] Goes to start of the current track when power button is pushed

### ISSUE THREAD

**Issue by dn3712** [PaulWoitaschek/Voice#937]
App-Version:  4.3.2
Phone Name:  Galaxy A20 (Model number:  SM-A205U)
Android Version: 9

Hi, I usually listen to my audio books (on mp3 files) with earphones
while walking or doing something. Sometimes I want to look up
some info on the phone (time, weather, etc.) while listening.
To do this I have to push the power button in order to turn on the screen 
(there is no Home button on my phone when the screen is off).
When I do this, about 50% of the time the app goes to the beginning
of the current track. It's annoying, especially if tracks are long.

Please do something,
thanks in advance.

**Comment by test2a** [comment]
yep. facing this each and every time, which is like everyday.

**Comment by PaulWoitaschek** [comment]
If this is still happening with 5.x, please open a new issue and attach a media file.
