### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by ronilaukkarinen** [PaulWoitaschek/Voice#939]
App-Version: 4.3.3
Phone Name: OnePlus 5T
Android Version: 9

Is it possible to save/restore the settings? When I installed the new apk just now I lost all progress and custom covers.

**Comment by jtagcat** [comment]
Not only save/restore, but automatically:
 - Saving the status within the source (tampering with data, not very good) as a file.
 - Saving the whole app's progress with all books in a file.
This allows syncing progress between devices and automatic backups by apps like Nextcloud and Syncthing.

**Comment by jtagcat** [comment]
Duplicate of #295

**Comment by kanjieater** [comment]
Does anyone have any temporary work around for this? Don't want to hold off resetting my phone for this one issue.

**Comment by egvimo** [comment]
I've done screenshots of the overview list to "save" the current status and restored the settings and progress manually.

**Comment by kachapman** [comment]
What if we copied the whole de.ph1b.audiobook folder from Android/Data to a new device?

**Comment by PaulWoitaschek** [comment]
This should work with Voice 6+.
