### ISSUE TITLE
Uncloseable notification

### ISSUE THREAD

**Issue by benpryke** [PaulWoitaschek/Voice#940]
Playback notification appears when app is not open and when swiped to close a second uncloseable Voice notification tooth no content appears that can only be cleared be force stopping the app. I have just upgraded to android 10 and have not used or chosen to open Voice. 

App Version: 4.3.2
Phone Name: OnePlus 6
Android Version: OxygenOS 10.3.0

**Comment by PaulWoitaschek** [comment]
Should be fixed in 5.0
