### ISSUE TITLE
First open play button

### ISSUE THREAD

**Issue by shme14** [PaulWoitaschek/Voice#941]
Please include the following details in your bug report:

App-Version: 5.0.0-rc4
Phone Name: Pixel XL 2
Android Version: 10

When using bluetooth headphones the play button on the headphones does not continue the last played audio book anymore. This only happens when the app is initially opened. The headphone button works fine if you manually press play in the app first. I don't think it acted like this in previous versions.

**Comment by PaulWoitaschek** [comment]
How is it with other media players?
I made a big change to how the whole playback is handled. I think the moment the headset play button now stops playing voice was the moment where previously the notification was just killed by the system.

**Comment by shme14** [comment]
The only other player I really use is Rocket Player. My current setup is I use Tasker to choose whether to hit play on Rocket Player or Voice by using the "Media Control" function. Within "Media Control" I choose "Play [Simulated Only]" and make the target either Voice or Rocket Player depending on other factors. This function used to always work for Voice (even on cold starts) but now only works if you already have voice running and have already hit the play button within the app at least once. With rocket player it always works with both cold starts and when it is already running in the background.

**Comment by MiK1977** [comment]
I can confirm a new problem using Tasker to start Voice playback. In old versions I could start playback using the "Media Control". This doesn't work anymore.
An alternative to "Media Control" could be sending an intent. Could you tell us the correct data for starting Voice playback using intents?

**Comment by shme14** [comment]
As of 5.0.1 this seems to not be an issue anymore.
