### ISSUE TITLE
Language setting not available

### ISSUE THREAD

**Issue by fridde** [PaulWoitaschek/Voice#943]
My phone's language is set in Swedish, but most apps that can't provide a proper translation provide the choice of English, which is totally fine.
This app gives me an awkward auto-translated mess of Swedish instead. Is this fixable?

App-Version: 4.3.2
Phone Name: Moto G5
Android Version: 8.1.0

**Comment by fridde** [comment]
Okay, maybe I was a bit harsh to call the translation "auto-generated". 
I checked the xml-file and saw that most of the strings could be considered acceptable, but clumsy and a bit weird.

Still, I'd much prefer *this particular* app to be available in English while keeping the rest of my apps Swedish.

**Comment by PaulWoitaschek** [comment]
It's not auto translated, it's translated by real humans.

https://www.transifex.com/PaulWoitaschek/voice/

You can request becoming a maintainer for swedish there and make the translations better. :)

**Comment by PaulWoitaschek** [comment]
Ah and for the language setting: I like keeping it simple and following the system settings.
