### ISSUE TITLE
Google CrashLytics tracker is contained in the program - for what?

### ISSUE THREAD

**Issue by geoderix** [PaulWoitaschek/Voice#944]
I read at Google Play: "Voice is free and Open Source. That means, everyone can see what it does. Minimal permissions, no tracking."
And I see at [exodus](https://reports.exodus-privacy.eu.org/en/reports/de.ph1b.audiobook/latest/) that Voice Audiobook Player from Paul Woitaschek has 1 tracker - [Google CrashLytics](https://fabric.io/kits/android/crashlytics).
Exodus [says](https://reports.exodus-privacy.eu.org/en/trackers/27/) about Google CrashLytics: 

"Crashlytics offers a variety of services for app developers. Crashlytics:

    Receives and analyzes app crash reports which may contain user and device-specific data.

    Performs analytics on app logs "even the exact line of code your app crashed on" Crashlytics, 03

    Performs analytics on app users and utilizes social media advertising. "Get insight into your users, what they’re doing, and inject live social content to delight them" Fabric, 01

    Performs cross-device user identity and authentication via "Fabric" Wired, 01

I looked on my tablet - over the past month, the program sent 0.91 Mb of data via Wi-Fi (298 kB in active mode and 631 kB in the background). This month, I gradually listened to one audiobook. I looked at the phone - over the past month, the program sent 155 kB via LTE (155 kB in active mode and 386 B in the background) and 234 kB through Wi-Fi (145 kB in active mode and 89.98 kB in background), In total, the program sent 155 + 234 = 389 kB of data from my phone without my knowledge. And from two devices with non-intensive use for a month, the program stole 910 + 398 = 1,308 kB of data.
On my devices, the program has never crashed. That is, the tracker could not send data about the program crash, some other data was sent. Are the authors interested in my personal data? Or files from my media? Or what is the author interested in on my devices? I ask because the author has stated publicly that the program does not contain trackers. Maybe the author will honestly say what data he is interested in on my devices and I will send it to him myself. Keeping an eye on my devices silently is unfair and disgusting.
I think that it will be correct to remove the tracker from the program or honestly declare to Google Play that the program monitors your actions and sends personal data to the author and Google Corporation.

P.S. Does the author sell this data for profit contrary to the statement that the program does not contain any trackers?

**Comment by PaulWoitaschek** [comment]
It's stated in the privacy policy that I use crashlytics for crash tracking.

If you don't like that use the fdroid version. 

Also I don't sell any data, who would even like to buy some random device stats from a small open source app?

**Comment by geoderix** [comment]
Can you give a link to a private policy, where it says about Google CrashLytics? I just found a google play entry where you say there are no trackers. But in reality they are.
P.S. Why did you instantly startled to close the bug? You do not want users to know that you are spying on them? Will you continue to be misleading?

**Comment by geoderix** [comment]
Sorry. I found a [link](https://github.com/PaulWoitaschek/Voice/blob/master/PRIVACY.md) to the private policy. It really says that you spy on users and collect personal information. Probably make money on this. However, why are you misleading users by claiming on Google play that there are no trackers in the program and it’s open source. Is Google CrashLytics an Open Source?
