### ISSUE TITLE
[Feature Request] Chromecast support

### ISSUE THREAD

**Issue by kan84** [PaulWoitaschek/Voice#946]
Chromecast support for playing audibook over Google Home or Chromecast device.

**Comment by franciskcso** [comment]
It seems like there are other threads about this from way back. But I'm not sure what happened to the implementation of it.

**Comment by franciskcso** [comment]
Use Google's Home app to mirror the screen and cast onto device. I think that's the solution the developer is going with.

**Comment by PaulWoitaschek** [comment]
#76
