### ISSUE TITLE
Ogg Opus files don't play

### ISSUE THREAD

**Issue by Beissmich** [PaulWoitaschek/Voice#948]
After the latest update my Ogg Opus files no longer play.
Older opus files are still listed and new opus files are recognised. When I tap the play button, it changes to pause and pack to play. Aac and mp3 files are fine.

In the older version 4.x Opus worked fine for me.

App-Version: 5.0.0-rc9
Phone Name: OnePlus 5
Android Version: 9
File Format: Ogg Opus in Opus format
Example file: two files attached
The not ok file worked on 2020-02-14 and does not work now, next to dozens of others.
I also generated an new opus file that works in 5.0.0-rc9

[opus.zip](https://github.com/PaulWoitaschek/Voice/files/4288689/opus.zip)

**Comment by PaulWoitaschek** [comment]
Please send me such a file (if confidential to Woitaschek@gmail.com)

**Comment by Beissmich** [comment]
I attached two opus files.
One of them played fine at 2020-02-14 and does not play any more, just like many others on my phone.
I created a second file that works in 5.0.0-rc9.

All of them play in Foobar2000 Windows and Foobar2000 Android.

**Comment by PaulWoitaschek** [comment]
@Beissmich I reported it upstream, see the linked issue.
