### ISSUE TITLE
Book restarts when starting vehicle Bluetooth Audio

### ISSUE THREAD

**Issue by drodda** [PaulWoitaschek/Voice#949]
When selecting Bluetooth Audio in my car Voice player automatically starts playing. It plays 1-2 seconds of the current audio book, then jumps to the start and plays from the beginning.

I have disabled the "Resume Playback" setting in Voice which had no effect. 

App-Version: 5.0.0-rc9
Phone Name: Pixel 3a
Android Version: 10

Possibly related: #941

**Comment by drodda** [comment]
Some more information:

When Voice is not open (no notification with player controls) and BT connects nothing happens, as Voice is not the current media player. If I later open Voice and play it works normally.

If Voice is open then when BT connects it plays 1-2 seconds of audio from the current position then starts from the beginning. 

I have attached an adb log of what I think are the relevant parts: [reset.log](https://github.com/PaulWoitaschek/Voice/files/4310463/reset.log) - this includes output from the `MediaSessionService` and `AvrcpMediaPlayerWrapper` processes. I have the original log and can submit more if required. 

You can see in the log Voice start to play at the current position, a timeout of some kind, and then Voice start to play from position 0.
```
MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_PLAY, scanCode=0, metaState=0, flags=0x0, repeatCount=0, eventTime=0, downTime=0, deviceId=-1, source=0x0, displayId=0 } to de.ph1b.audiobook/PlaybackService (userId=0)
AvrcpMediaPlayerWrapper: onPlaybackStateChanged(): de.ph1b.audiobook : PlaybackState {..., position=36606520, ...}
...
AvrcpMediaPlayerWrapper: Timeout while waiting for metadata to sync for de.ph1b.audiobook
...
AvrcpMediaPlayerWrapper: onPlaybackStateChanged(): de.ph1b.audiobook : PlaybackState {..., position=0, ...}
```

Other media players seem to handle this fine. Any idea what is causing the reset?

**Comment by MartinCorteza** [comment]
This is a behavior similar to my feature request #915. Unfortunately, I told Paul that the problem was gone with Voice 5.0 and he has closed the feature request. But my assessment was premature - the issue persist.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
