### ISSUE TITLE
[Bug] widget play button only works if the app is open

### ISSUE THREAD

**Issue by MagTun** [PaulWoitaschek/Voice#951]
With the previous version I could use close the app (from the current app menu) and press the play button on the widget to restart the audio.
With this new version, I have to first re-open the app and the press the play button (which kind of defeat the purpose of using the widget). 

I enabled autostart but it didn't change anything

App-Version: 5.0.0-rc9
Phone Name: Redmi 7A
Android Version: 9 (MIUI 11)

**Comment by MagTun** [comment]
I forgot to mention that I turned off battery saver

**Comment by WiliTest** [comment]
Idem:  the widget doesn't work (it only opens the app).

**Comment by egvimo** [comment]
I have the same issue.

Furthermore the issue is also true for resuming the playback via Bluetooth or headphones. If the app is closed the playback does not resume. With the previous version (and other apps) it worked.

**Comment by shme14** [comment]
Same with me too.

**Comment by egvimo** [comment]
For me RC 13 resolved the issue.

**Comment by MagTun** [comment]
@PaulWoitaschek, thanks a lot, it works!
