### ISSUE TITLE
Disable timer if not reactivated in X minutes

### ISSUE THREAD

**Issue by bjohas** [PaulWoitaschek/Voice#954]
Love the app, thank you. 

I've got the timer on, co be plays for say 30 mins then stops. Shake, plays for another 30, then leave phone alone for a few hours (e.g., sleep). When I pick up the phone, the app resumes. I pause from the tray, but of the phone shakes, the app resumes again.

It would be better if the "shake to continue" function only stayed active for a period of some minutes (that would save battery too, right?). Something like 1 minute would work for me, but I don't mind of it was even 60 minutes. 

App-Version: Google play  2nd mar 2020
Android Version: 8

**Comment by scampsi** [comment]
Is this maybe a bug rather than a feature request?
The behaviour bjohas describes only started happening for me after a recent Play Store update. Before that, shake to continue would only stay active for several minutes.

App Version: 5.0.1 from Play Store on 2020-04-03
Android Version: 6.0.1

**Comment by PaulWoitaschek** [comment]
Yes, its a bug. There is cold that should already do this.

**Comment by bjohas** [comment]
Thank you for confirming!

**Comment by bjohas** [comment]
Btw. When I take the timer off, with playback paused, playback resumes. That may be related!

**Comment by bjohas** [comment]
Hi @PaulWoitaschek - I was just wondering whether this should be fixed in the latest release. The latest release on Google Play is 5.0.1, whereas the above might have been fixed in 5.0.2?

**Comment by bjohas** [comment]
Hi @PaulWoitaschek - just following up on this. Would love to have this feature in a new release on Google Apps store. Any chance? Thank you👍😀
