### ISSUE TITLE
Mark book as completed

### ISSUE THREAD

**Issue by bjohas** [PaulWoitaschek/Voice#955]
Sometimes when I get to the end of a book, the book is not marked as done. I then go back to the last track, play the end again, and that fixes the issue.

Would love to have an option in the tap-hold menu to mark a book as conplete (or, less important, an option to mark a complete book as incomplete).

App-Version: Google play  2nd mar 2020
Android Version: 8

**Comment by PaulWoitaschek** [comment]
Thanks for your suggestion!
Marking a book as completed is implemented as of https://github.com/PaulWoitaschek/Voice/commit/265d28e90c0dfd68f5c1295b58875986c42567b1
