### ISSUE TITLE
[Bug] Several problems with Voice

### ISSUE THREAD

**Issue by egvimo** [PaulWoitaschek/Voice#957]
Please include the following details in your bug report:

App-Version: 5.0.0-rc9
Phone Name: Nokia 7.2
Android Version: 9

The problems started when I wanted to add a new book (about 1.8 GB). It was not added or did not appear in the list.

So I tried to add the book one by one removing all other books first. That did not work either.

I uninstalled and reinstalled the app (multiple times by now).
Now it's like this: When I start the app, the loading circle comes. Normally the popup for adding the books should appear. But that popup only comes when I actually add the book. To get rid of this popup I have to remove the book and add it again.
When I add a single book, it takes a long time (several minutes) until the book appears in the list.

After the book finally appears, neither metadata nor covers can be seen.

On another device (Pixel 3, Android 10) this all works without problems (same Voice version). I suppose it is a device or Android 9 problem in combination with the new version. Everything worked well before the update.

**Comment by PaulWoitaschek** [comment]
Can you say if this release improves the situation for you?
https://github.com/PaulWoitaschek/Voice/releases/download/5.0.0-rc10/app-proprietary-release.apk

**Comment by egvimo** [comment]
Yes, now it's working again. Thank you for the quick fix!

BTW: Why is the release so big (~5 MB vs. ~85 MB)?

**Comment by PaulWoitaschek** [comment]
Thats because I now use ffmpeg for parsing the metadata. On my device this made the media scan extremely fast (5 minutes -> 200ms).
That means that apk's now include the library for all cpu architectures. On google play I use app bundles so you only get the architecture necessary and it shows a download size between 11MB and 20MB, depending on your cpu architecture.
