### ISSUE TITLE
[Bug] Audio cannot be heard if made call via Google Duo

### ISSUE THREAD

**Issue by jakubklos77** [PaulWoitaschek/Voice#961]
App-Version: 5.0.0
Phone Name: Huawei P20 Pro
Android Version: Android 9.1

Hello,
when I keep listening in the audio book and during that make a Google Duo call, then after finishing the call the audio from Voice cannot be heard. You basically need to fix this using Google Play music (start playing any song) and then Voice will start playing audio again.

It seems Duo use a way to mute/pause the audio playback and the app needs to reset it back somehow. Google Play Music does that but Voice does not.

It would be nice if you could figure this out

Thank you

**Comment by PaulWoitaschek** [comment]
Wow that was hard to debug.

https://github.com/google/ExoPlayer/issues/7182

**Comment by jakubklos77** [comment]
Good job, Paul! 
Hope the ExoPlayer dev will be able to fix it
Love your app btw.
Thank you

**Comment by PaulWoitaschek** [comment]
It was a bug in google duo. However the exoplayer team was able to implement a workaround.
