### ISSUE TITLE
Empty list

### ISSUE THREAD

**Issue by seathwolf** [PaulWoitaschek/Voice#963]
Just adapted to the latest version and I lost the list with all books I have already completed.  

I hope you can add the option to mark books as completed. 

App-Version: 5.0.0
Android Version: 10

Thanks for your work I really enjoy the app.

**Comment by PaulWoitaschek** [comment]
What does it mean; you lost the list. Where are these books listed now?

**Comment by seathwolf** [comment]
They are back in "Not started Yet" section.

**Comment by PaulWoitaschek** [comment]
And what is their progress?

**Comment by seathwolf** [comment]
![Screenshot_20200403-150251_Voice_LI](https://user-images.githubusercontent.com/63124516/78400511-7c6c5f80-75bc-11ea-9f6f-ce3ccd03faa8.jpg)

showing as unread

**Comment by PaulWoitaschek** [comment]
Ah damn. Hopefully 1c54e30323f380031ac264d28fe4b508093debf0 will make the app crash in the future instead of losing its progress.
