### ISSUE TITLE
[BUG] chapter markers are being read incorrectly in certain *.m4b files.

### ISSUE THREAD

**Issue by rottenkumquat** [PaulWoitaschek/Voice#964]
In version 5.0.0 certain *.m4b files have their chapter markers read incorrectly resulting in misaligned chapters. In version 4.3.3 these files worked correctly. I can provide a sample file if necessary.

App-Version: 5.0.0
Phone Name: Xiaomi Mi A1
Android Version: 9

**Comment by PaulWoitaschek** [comment]
Yes, please send a file.
