### ISSUE TITLE
I dont see SKIP and REWIND. 

### ISSUE THREAD

**Issue by itsbchen** [PaulWoitaschek/Voice#969]
Please include the following details in your bug report:

App-Version:
Phone Name: samsung 9+
Android Version:

**Comment by PaulWoitaschek** [comment]
Please describe your issues properly.

**Comment by itsbchen** [comment]
My apologies,
I see that I can skip and rewind, but I completely skip it. 
Skip amount: 3-60
Auto rewind: 3-60

But, I cannot completely skip or rewind. Before, I could do it.

Also, I was able to be black in Voice. It is really bright now.

Cheers!

app version: 5.0.0
Phone Name: Samsung Galaxy S9+
android version: 10

**Comment by PaulWoitaschek** [comment]
I don't understand. Why cant you skip?

> Also, I was able to be black in Voice. It is really bright now.
Voice follows the system settings of the dark mode on Android 10.

**Comment by itsbchen** [comment]
![92443846_633653810546167_2153198849311637504_n](https://user-images.githubusercontent.com/26336661/78968233-02fbd200-7ad2-11ea-9bd1-bec195f582d2.jpg)

**Comment by itsbchen** [comment]
I thought you can completely skip or rewind.

**Comment by itsbchen** [comment]
![92509254_2629319270620605_3044032799452430336_n](https://user-images.githubusercontent.com/26336661/78968290-1eff7380-7ad2-11ea-9b82-4719ac62cf18.jpg)
I thought, I can lower to be black.

**Comment by PaulWoitaschek** [comment]
There are arrows on the left and the right. Use these to skip tacks.

Swipe down your notification settings and enable the dark mode there.

**Comment by itsbchen** [comment]
MY GOODNESS! Paul, Thank you very much!

**Comment by itsbchen** [comment]
Did you change it, recently? Or, it was always arrows on the left and the right?

Thanks

**Comment by innesst** [comment]
I to was a bit confused at first. Perhaps you could change the icon for skip track to have the vertical line, like this. 
![skip_forward-01-512](https://user-images.githubusercontent.com/10469898/78993165-137c6e80-7b0b-11ea-9477-eb68a5d5aabb.png)

**Comment by itsbchen** [comment]
@innesst 
This is the newest version 5.0.1.
I just reversed to 4.3.3. I needed to uninstall 5.0.1 and open 4.3.3. 
https://github.com/PaulWoitaschek/Voice/releases/tag/4.3.3
Also, the 4.3.3 has day/night theme.

**Comment by innesst** [comment]
Yes, I have 5.01. this is the arrow I'm taking about 
![Screenshot_20200410-204036](https://user-images.githubusercontent.com/10469898/79031271-a3ea9b80-7b6b-11ea-87d5-bb724d9f0b0f.png)

**Comment by itsbchen** [comment]
@innesst you should make a new request. I think Paul closed it off.
