### ISSUE TITLE
I would like have the older night theme

### ISSUE THREAD

**Issue by itsbchen** [PaulWoitaschek/Voice#971]
Dark Mode in my Samsung Galaxy s9+ works, but in Voice, I prefer the older version.

Is it possible to use a older version for my use?

App-Version: 5.0.1
Phone Name: samsung Galaxy 9+
Android Version: 10

**Comment by itsbchen** [comment]
![SmartSelect_20200410-062117_Google](https://user-images.githubusercontent.com/26336661/78984259-d22c9480-7af3-11ea-858c-2772bb3acb2f.jpg)

I am using Dark Mode, but everything is weird now.

**Comment by PaulWoitaschek** [comment]
Yes, you can download it on the releases tab.
