### ISSUE TITLE
F-Droid version stops at 4.3.3

### ISSUE THREAD

**Issue by Pentaphon** [PaulWoitaschek/Voice#972]
Any reason why we haven't gotten 5.x versions on F-Droid?

**Comment by PaulWoitaschek** [comment]
I don't know. You can open an issue there:
https://gitlab.com/fdroid/fdroiddata/-/issues

**Comment by Pentaphon** [comment]
@PaulWoitaschek they replied with: 

>Unfortunately automatic updates aren't that easy. See maintainer notes at the end: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.ph1b.audiobook.yml

https://gitlab.com/fdroid/fdroiddata/-/issues/2010
