### ISSUE TITLE
Titles are broken on opus files

### ISSUE THREAD

**Issue by Emilv2** [PaulWoitaschek/Voice#977]
Please include the following details in your bug report:

App-Version: 5.0.1
Phone Name:
Android Version:

One of the last versions broke this, it used to work. Before the correct title was shown, now it just shows the comment tag. I can provide an example file if needed.

**Comment by PaulWoitaschek** [comment]
Yes, always. Without a sample file there is almost never anything I can do.

**Comment by Emilv2** [comment]
The title should be "A Long-Expected Party (2014)", but "cover.jpg" is shown.
[opus_file.zip](https://github.com/PaulWoitaschek/Voice/files/4488459/opus_file.zip)

**Comment by Emilv2** [comment]
Thanks for the quick fix!

**Comment by Emilv2** [comment]
It seems like you forgot to push this update to the Play Store  :)
