### ISSUE TITLE
Missing previously displayed widget on dragdown menu on s9 android

### ISSUE THREAD

**Issue by heartofstone** [PaulWoitaschek/Voice#979]
**Describe the bug**
I don't know if this is a bug in your software as this is a function that I have used before.
I have a library of maybe  150GB of audiobooks on my sd card in samsung s9.
I no longer get the controls and now playing widget when the app is playing but not in the foreground.
this always used to work.

also there is an intermittent issue of sometime the app playing but not appearing. maybe this is because my library is large.

**To Reproduce**
I am sorry I don't know.
have an s9, have a library of 150GB of audiobooks. drag down the menu from the top to display android menu such as wifi, torch etc.
now playing media should be there.

**Expected behavior**
I expected to see the same widget previously displayed.

By the way, really good workon this app. I am very impressed. this has been my first choice for audiobooks for a good while now. Thank you.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
If the issue is somehow related to media (not being recognized, not playing, showing wrong metadata etc) please attach a file that demonstrates the issue or email it to me at woitaschek+voicemedia@gmail.com

**Comment by PaulWoitaschek** [comment]
> I no longer get the controls and now playing widget when the app is playing but not in the foreground.
this always used to work.

Do you mean the notficiation is there when the player is playing?
Maybe you accidentially blocked the notification?

**Comment by heartofstone** [comment]
Resolved! thank you.
