### ISSUE TITLE
Incorrect file names - problems with fonts and russian names.

### ISSUE THREAD

**Issue by Dakuort** [PaulWoitaschek/Voice#980]
**Describe the bug**
The problem with the section (file) names - problem with fonts - sometimes when file names are in russian language in programme it is not shown correctly.

**To Reproduce**
Steps to reproduce the behaviour - please try to download and use some audiobooks with russian letters or russian names.

**Expected behavior**

**Screenshots**
![Screenshot_2020-04-20-23-09-31-366_de ph1b audiobook](https://user-images.githubusercontent.com/64041053/79795255-51c02c00-835c-11ea-92b6-508a63aa01ed.jpg)
![Screenshot_2020-04-20-23-09-38-507_de ph1b audiobook](https://user-images.githubusercontent.com/64041053/79795291-5be22a80-835c-11ea-98d1-b0b0a5e3bc62.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi mi9t
 - OS: android 10
 - Browser: google

**Additional context**
If the issue is somehow related to media (not being recognized, not playing, showing wrong metadata etc) please attach a file that demonstrates the issue or email it to me at woitaschek+voicemedia@gmail.com - the audio file with a problem i will send by e-mail.

**Comment by PaulWoitaschek** [comment]
Please read the issue template. There is nothing I can do without an example file.

**Comment by PaulWoitaschek** [comment]
As far I can tell the file you sent me is parsed correctly. Where did you get that file from?

This is the ffprobe output:
```
Input #0, mp3, from '001 - В место предисловия.mp3':
  Metadata:
    title           : Â ìåñòî ïðåäèñëîâèÿ
    artist          : Ñåðãåé Ëóêüÿíåíêî
    album           : Ëîðä ñ ïëàíåòû Çåìëÿ. Èãðà ñòîèò ïðèíöåññû
    track           : 01/61
  Duration: 00:04:27.22, start: 0.000000, bitrate: 112 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 112 kb/s
```

This is how it shows up in vlc
![image](https://user-images.githubusercontent.com/743462/79828167-73430700-83a0-11ea-9ecd-295b23e5324e.png)
