### ISSUE TITLE
"Shake to resume" feature missing in v5.0.2

### ISSUE THREAD

**Issue by rottenkumquat** [PaulWoitaschek/Voice#981]
"Shake to resume" feature missing in v5.0.2. Was there up until v5.0.1.

App-Version: v5.0.2
Phone Name: Xiaomi Mi A1
Android Version: 9

**Comment by PaulWoitaschek** [comment]
> * After the sleep timer ended, for 30 seconds you have the chance to shake the phone to restart the playback. The feature is now always active without a toggle.
