### ISSUE TITLE
[Bug] The widget on the lock screen doesn't work after idle 

### ISSUE THREAD

**Issue by MagTun** [PaulWoitaschek/Voice#982]
I always have the voice widget on my lock screen. But it can't use it to play my audio if Voice have been idle for some time. This bug doesn't happen with the widget on the home screen (where all the app shortcuts are). 
If the lock screen widget doesn't work, I have to "enter" my phone, press play on the home screen widget and then I can use the lock screen widget. (Sometimes, but not always, I can also fix this bug by starting voice from my Bluetooth headset).

**Comment by MagTun** [comment]
After a bit more debugging, it seems the problem is not really in the widget but in the play/pause button: the button displays the pause symbol even though the audio is already paused. If I press on the back button, then the pause symbol becomes a play symbol and if I click this play button then it's working. So the widget is working, but the problem seems to be that it doesn't receive/process the event that has paused the audio.

**Comment by WiliTest** [comment]
I have the same problem.

**Comment by WiliTest** [comment]
To be clear there are 2 problems. 
<S>1) the lockscreen widget was not responsive at all. It has been solved in the previous update.</s>
2) when I want to listen to a song from the locked screen, I press on the play `►` button of the widget, but nothing happens. I need to press the `<<` or `>>`then `►` again, and it will play.  

(Phone is a redmi 7A, MIUI11 android 9, last version of your app)

**Comment by PaulWoitaschek** [comment]
Thanks for the report! I assume this is fixed.
Please open a new ticket if this still is present in version 6+!
