### ISSUE TITLE
Display always staying awake / always-on-display gets triggered

### ISSUE THREAD

**Issue by nioncode** [PaulWoitaschek/Voice#983]
When running Voice and turning off my screen, it immediately turns back on and it looks like the Always-On-Display is getting triggered: the lock icon gets displayed, the current time is visible as well as the battery percentage. In the middle of the screen, the Voice notification is displayed.

I have Always-On-Display DISABLED in my phone and it never shows up when using any other audio app (like PocketCasts, Google Play Music), but somehow it gets triggered by Voice.

I think this only appeared since the v5.0 update.

Phone: Google Pixel 2, Android 10

**Comment by PaulWoitaschek** [comment]
This should be fixed with Voice 7+, if not please open a new ticket.
