### ISSUE TITLE
[Bug] Audiobook doesn't start anymore when opening app

### ISSUE THREAD

**Issue by EJH83** [PaulWoitaschek/Voice#986]
Since the last version it seems like the setting to start playing an audiobook when opening the voice app isn't available anymore. You have to push the play button to start the book.

Love the app, kind regards!

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
