### ISSUE TITLE
Big autoBookDB leads to scanning slow down, crashes, corruption. 

### ISSUE THREAD

**Issue by nyahwhy** [PaulWoitaschek/Voice#989]
My autoBookDB is ~7MB now and adding new books takes several minutes, sometimes leads to apps freezing / getting killed and it can take a couple of restarts to get new books to show up. One time I had to restore app data from a backup because the app would not start any more after getting killed by android. 

Checked what's in the autoBookDB file - and there are a LOT of filenames that don't exist any more and that I haven't seen in a long time. I assume that's what the problem is, because it looked the same the last time this happened and other than those "phantom files" nothing much changed after I reinstalled the app (which fixed it, temporarily). 

Purging all app data isn't always a good option since that means loosing progress markers on all audio books that are still present. A button to remove old books (all files not present in the file system) or something like that would be great.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
