### ISSUE TITLE
issue: when playing audiobooks whilst phone is on silent, constant vibrations

### ISSUE THREAD

**Issue by heartofstone** [PaulWoitaschek/Voice#996]
If my phone (samsung s9) is on silent, and I listen to an audiobook, i get constant vibration alerts

**Describe the solution you'd like**
no more vibrations.

**Describe alternatives you've considered**
I'm not sure why this is happening

**Additional context**
nothing further. great app by the way. I very much appreciate it.

**Comment by PaulWoitaschek** [comment]
Thanks for your report. 
I assume this issue is fixed as this issue is ancient and a lot changed in the meantime. If not please open a new issue.
